# TODO:

Politics / Mentions: two promising wallets
0x9e8ecc4cb3c4e48f544cba2fbbb252a6a65e8db8	
0x0cb10c40b0776e9ee8cef970af85724654dda76c

# Wallet Strategy Selection

This stage tracks two distinct wallet groups on the full trade stream (BUY + SELL):

- `copyable_group`: wallets that pass base eligibility and strong copyability thresholds.
- `predicting_group`: the remaining eligible wallets (not in copyable) that pass a predictability score threshold.

Notes:
- Group membership is threshold-based (absolute scores), not target-count based.
- Open-buy skill metrics are kept for diagnostics/legacy comparison.
- `selected_wallets_v2.parquet` stores both groups with a `wallet_group` label.
- Stage2 backtest uses only `predicting_group`.

In [674]:
%load_ext autoreload
%autoreload 2

import datetime
from pathlib import Path
import json

import numpy as np
import pandas as pd
import pyarrow.dataset as ds

np.set_printoptions(precision=4, suppress=True)
pd.options.display.float_format = '{:.2f}'.format

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

## Configuration

In [675]:
# ── configuration ─────────────────────────────────────────────────────────────
RECENCY_DAYS     = 90

PRICE_BUCKET_BINS   = [0.0, 0.1, 0.25, 0.4, 0.6, 0.75, 0.9, 1.0]
PRICE_BUCKET_LABELS = [
    "0.00-0.10", "0.10-0.25", "0.25-0.40", "0.40-0.60",
    "0.60-0.75", "0.75-0.90", "0.90-1.00",
]

TRADES_DIR    = Path("../../data/polygon_trades_processed")
WORKSPACE_DIR = Path("../../data/trade_signals_workspace_v2")
WORKSPACE_DIR.mkdir(parents=True, exist_ok=True)

dataset = ds.dataset(TRADES_DIR, format="parquet")
TAGS = set(['Politics'])
# TAGS = set(['Weather'])
# TAGS = set(['Politics'])
# TAGS = set(['Awards'])
# TAGS = set(['MrBeast', 'Trump', 'Elections', 'Celebrities', 'Elon Musk', 'YouTube'])

WALLET_FILTER = None
# WALLET_FILTER = [
#     '0x919698b19427cbe6945b0dc823f2d9e126a4d934',
#     '0x85d22a973e817f87afe0a7fd346a39823cce7479',
#     '0x6011655c4afb76f36dd1b08a137a1ba73466b31e',
#     '0x5f612351a9e46afbe3f164473a7d77a69ec9840a',
# ]
DATASET_COLUMNS        = set(dataset.schema.names)
TRIGGER_TX_HASH_COLUMN = (
    "transaction_hash" if "transaction_hash" in DATASET_COLUMNS
    else ("tx_hash" if "tx_hash" in DATASET_COLUMNS else None)
)

## Derive train/test dates from data

## Full-stream wallet metrics for copy-trigger selection

Build per-wallet metrics on the full training trade stream (BUY + SELL).
Copyability is considered here (stage1), not in stage0 filtering.

In [676]:
from polymarket_analysis.wallet_selection.volatility import (
    compute_wallet_metrics,
    filter_wallets_by_volatility,
)

from polymarket_analysis.data.data_catalogue import load_markets_processed
mdf = load_markets_processed()

print(mdf.groupby('primary_tag').size().sort_values(ascending=False).head(20))

mdf = mdf[
    # (TAGS is None or mdf['primary_tag'].isin(TAGS))
    ~(mdf['primary_tag'].isin(['Sports', 'Crypto']))
    & ((TAGS is None) or mdf["tags"].apply(lambda tags: any(tag in TAGS for tag in tags)))
    & (mdf['winner_token_id'].notna())
].copy().reset_index(drop=True)

print(f'selected markets for tags {TAGS}: {len(mdf)}')

primary_tag
Sports         1210077
Crypto          688468
Weather          96837
Politics         66598
Finance          36574
Awards            9743
Movies            8981
Music             6295
Culture           5726
AI                4491
All               3808
Esports           3671
Business          3086
MrBeast           1714
Science           1665
Trump             1245
Iran              1213
box office        1122
Celebrities       1053
Elections          889
dtype: int64
selected markets for tags {'Politics'}: 44273

In [677]:
# Load full processed trades for the full-stream path
trade_files = sorted(TRADES_DIR.glob("*.parquet"))
df_full = pd.concat(
    [pd.read_parquet(f).merge(mdf, on="condition_id", how="inner") for f in trade_files], ignore_index=True
    )

# df_full = df_full[
#     (df_full['avg_price'] <= 1) 
#     # (df_full['side'] == 'BUY') 
#     ()
#     ].copy().reset_index(drop=True)

# df_full = df_full.merge(mdf, on="condition_id", how="inner")

if TAGS is not None:
    df_full = df_full[df_full['primary_tag'].isin(TAGS)].copy().reset_index(drop=True)

df_full['outcome'] = df_full['outcome_x']
del df_full['outcome_x'], df_full['outcome_y']

df_full["dt"] = pd.to_datetime(df_full["dt"], utc=True)

# Normalise grouped schema → canonical fill-level names
if "total_quantity" in df_full.columns and "quantity" not in df_full.columns:
    df_full = df_full.rename(columns={
        "total_quantity": "quantity",
        "avg_price": "price",
        "trade_value_usdc": "usdc_amount",
    })

df_full["usdc_amount"] = df_full["usdc_amount"].astype(float)
df_full["final_value_usdc"] = df_full["final_value_usdc"].astype(float)
df_full["quantity"] = df_full["quantity"].astype(float)

# Full-stream PnL / notional across BUY + SELL
df_full["pnl"] = np.where(
    df_full["side"] == "BUY",
    df_full["final_value_usdc"] - df_full["usdc_amount"],
    df_full["usdc_amount"] - df_full["final_value_usdc"],
)
df_full["notional"] = np.where(
    df_full["side"] == "BUY",
    df_full["usdc_amount"],
    df_full["quantity"] * (1 - df_full["price"].astype(float)),
)

df_slice = df_full[df_full["is_train"]].copy()

wallet_vol_train, _ = compute_wallet_metrics(df_slice)
del df_slice
print(len(wallet_vol_train))

/Users/vobornij/Library/Caches/pypoetry/virtualenvs/polymarket-analysis-BY1ldWyW-py3.13/lib/python3.13/site-packages/pandas/core/arraylike.py:399: RuntimeWarning:

invalid value encountered in sqrt

34135

In [678]:
df_full.head()

,wallet,condition_id,token_id,dt,side,position,quantity,price,usdc_amount,final_value_usdc,trade_pnl,copyable_pnl,token_winner,final_price,last_condition_trade_ts,tx_hash,num_fills,is_train,copyable_qty,avail_copy_qty,avail_copy_total_vol,avail_copy_count,copyable_qty_098,copyable_qty_095,copyable_qty_090,avail_copy_qty_098,avail_copy_qty_095,avail_copy_qty_090,end_date_iso,question,tags,primary_tag,winner_token_id,outcome,pnl,notional
0,0x00000ba68703bce9c2ff4be7177145c1bb3e9ac5,0x098afead2c41677b0f09ae9d0013ca520eacdb3f0d7c8985c6581de7a0e9ac37,25765184634765339363827807992411986670067641678875992164214223288175352348465,2026-05-18 05:53:53+00:00,BUY,5000.00,5000.00,0.14,700.00,0.00,-700.00,-56.59,False,0.00,2026-05-22 06:11:42+00:00,0x0608e4eeb4f28612dfee57a202a790d2f183d4e251f0fcd7dd682685834d9d4d,1,True,404.23,404.23,52.55,2.00,404.23,404.23,0.00,404.23,404.23,0.00,2026-05-21T00:00:00Z,Iran closes its airspace by May 21?,"[Politics, Iran, Geopolitics, U.S. x Iran]",Politics,112135611227049632102833296892649508522129989874688677403193353750752980311218,Yes,-700.00,700.00
1,0x00000ba68703bce9c2ff4be7177145c1bb3e9ac5,0x098afead2c41677b0f09ae9d0013ca520eacdb3f0d7c8985c6581de7a0e9ac37,25765184634765339363827807992411986670067641678875992164214223288175352348465,2026-05-19 10:50:26+00:00,BUY,5500.00,500.00,0.13,63.00,0.00,-63.00,-33.49,False,0.00,2026-05-22 06:11:42+00:00,0x2f6aaa6d6f26ca01bb3326f842fdd7d235b4bc2f8f87b3339afbae215475c339,3,True,265.82,265.82,78.05,27.00,188.89,188.89,141.25,188.89,188.89,141.25,2026-05-21T00:00:00Z,Iran closes its airspace by May 21?,"[Politics, Iran, Geopolitics, U.S. x Iran]",Politics,112135611227049632102833296892649508522129989874688677403193353750752980311218,Yes,-63.00,63.00
2,0x00090e8b4fa8f88dc9c1740e460dd0f670021d43,0x09b3e4c716df2579afa0ede1bf00edd84f8cbe1e335785f90336e7a909c52f8e,98045093822431547938365423095786421804452886266888528428746910959667685407691,2025-09-29 16:48:21+00:00,BUY,159.75,159.75,0.68,108.63,159.75,51.12,0.00,True,1.00,2025-10-01 06:28:39+00:00,0x135f651765de9f28e983b907579bae719e65327ff2aa34bbafd61133a908fe2b,1,True,-0.00,-0.00,-0.00,0.00,0.00,-0.00,-0.00,0.00,-0.00,-0.00,2025-10-01T00:00:00Z,US government shutdown by October 1?,"[Politics, Trump, Congress, funding, Trump Presidency, house, Gov Shutdown, 2025 Predictions, Ec...",Politics,98045093822431547938365423095786421804452886266888528428746910959667685407691,Yes,51.12,108.63
3,0x00090e8b4fa8f88dc9c1740e460dd0f670021d43,0x09b3e4c716df2579afa0ede1bf00edd84f8cbe1e335785f90336e7a909c52f8e,98045093822431547938365423095786421804452886266888528428746910959667685407691,2025-09-29 16:49:53+00:00,BUY,199.75,40.00,0.68,27.20,40.00,12.80,0.00,True,1.00,2025-10-01 06:28:39+00:00,0x10cd71c2b0bb27d47abdca8a42fef5349175fd548de7081975bb317eb058d3f2,1,True,-0.00,-0.00,-0.00,0.00,0.00,-0.00,-0.00,0.00,-0.00,-0.00,2025-10-01T00:00:00Z,US government shutdown by October 1?,"[Politics, Trump, Congress, funding, Trump Presidency, house, Gov Shutdown, 2025 Predictions, Ec...",Politics,98045093822431547938365423095786421804452886266888528428746910959667685407691,Yes,12.80,27.20
4,0x00090e8b4fa8f88dc9c1740e460dd0f670021d43,0x09b3e4c716df2579afa0ede1bf00edd84f8cbe1e335785f90336e7a909c52f8e,98045093822431547938365423095786421804452886266888528428746910959667685407691,2025-09-29 16:50:03+00:00,BUY,209.12,9.38,0.68,6.38,9.38,3.00,0.00,True,1.00,2025-10-01 06:28:39+00:00,0x6d6e5452e4682305c761e730129aecd3f9d4c078b85fe27ef1d701fa223c72a8,1,True,-0.00,-0.00,-0.00,0.00,0.00,-0.00,-0.00,0.00,-0.00,-0.00,2025-10-01T00:00:00Z,US government shutdown by October 1?,"[Politics, Trump, Congress, funding, Trump Presidency, house, Gov Shutdown, 2025 Predictions, Ec...",Politics,98045093822431547938365423095786421804452886266888528428746910959667685407691,Yes,3.00,6.38

In [679]:
# mdf = load_markets_processed()
# df_full = pd.concat(
#     [
#         (
#             pd.read_parquet(f)
#             .merge(mdf, on="condition_id", how="inner")
#             .assign(dt=lambda df: pd.to_datetime(df["dt"], utc=True))
#             .loc[lambda df: df["dt"] >=  datetime.datetime(2026, 7, 1, tzinfo=datetime.timezone.utc)]
#         )
#         for f in trade_files
#     ],
#     ignore_index=True,
# )

In [680]:
print (df_full.columns)
print(df_full.index.names)

Index(['wallet', 'condition_id', 'token_id', 'dt', 'side', 'position',
       'quantity', 'price', 'usdc_amount', 'final_value_usdc', 'trade_pnl',
       'copyable_pnl', 'token_winner', 'final_price',
       'last_condition_trade_ts', 'tx_hash', 'num_fills', 'is_train',
       'copyable_qty', 'avail_copy_qty', 'avail_copy_total_vol',
       'avail_copy_count', 'copyable_qty_098', 'copyable_qty_095',
       'copyable_qty_090', 'avail_copy_qty_098', 'avail_copy_qty_095',
       'avail_copy_qty_090', 'end_date_iso', 'question', 'tags', 'primary_tag',
       'winner_token_id', 'outcome', 'pnl', 'notional'],
      dtype='object')
[None]

In [681]:
df_full['copyable_pnl_098'] = np.where(
    df_full['side'] == 'BUY',
    (df_full['final_price'] - df_full['price'] * 0.98) * df_full['copyable_qty_098'],
    (df_full['price']/0.98 - df_full['final_price']) * df_full['copyable_qty_098']
)

df_full['copyable_pnl_095'] = np.where(
    df_full['side'] == 'BUY',
    (df_full['final_price'] - df_full['price'] * 0.95) * df_full['copyable_qty_095'],
    (df_full['price']/0.95 - df_full['final_price']) * df_full['copyable_qty_095']
)

df_full['copyable_pnl_090'] = np.where(
    df_full['side'] == 'BUY',
    (df_full['final_price'] - df_full['price'] * 0.90) * df_full['copyable_qty_090'],
    (df_full['price']/0.90 - df_full['final_price']) * df_full['copyable_qty_090']
)

# (
#     df_full[df_full['side'] == 'BUY']
#     .groupby(['primary_tag', 'wallet'], as_index=False)
#     .agg(
#         trade_count=('wallet', 'count'),
#         copyable_pnl=('copyable_pnl', 'sum'),
#         copyable_pnl_098=('copyable_pnl_098', 'sum'),
#         copyable_pnl_095=('copyable_pnl_095', 'sum'),
#         copyable_pnl_090=('copyable_pnl_090', 'sum'),
#     )
#     .query('trade_count > 100 and copyable_pnl > 1000')
#     .groupby('primary_tag', as_index=False)
#     .sum(numeric_only=True)
#     .sort_values('copyable_pnl', ascending=False)
# )

In [682]:
df_full['copyable_notional'] = df_full['notional'] * (df_full['copyable_pnl'] / df_full['pnl'].replace(0, np.nan))
df_full['roi'] = df_full['pnl'] / df_full['notional'].replace(0, np.nan)
df_full['copyable_roi'] = df_full['copyable_pnl'] / df_full['copyable_notional'].replace(0, np.nan)

df_full.head()

,wallet,condition_id,token_id,dt,side,position,quantity,price,usdc_amount,final_value_usdc,trade_pnl,copyable_pnl,token_winner,final_price,last_condition_trade_ts,tx_hash,num_fills,is_train,copyable_qty,avail_copy_qty,avail_copy_total_vol,avail_copy_count,copyable_qty_098,copyable_qty_095,copyable_qty_090,avail_copy_qty_098,avail_copy_qty_095,avail_copy_qty_090,end_date_iso,question,tags,primary_tag,winner_token_id,outcome,pnl,notional,copyable_pnl_098,copyable_pnl_095,copyable_pnl_090,copyable_notional,roi,copyable_roi
0,0x00000ba68703bce9c2ff4be7177145c1bb3e9ac5,0x098afead2c41677b0f09ae9d0013ca520eacdb3f0d7c8985c6581de7a0e9ac37,25765184634765339363827807992411986670067641678875992164214223288175352348465,2026-05-18 05:53:53+00:00,BUY,5000.00,5000.00,0.14,700.00,0.00,-700.00,-56.59,False,0.00,2026-05-22 06:11:42+00:00,0x0608e4eeb4f28612dfee57a202a790d2f183d4e251f0fcd7dd682685834d9d4d,1,True,404.23,404.23,52.55,2.00,404.23,404.23,0.00,404.23,404.23,0.00,2026-05-21T00:00:00Z,Iran closes its airspace by May 21?,"[Politics, Iran, Geopolitics, U.S. x Iran]",Politics,112135611227049632102833296892649508522129989874688677403193353750752980311218,Yes,-700.00,700.00,-55.46,-53.76,-0.00,56.59,-1.00,-1.00
1,0x00000ba68703bce9c2ff4be7177145c1bb3e9ac5,0x098afead2c41677b0f09ae9d0013ca520eacdb3f0d7c8985c6581de7a0e9ac37,25765184634765339363827807992411986670067641678875992164214223288175352348465,2026-05-19 10:50:26+00:00,BUY,5500.00,500.00,0.13,63.00,0.00,-63.00,-33.49,False,0.00,2026-05-22 06:11:42+00:00,0x2f6aaa6d6f26ca01bb3326f842fdd7d235b4bc2f8f87b3339afbae215475c339,3,True,265.82,265.82,78.05,27.00,188.89,188.89,141.25,188.89,188.89,141.25,2026-05-21T00:00:00Z,Iran closes its airspace by May 21?,"[Politics, Iran, Geopolitics, U.S. x Iran]",Politics,112135611227049632102833296892649508522129989874688677403193353750752980311218,Yes,-63.00,63.00,-23.32,-22.61,-16.02,33.49,-1.00,-1.00
2,0x00090e8b4fa8f88dc9c1740e460dd0f670021d43,0x09b3e4c716df2579afa0ede1bf00edd84f8cbe1e335785f90336e7a909c52f8e,98045093822431547938365423095786421804452886266888528428746910959667685407691,2025-09-29 16:48:21+00:00,BUY,159.75,159.75,0.68,108.63,159.75,51.12,0.00,True,1.00,2025-10-01 06:28:39+00:00,0x135f651765de9f28e983b907579bae719e65327ff2aa34bbafd61133a908fe2b,1,True,-0.00,-0.00,-0.00,0.00,0.00,-0.00,-0.00,0.00,-0.00,-0.00,2025-10-01T00:00:00Z,US government shutdown by October 1?,"[Politics, Trump, Congress, funding, Trump Presidency, house, Gov Shutdown, 2025 Predictions, Ec...",Politics,98045093822431547938365423095786421804452886266888528428746910959667685407691,Yes,51.12,108.63,0.00,-0.00,-0.00,0.00,0.47,NaN
3,0x00090e8b4fa8f88dc9c1740e460dd0f670021d43,0x09b3e4c716df2579afa0ede1bf00edd84f8cbe1e335785f90336e7a909c52f8e,98045093822431547938365423095786421804452886266888528428746910959667685407691,2025-09-29 16:49:53+00:00,BUY,199.75,40.00,0.68,27.20,40.00,12.80,0.00,True,1.00,2025-10-01 06:28:39+00:00,0x10cd71c2b0bb27d47abdca8a42fef5349175fd548de7081975bb317eb058d3f2,1,True,-0.00,-0.00,-0.00,0.00,0.00,-0.00,-0.00,0.00,-0.00,-0.00,2025-10-01T00:00:00Z,US government shutdown by October 1?,"[Politics, Trump, Congress, funding, Trump Presidency, house, Gov Shutdown, 2025 Predictions, Ec...",Politics,98045093822431547938365423095786421804452886266888528428746910959667685407691,Yes,12.80,27.20,0.00,-0.00,-0.00,0.00,0.47,NaN
4,0x00090e8b4fa8f88dc9c1740e460dd0f670021d43,0x09b3e4c716df2579afa0ede1bf00edd84f8cbe1e335785f90336e7a909c52f8e,98045093822431547938365423095786421804452886266888528428746910959667685407691,2025-09-29 16:50:03+00:00,BUY,209.12,9.38,0.68,6.38,9.38,3.00,0.00,True,1.00,2025-10-01 06:28:39+00:00,0x6d6e5452e4682305c761e730129aecd3f9d4c078b85fe27ef1d701fa223c72a8,1,True,-0.00,-0.00,-0.00,0.00,0.00,-0.00,-0.00,0.00,-0.00,-0.00,2025-10-01T00:00:00Z,US government shutdown by October 1?,"[Politics, Trump, Congress, funding, Trump Presidency, house, Gov Shutdown, 2025 Predictions, Ec...",Politics,98045093822431547938365423095786421804452886266888528428746910959667685407691,Yes,3.00,6.38,0.00,-0.00,-0.00,0.00,0.47,NaN

In [683]:
wallet_vol_test, _ = compute_wallet_metrics(df_full[~df_full["is_train"]].copy())

/Users/vobornij/Library/Caches/pypoetry/virtualenvs/polymarket-analysis-BY1ldWyW-py3.13/lib/python3.13/site-packages/pandas/core/arraylike.py:399: RuntimeWarning:

invalid value encountered in sqrt

In [684]:
df_test=wallet_vol_test.sort_values('copyable_pnl', key=abs, ascending=False)

In [685]:
len(df_full[
    (df_full['wallet'] == '0x919698b19427cbe6945b0dc823f2d9e126a4d934')
    & ~df_full["is_train"]
])

0

In [686]:
df_full['bucket'] = df_full['dt'].dt.round("5min")

In [687]:
# # WALLET COMBINATION CELL

# df = df_full[
#     (df_full['wallet'].isin(wallet_cohorts['predicting_group']['wallet']) | df_full['wallet'].isin(wallet_cohorts['copyable_group']['wallet']) | df_full['wallet'].isin(WALLET_FILTER))
#      & (df_full["is_train"])].copy()

# df['is_predicting_group'] = df['wallet'].isin(wallet_cohorts['predicting_group']['wallet'])
# df['is_filter_group'] = df['wallet'].isin(WALLET_FILTER)
# df['is_copyable_group'] = df['wallet'].isin(wallet_cohorts['copyable_group']['wallet']) & ~df['is_filter_group']



# print(f'predicting_size: {len(wallet_cohorts["predicting_group"]["wallet"])}')
# print(f'copyable_size: {len(wallet_cohorts["copyable_group"]["wallet"])}')

# print('\n')
# print('*** Total PnL / Copyable PnL before filtering ***')
# print(df[['pnl', 'copyable_pnl']].sum())
# print(f'wallet_roi={df["pnl"].sum() / df["notional"].sum()}')
# print(f'copyable_roi={df["copyable_pnl"].sum() / df["copyable_notional"].sum()}')


# print('\n')
# print('*** Predicting group PnL ***')
# print(df[df['is_predicting_group']][['pnl', 'copyable_pnl']].sum())
# print(f'wallet_roi={df[df["is_predicting_group"]]["pnl"].sum() / df[df["is_predicting_group"]]["notional"].sum()}')
# print(f'copyable_roi={df[df["is_predicting_group"]]["copyable_pnl"].sum() / df[df["is_predicting_group"]]["copyable_notional"].sum()}')

# print('\n')
# print('*** Copyable group PnL ***')
# print(df[df['is_copyable_group']][['pnl', 'copyable_pnl']].sum())
# print(f'wallet_roi={df[df["is_copyable_group"]]["pnl"].sum() / df[df["is_copyable_group"]]["notional"].sum()}')
# print(f'copyable_roi={df[df["is_copyable_group"]]["copyable_pnl"].sum() / df[df["is_copyable_group"]]["copyable_notional"].sum()}')

# df = df.groupby(['bucket', 'token_id', 'side']).agg(
#     copyable_pnl=('copyable_pnl', 'sum'),
#     wallet_count=('wallet', 'nunique'),
#     pnl=('pnl', 'sum'),
#     predicting_group_count=('is_predicting_group', 'sum'),
#     copyable_group_count=('is_copyable_group', 'sum'),
#     wallet_in_filter_count=('is_filter_group', 'sum'),
#     notional=('notional', 'sum'),
#     copyable_notional=('copyable_notional', 'sum'),
# )
# df.reset_index(inplace=True)
# df = df[
#     ((df['wallet_count'] > 1)
#     & (df['predicting_group_count'] <= 0)
#     & (df['copyable_group_count'] >= 0)
#      & (df['wallet_in_filter_count'] >= 0) )
#       | ( df['wallet_count'] == df['wallet_in_filter_count'])
#      ]

# print('\n')
# print('*** Combined PnL ***')
# print(df[['pnl', 'copyable_pnl']].sum())
# print(f'wallet_roi={df["pnl"].sum() / df["notional"].sum() if "notional" in df.columns else np.nan}')
# print(f'copyable_roi={df["copyable_pnl"].sum() / df["copyable_notional"].sum() if "copyable_notional" in df.columns else np.nan}')

In [688]:
wallet_vol_train['copyable_pnl_factor'] = np.clip(
    wallet_vol_train['copyable_pnl'] / wallet_vol_train['total_pnl'].replace(0, np.nan),
    0,
    1.0,
).fillna(0.0)
wallet_vol_train['copyable_roi'] = wallet_vol_train['average_roi'] * wallet_vol_train['copyable_pnl_factor']

# Keep sorting deterministic for downstream filtering/inspection.
wallet_vol_train.sort_values('copyable_roi', ascending=False, inplace=True)
wallet_vol_train.reset_index(drop=True, inplace=True)

In [689]:
wallet_cohorts = {}

In [690]:
print(len(wallet_vol_train))
wallet_vol_train.head()

34135

,wallet,num_buckets,trade_count,total_notional,total_pnl,copyable_pnl,num_markets,median_dt,median_roi,average_roi,max_drawdown,max_copyable_drawdown,buy_pnl,buy_quantity,sell_pnl,sell_quantity,buy_notional,sell_notional,buy_copyable_quantity,buy_copyable_pnl,sell_copyable_quantity,sell_copyable_pnl,buy_roi,sell_roi,buy_copyable_notional,top5_pnl_pct,top10_pnl_pct,worst5_pnl_pct,positive_bucket_share,top_market_pnl_pct,top_market_abs_pnl_pct,market_pnl_hhi,pnl_volatility,max_drawdown_to_pnl,max_copyable_drawdown_to_copyable_pnl,return,copyable_pnl_factor,copyable_roi
0,0x8da0d29ec66508950ad72846ac3164db7cc41c53,1,1,2.50,205.83,205.83,1,2026-04-03 19:40:00+00:00,82.33,82.33,0.00,0.00,205.83,208.33,0.00,0.00,2.50,0.00,208.33,205.83,0.00,0.00,0.99,0.00,2.50,1.00,1.00,1.00,1.00,1.00,1.00,1.00,NaN,0.00,0.00,82.33,1.00,82.33
1,0x6d220c14b74f1051783fc5e1025841496cd4ff68,2,2,196.15,145.85,193.57,1,2025-03-20 12:50:00+00:00,70.43,70.43,193.76,0.00,339.61,342.00,-193.76,194.93,2.39,193.76,194.93,193.57,0.00,-0.00,0.99,-0.99,1.36,1.00,1.00,1.00,1.00,1.00,1.00,1.00,4.85,1.33,0.00,0.74,1.00,70.43
2,0xf9a2c6ccf96b1651f98f666700d24a835857290c,1,1,50.00,3325.32,3325.32,1,2026-04-03 13:40:00+00:00,66.51,66.51,0.00,0.00,3325.32,3375.32,0.00,0.00,50.00,0.00,3375.32,3325.32,0.00,0.00,0.99,0.00,50.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,NaN,0.00,0.00,66.51,1.00,66.51
3,0x782d96e81d5aabc9ca316914f5fa656a11ebed8a,12,15,980.25,96.84,313.02,3,2026-04-05 07:25:00+00:00,100.01,62.32,656.96,4.90,676.74,1077.09,-579.90,808.19,255.76,724.49,393.21,297.92,91.84,15.10,0.63,-0.72,93.37,9.10,1.00,-7.89,0.62,1.58,0.73,0.61,30.69,6.78,0.02,0.10,1.00,62.32
4,0x69f8c4434bf303a65141db9e3a92862d334a08c1,1,1,2.09,114.02,106.18,1,2026-04-02 09:05:00+00:00,54.56,54.56,0.00,0.00,114.02,116.11,0.00,0.00,2.09,0.00,108.13,106.18,0.00,0.00,0.98,0.00,1.95,1.00,1.00,1.00,1.00,1.00,1.00,1.00,NaN,0.00,0.00,54.56,0.93,50.81

In [691]:
# Final wallet selection: threshold-based copyable + predicting groups
# COPYABLE_SCORE_MIN = -1
# PREDICTING_SCORE_MIN = -2

candidates = wallet_vol_train.copy()

for col, default in {
    'top10_pnl_pct': np.nan,
    'top_market_abs_pnl_pct': np.nan,
    'market_pnl_hhi': np.nan,
    'positive_bucket_share': np.nan,
}.items():
    if col not in candidates.columns:
        candidates[col] = default

for col in [
    'average_roi', 'median_roi', 'num_buckets', 'num_markets',
    'pnl_volatility', 'max_drawdown_to_pnl',
    'top_market_pnl_pct', 'top_market_abs_pnl_pct', 'top5_pnl_pct', 'top10_pnl_pct', 'market_pnl_hhi',
    'copyable_roi', 'copyable_pnl_factor', 'copyable_pnl', 'total_notional',
    'max_copyable_drawdown_to_copyable_pnl', 'worst5_pnl_pct', 'positive_bucket_share',
]:
    if col in candidates.columns:
        candidates[col] = pd.to_numeric(candidates[col], errors='coerce')

base_mask = (
    (candidates['buy_roi'] >= 0.05)
    # & (candidates['median_roi'] >= 0)
    & (candidates['num_buckets'] >= 20)
    & (candidates['num_markets'] >= 15)
    & (candidates['max_drawdown_to_pnl'] <= 0.2)
    & (candidates['top_market_pnl_pct'] < 0.25)
    # & (candidates['top5_pnl_pct'] < 0.55)
    # & (candidates['top10_pnl_pct'].fillna(0.85) < 0.8)
    # & (candidates['top_market_abs_pnl_pct'].fillna(candidates['top_market_pnl_pct']) < 0.25)
    & (candidates['market_pnl_hhi'].fillna(0.20) < 0.30)
    & (candidates['median_dt'].dt.date <= (pd.Timestamp.today().date() - pd.Timedelta(days=30)))
    & (candidates['total_notional'] >= 5_000)
)

base_mask2 = (
    (candidates['buy_roi'] >= 0.04)
    # & (candidates['median_roi'] >= 0)
    & (candidates['num_buckets'] >= 20)
    & (candidates['num_markets'] >= 15)
    & (candidates['max_drawdown_to_pnl'] <= 0.2)
    & (candidates['max_copyable_drawdown_to_copyable_pnl'] <= 0.3)
    # & (candidates['top_market_pnl_pct'] < 0.25)
    # & (candidates['top5_pnl_pct'] < 0.55)
    # & (candidates['top10_pnl_pct'].fillna(0.85) < 0.8)
    & (candidates['market_pnl_hhi'].fillna(0.20) < 0.2)
    & (candidates['median_dt'].dt.date <= (pd.Timestamp.today().date() - pd.Timedelta(days=30)))
    & (candidates['total_notional'] >= 1_000)
)

eligible_base = candidates[base_mask].copy()
if eligible_base.empty:
    raise ValueError('No wallets passed base eligibility filters.')

eligible_base['sample_mult'] = np.clip(
    np.log1p(eligible_base['num_buckets']) / np.log(2000.0),
    0.20,
    1.00,
)
eligible_base['downside_tail'] = eligible_base['worst5_pnl_pct'].abs().fillna(0.0)
eligible_base['predictability_score'] = eligible_base['sample_mult'] * (
    # 2.5 * eligible_base['average_roi'].fillna(0.0)
    # + 1.5 * eligible_base['median_roi'].fillna(0.0)
    + 1.2 * (eligible_base['positive_bucket_share'].fillna(0.5) - 0.5)
    - 1.0 * eligible_base['pnl_volatility'].fillna(0.0)
    - 1.2 * eligible_base['max_drawdown_to_pnl'].fillna(0.0)
    - 0.8 * eligible_base['top_market_abs_pnl_pct'].fillna(eligible_base['top_market_pnl_pct']).fillna(0.0)
    - 0.6 * eligible_base['market_pnl_hhi'].fillna(0.0)
    - 0.5 * eligible_base['downside_tail']
)
eligible_base['predicting_final_score'] = eligible_base['predictability_score']

copyable_mask = (
    (eligible_base['copyable_pnl'] > 0)
    & (eligible_base['average_roi'] >= 0.04)
    # & (eligible_base['copyable_pnl_factor'] >= 0.1)
    & (eligible_base['copyable_roi'] >= 0.05)
    # & (eligible_base['median_roi'] >= 0.00)
    # & (eligible_base['average_roi'] >= 0.04)
    # & (
    #     eligible_base['max_copyable_drawdown_to_copyable_pnl']
    #     .fillna(eligible_base['max_drawdown_to_pnl'])
    #     .fillna(0.0)
    #     <= 0.3
    # )
)
copyable_candidates = eligible_base[copyable_mask].copy()
copyable_candidates['copyable_efficiency'] = copyable_candidates['copyable_pnl'].fillna(0.0) / (copyable_candidates['total_notional'].fillna(0.0) + 1.0)
copyable_candidates['copyable_dd_ratio'] = (
    copyable_candidates['max_copyable_drawdown_to_copyable_pnl']
    .fillna(copyable_candidates['max_drawdown_to_pnl'])
    .fillna(0.0)
)
copyable_candidates['copyable_score'] = (
    1.8 * copyable_candidates['copyable_roi'].fillna(0.0)
    + 1.2 * copyable_candidates['copyable_pnl_factor'].fillna(0.0)
    + 25.0 * copyable_candidates['copyable_efficiency'].clip(lower=-1.0, upper=1.0)
    - 0.8 * copyable_candidates['copyable_dd_ratio'].clip(lower=0.0)
    - 0.5 * copyable_candidates['top_market_abs_pnl_pct'].fillna(copyable_candidates['top_market_pnl_pct']).fillna(0.0)
)
copyable_candidates['final_score'] = (
    0.60 * copyable_candidates['predictability_score']
    + 0.40 * copyable_candidates['copyable_score']
)

wallet_cohorts['copyable_group'] = (
    copyable_candidates
    .sort_values('final_score', ascending=False)
    .reset_index(drop=True)
)

predicting_pool = eligible_base[
    ~eligible_base['wallet'].isin(wallet_cohorts['copyable_group']['wallet'])
].copy()
wallet_cohorts['predicting_group'] = (
    predicting_pool
    # predicting_pool[predicting_pool['predicting_final_score'] >= PREDICTING_SCORE_MIN]
    .sort_values('predicting_final_score', ascending=False)
    .reset_index(drop=True)
)

overlap = set(wallet_cohorts['copyable_group']['wallet']) & set(wallet_cohorts['predicting_group']['wallet'])
if overlap:
    raise ValueError(f'Wallet groups must be disjoint; found overlap of {len(overlap)} wallets.')

wallet_cohorts['copyable_group']['wallet_quality'] = wallet_cohorts['copyable_group']['final_score']
wallet_cohorts['predicting_group']['wallet_quality'] = wallet_cohorts['predicting_group']['predicting_final_score']

wallet_cohorts['multi_filter'] = wallet_cohorts['copyable_group'].copy()

print(f"Base-eligible wallets: {len(eligible_base):,}")
print(f"Copyable candidates: {len(copyable_candidates):,}")
print(f"Selected wallets (copyable group): {len(wallet_cohorts['copyable_group']):,}")
print(f"Selected wallets (predicting group): {len(wallet_cohorts['predicting_group']):,}")
wallet_cohorts['copyable_group'].head(10)

Base-eligible wallets: 99
Copyable candidates: 24
Selected wallets (copyable group): 24
Selected wallets (predicting group): 75

,wallet,num_buckets,trade_count,total_notional,total_pnl,copyable_pnl,num_markets,median_dt,median_roi,average_roi,max_drawdown,max_copyable_drawdown,buy_pnl,buy_quantity,sell_pnl,sell_quantity,buy_notional,sell_notional,buy_copyable_quantity,buy_copyable_pnl,sell_copyable_quantity,sell_copyable_pnl,buy_roi,sell_roi,buy_copyable_notional,top5_pnl_pct,top10_pnl_pct,worst5_pnl_pct,positive_bucket_share,top_market_pnl_pct,top_market_abs_pnl_pct,market_pnl_hhi,pnl_volatility,max_drawdown_to_pnl,max_copyable_drawdown_to_copyable_pnl,return,copyable_pnl_factor,copyable_roi,sample_mult,downside_tail,predictability_score,predicting_final_score,copyable_efficiency,copyable_dd_ratio,copyable_score,final_score,wallet_quality
0,0x3e438fdb437d90925b47b6f8ab85405ba8ffa83f,54,61,5728.71,934.03,559.08,31,2025-06-24 06:15:00+00:00,0.18,0.67,100.00,73.91,991.23,7719.90,-57.20,1285.93,5325.09,403.62,4266.94,625.04,551.64,-65.96,0.13,-0.04,2943.28,0.60,0.87,-0.30,0.70,0.16,0.11,0.06,1.05,0.11,0.13,0.16,0.60,0.40,0.53,0.30,-0.64,-0.64,0.10,0.13,3.72,1.11,1.11
1,0x04c30228da9e4346a2dd4e958499dfb81aef9a7c,707,727,6889.06,1151.24,875.68,218,2026-03-01 07:50:00+00:00,0.06,0.20,118.02,118.02,1560.97,8132.08,-409.73,6360.12,5547.16,1341.90,5046.86,1206.48,3459.24,-330.80,0.19,-0.06,3442.63,0.48,0.70,-0.20,0.61,0.18,0.14,0.07,1.26,0.10,0.13,0.17,0.76,0.15,0.86,0.20,-1.30,-1.30,0.13,0.13,4.19,0.89,0.89
2,0x6d16c33b540069f5aa0d9f705b0d759dec927228,212,288,20724.28,9176.28,3238.68,30,2026-04-25 08:22:30+00:00,0.23,0.91,935.10,646.92,10220.06,48194.70,-1043.78,28947.06,19580.49,1143.78,13998.42,3678.37,4932.02,-439.68,0.21,-0.04,5687.26,0.37,0.61,-0.14,0.59,0.19,0.15,0.09,2.07,0.10,0.20,0.44,0.35,0.32,0.71,0.14,-1.64,-1.64,0.16,0.20,4.67,0.88,0.88
3,0x30f67d821c57a54e25e5e521dbd3b5b18309004f,632,1628,6993.86,2328.85,643.22,169,2026-04-25 08:15:00+00:00,0.19,0.43,294.09,140.21,2586.62,12374.20,-257.77,3046.50,5434.43,1559.42,3479.36,775.96,1314.29,-132.74,0.21,-0.08,1528.04,0.38,0.62,-0.25,0.62,0.16,0.09,0.02,1.03,0.13,0.22,0.33,0.28,0.12,0.85,0.25,-1.06,-1.06,0.09,0.22,2.62,0.41,0.41
4,0xc3196c92f4b18cb13efbc16871d722a93ed90e0c,96,168,12403.57,4687.06,2670.65,29,2026-04-21 20:10:00+00:00,-1.00,0.31,638.88,523.18,5087.32,20897.70,-400.26,14810.84,5302.57,7101.00,10177.32,2170.71,7150.11,499.94,0.24,-0.03,2582.39,0.86,1.34,-0.39,0.45,0.19,0.15,0.07,5.27,0.14,0.20,0.38,0.57,0.17,0.60,0.39,-3.52,-3.52,0.22,0.20,6.15,0.35,0.35
5,0xe97b7b1396a99341b32984fa8bbf62f2f68ab2ea,173,193,33251.24,4358.33,1006.24,36,2025-02-02 14:45:00+00:00,0.08,1.82,631.30,391.04,3150.95,41489.75,1207.38,13447.45,28017.02,5234.21,4954.63,865.37,4142.32,140.87,0.08,0.09,3345.74,0.56,0.85,-0.30,0.75,0.20,0.16,0.09,1.70,0.14,0.39,0.13,0.23,0.42,0.68,0.30,-1.29,-1.29,0.03,0.39,1.40,-0.21,-0.21
6,0x37a46125cfa561a8b52c4a6ddd093a65bb4ca487,548,877,31776.79,3223.60,919.42,150,2025-04-04 21:30:00+00:00,0.06,0.23,401.45,84.92,3312.52,47853.53,-88.93,5888.45,29069.67,2707.12,3695.31,763.69,1323.24,155.73,0.07,-0.02,2244.80,0.45,0.71,-0.28,0.48,0.12,0.06,0.02,1.09,0.12,0.09,0.10,0.29,0.07,0.83,0.28,-1.21,-1.21,0.03,0.09,1.08,-0.29,-0.29
7,0xb9c1ea9b9ae211e384e7128255e8387edb380791,544,626,17786.38,3781.20,710.31,200,2026-02-08 06:00:00+00:00,0.27,0.34,335.67,201.37,2743.02,27396.34,1038.18,8170.65,14524.68,3261.70,2667.97,64.76,1872.31,645.55,0.10,0.13,1414.47,0.39,0.54,-0.14,0.69,0.17,0.09,0.02,1.57,0.09,0.28,0.21,0.19,0.06,0.83,0.14,-1.32,-1.32,0.04,0.28,1.07,-0.36,-0.36
8,0x2853240a0f4e9e11a949a5cfa6e0fe953a293482,3113,3553,165100.25,20971.10,3251.23,847,2025-10-20 14:25:00+00:00,0.02,0.43,738.98,413.05,18393.26,220123.79,2577.85,72857.68,120188.93,44911.32,22461.25,3214.30,14543.68,36.92,0.08,0.04,12263.98,0.28,0.43,-0.05,0.60,0.10,0.05,0.01,1.13,0.04,0.13,0.13,0.16,0.07,1.00,0.05,-1.13,-1.13,0.02,0.13,0.67,-0.41,-0.41
9,0x78a19803306d350cd1120bb07fcfe91a665be6bd,151,289,21235.20,8177.69,4990.60,70,2026-04-14 15:20:00+00:00,-1.00,0.19,1510.48,1095.33,10548.74,54890.90,-2371.06,23730.40,10201.38,11033.82,28201.40,6235.40,6620.23,-1244.80,0.19,-0.10,5241.18,0.88,1.24,-0.43,0.43,0.20,0.11,0.04,7.21,0.18,0.22,0.39,0.61,0.12,0.66,0.43,-5.18,-5.18,0.24,0.22,6.59,-0.47,-0.47

In [692]:
df_ana = df_full[df_full["is_train"] == False].copy()

In [693]:
# Copyable group total and open PnL

opening_res = df_ana[
    df_ana['wallet'].isin(wallet_cohorts['copyable_group']['wallet'])
    & (df_ana['position'] == df_ana['quantity'])
][['trade_pnl', 'copyable_pnl', 'notional', 'copyable_notional']].sum()

total_res = df_ana[
    df_ana['wallet'].isin(wallet_cohorts['copyable_group']['wallet'])
][['trade_pnl', 'copyable_pnl', 'notional', 'copyable_notional']].sum()

print('*** Copyable group Open PnL ***')
print(f'wallet_pnl={opening_res["trade_pnl"]} roi={opening_res["trade_pnl"] / opening_res["notional"]}')
print(f'copyable_pnl={opening_res["copyable_pnl"]} roi={opening_res["copyable_pnl"] / opening_res["copyable_notional"]}')
print('\n')

print('*** Copyable group Total PnL ***')
print(f'total_wallet_pnl={total_res["trade_pnl"]} roi={total_res["trade_pnl"] / total_res["notional"]}')
print(f'total_copyable_pnl={total_res["copyable_pnl"]} roi={total_res["copyable_pnl"] / total_res["copyable_notional"]}')

*** Copyable group Open PnL ***
wallet_pnl=110236.62112130916 roi=0.7738379314990778
copyable_pnl=3718.572186497662 roi=0.17483372570475444


*** Copyable group Total PnL ***
total_wallet_pnl=260258.189046 roi=0.2267126698128708
total_copyable_pnl=59308.44880901707 roi=0.1687977132590261

In [694]:
df_ana[df_ana['wallet'].isin(wallet_cohorts['copyable_group']['wallet'])].groupby('condition_id').agg(
    num_wallets=('wallet', 'nunique'),
    total_pnl=('pnl', 'sum'),
    total_copyable_pnl=('copyable_pnl', 'sum'),
    total_notional=('notional', 'sum'),
    trades=('wallet', 'count')
).sort_values('total_copyable_pnl', ascending=False, key=abs).head(20)

,num_wallets,total_pnl,total_copyable_pnl,total_notional,trades
condition_id,,,,,
0xd86a816093fcd0a0e1ca440bc5ce199bd3c5a8d6139e044b076958164f8c5423,5,187328.69,60882.46,219515.38,278
0xab1209b73e1ce9ebb4905dad781496385b5102c048889502b174ed733de1506a,4,17643.23,6825.53,10668.65,91
0xcacd424332319971356c757c025b45a4eb5643b919fb3bd2f84051afea599b13,3,68092.91,6497.22,180499.71,516
0xee78796c2501ccee253b7b3fc9ebda254acb4c82c424db2dd24fc6b16885417d,1,-5234.60,-5393.34,45912.21,38
0xd39905267d79b715f078279ef41f311b791c6e2c7361fea38011492b632212ef,3,4947.57,4998.42,1322.38,11
0x6a8cfe84d17693425f27831db5949d7511f3393d4624b182ac6956164cd32b10,2,-20718.05,-4431.41,26772.04,118
0x68fbeb8d823552abf9d35f3ebdb8619a1a1d51b650da9101be62f09308fd18d2,2,-16934.41,-4142.87,16934.41,111
0x3088733a3d7f03d026035f6dd7df44a82c59eeb95545dda3889b65baa9a36e82,4,-284.80,-2883.63,20372.53,55
0x16608c4fdd7cb41292f6d42c1c02b43ac22593f1c198a104847a3479848d7abe,4,24738.56,2689.38,16938.12,89
0x1b5e5ebc0cf5c7c55d557f2be51276efbddb59ff5c038692be4501f17fa53944,2,-6956.16,-2002.47,6956.16,83
0x2bef40a1f62d045527228e699990d1bd1f97906b2458a6f3e4a0daf11124060c,4,-16029.56,-1573.80,22742.14,73
0x3094a2b925483a06aa72945a1472e311e5eb6be75284f61e0c008e279508ddf6,3,22793.08,1553.13,32689.35,63
0x9769f78cbc95a5ed11895e6064bac471d8fd8f930b260cf581b68d3f58630d27,5,-1221.43,1470.16,28237.37,99
0xd8664606498aba2a8ccab56656860cb3f02d74de80e974ab87a9f940e65d4d5e,1,-110.61,-1280.91,5826.58,79
0x876047c0df88886ddbe468fe811bc75a667da45a552d798e626ecfc5c60d52d9,2,-17958.86,-1182.33,28790.42,44
0x35481add6852622436ba70d466479e5d4ea676c9ba8c3961917e39fd1047061d,1,-549.98,-943.06,2671.48,9
0x46dd571d8c32bd58dcc553ae6c2a1ae8dda6d1ec69943bc0f771ea5c35132ca5,3,3127.98,863.87,8371.79,41
0x366f89649caea042c96ee741b185461ec7faa408a2664ec44469a0061924b537,2,-1881.21,-757.23,1915.00,14
0xe352d7b022b4913faece8da53efd363a430a25d9913d6db8bef968a2e1f6be15,1,-237.32,-647.74,1262.32,5
0x605c1bb246391281ad86d2c00586f00dc507488f402950eb3b1edf064e749822,2,-642.00,-642.00,642.00,8

In [695]:
if(WALLET_FILTER is not None):
    wallet_cohorts['copyable_group'] = wallet_cohorts['copyable_group'].query("wallet in @WALLET_FILTER").copy().reset_index(drop=True)

In [696]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [697]:
filter_wallets = set(wallet_cohorts['multi_filter']["wallet"])
df_test =  df_full[
    (df_full['wallet'].isin(filter_wallets))
    ].groupby(['question', 'condition_id', 'outcome']).agg(
    # ].groupby(['wallet']).agg(
        pnl_sum=('pnl', 'sum'),
        trade_count=('pnl', 'size'),
        wallet_count=('wallet', 'nunique'),
    ).reset_index().sort_values('pnl_sum', key=abs, ascending=False)

big_conditions = df_test.groupby('condition_id').agg(
    abs_pnl_sum=('pnl_sum', lambda x: abs(x).sum()),
    min_abs_pnl_pct=('pnl_sum', lambda x: abs(x).min() / abs(x).sum() if abs(x).sum() > 0 else 0)
).reset_index().sort_values('abs_pnl_sum', ascending=False)



print(df_test['pnl_sum'].sum())
df_test = df_test[df_test['condition_id'].isin(big_conditions['condition_id'])].sort_values('question', ascending=False).merge(big_conditions, on='condition_id', how='left')

print(df_test[df_test['min_abs_pnl_pct']<0.1]['pnl_sum'].sum()) 

df_test[df_test['min_abs_pnl_pct'] < 0.1].sort_values(['abs_pnl_sum'], ascending=False).head(2)

901551.8494250001
620663.618399

,question,condition_id,outcome,pnl_sum,trade_count,wallet_count,abs_pnl_sum,min_abs_pnl_pct
4885,"US x Iran permanent peace deal by June 15, 2026?",0xd86a816093fcd0a0e1ca440bc5ce199bd3c5a8d6139e044b076958164f8c5423,Yes,187334.22,245,3,187339.75,0.00
4886,"US x Iran permanent peace deal by June 15, 2026?",0xd86a816093fcd0a0e1ca440bc5ce199bd3c5a8d6139e044b076958164f8c5423,No,-5.53,33,4,187339.75,0.00

In [698]:
wallet_cohorts['multi_filter'].sort_values("copyable_pnl", key=abs, ascending=False).head(10)

,wallet,num_buckets,trade_count,total_notional,total_pnl,copyable_pnl,num_markets,median_dt,median_roi,average_roi,max_drawdown,max_copyable_drawdown,buy_pnl,buy_quantity,sell_pnl,sell_quantity,buy_notional,sell_notional,buy_copyable_quantity,buy_copyable_pnl,sell_copyable_quantity,sell_copyable_pnl,buy_roi,sell_roi,buy_copyable_notional,top5_pnl_pct,top10_pnl_pct,worst5_pnl_pct,positive_bucket_share,top_market_pnl_pct,top_market_abs_pnl_pct,market_pnl_hhi,pnl_volatility,max_drawdown_to_pnl,max_copyable_drawdown_to_copyable_pnl,return,copyable_pnl_factor,copyable_roi,sample_mult,downside_tail,predictability_score,predicting_final_score,copyable_efficiency,copyable_dd_ratio,copyable_score,final_score,wallet_quality
20,0x134a63b764ac7b008356e8db1857db94e6b09e42,4964,6932,2550383.06,187057.69,50838.56,1806,2025-09-02 16:42:30+00:00,0.01,0.78,23384.92,9904.89,174627.37,3267856.06,12430.32,612860.05,2417932.39,132450.67,410300.85,58209.76,65321.40,-7371.19,0.05,0.02,303587.34,0.41,0.63,-0.17,0.77,0.23,0.11,0.03,5.34,0.13,0.19,0.07,0.27,0.21,1.00,0.17,-5.36,-5.36,0.02,0.19,0.99,-2.82,-2.82
23,0x3b4484b6c8cbfdaa383ba337ab3f0d71055e264e,839,1508,1047497.20,127374.77,34006.14,226,2026-01-03 16:25:00+00:00,0.03,0.72,15036.49,7440.13,96809.23,1281722.84,30565.53,589863.80,771938.65,275558.55,249449.27,29974.44,242135.31,4031.70,0.08,0.05,150234.92,0.51,0.78,-0.34,0.59,0.12,0.09,0.04,12.64,0.12,0.22,0.12,0.27,0.19,0.89,0.34,-11.46,-11.46,0.03,0.22,1.26,-6.37,-6.37
13,0x88b59d79b6e1659c95a0043028e5bb7a26e6205c,231,493,323337.96,46951.91,18953.80,29,2025-06-24 10:30:00+00:00,0.17,0.23,2775.43,1673.08,55146.37,379672.12,-8194.46,72965.58,314800.10,8537.86,90779.36,21732.18,9097.38,-2778.38,0.15,-0.11,75268.50,0.49,0.72,-0.18,0.82,0.24,0.21,0.11,4.78,0.06,0.09,0.15,0.40,0.09,0.72,0.18,-3.43,-3.43,0.06,0.09,1.94,-1.28,-1.28
21,0x3c0c8df8eb256e41f5586e5b89b27181497cfbb7,160,319,142401.38,54109.55,10870.20,18,2026-04-20 16:55:00+00:00,0.47,0.50,9727.55,7140.92,34782.74,219294.17,19326.81,108542.04,82345.50,60055.88,40423.16,2857.41,35948.00,8012.79,0.16,0.18,15178.99,0.61,0.85,-0.25,0.66,0.24,0.23,0.15,9.96,0.18,0.66,0.38,0.20,0.10,0.67,0.25,-6.94,-6.94,0.08,0.66,1.69,-3.49,-3.49
15,0x744a283ddda3533d6abf89240bfe2f43201a923b,104,187,58099.35,21728.78,7937.46,23,2026-02-27 15:20:00+00:00,-1.00,0.60,2219.16,2879.45,33325.11,83580.24,-11596.33,69359.71,45733.93,12365.42,32095.30,14174.74,26203.42,-6237.28,0.40,-0.17,17562.10,0.78,1.20,-0.37,0.52,0.22,0.21,0.13,7.49,0.10,0.36,0.37,0.37,0.22,0.61,0.37,-4.91,-4.91,0.14,0.36,3.85,-1.41,-1.41
16,0xf989bd9c62b1eae2c388515fcc766527a8b147cc,78,91,101969.01,49868.54,5321.01,31,2025-03-03 22:20:00+00:00,0.45,0.62,1386.68,0.27,51334.38,152100.85,-1465.84,10240.96,100444.14,1524.87,12604.57,5314.21,21.10,6.80,0.34,-0.14,8323.79,0.38,0.60,-0.03,0.84,0.20,0.20,0.10,6.05,0.03,0.00,0.49,0.11,0.07,0.57,0.03,-3.39,-3.39,0.05,0.00,1.45,-1.45,-1.45
9,0x78a19803306d350cd1120bb07fcfe91a665be6bd,151,289,21235.20,8177.69,4990.60,70,2026-04-14 15:20:00+00:00,-1.00,0.19,1510.48,1095.33,10548.74,54890.90,-2371.06,23730.40,10201.38,11033.82,28201.40,6235.40,6620.23,-1244.80,0.19,-0.10,5241.18,0.88,1.24,-0.43,0.43,0.20,0.11,0.04,7.21,0.18,0.22,0.39,0.61,0.12,0.66,0.43,-5.18,-5.18,0.24,0.22,6.59,-0.47,-0.47
10,0xdaa6a2cd4ba545befb3dbdc25d2b444c46873e62,2168,3395,122865.46,10125.86,3832.98,235,2026-01-23 18:07:30+00:00,0.00,0.25,1662.26,977.19,14040.91,143428.30,-3915.05,129472.55,66730.17,56135.29,55124.92,5140.34,55740.46,-1307.36,0.10,-0.03,25646.93,0.33,0.56,-0.26,0.52,0.07,0.04,0.01,1.92,0.16,0.25,0.08,0.38,0.09,1.00,0.26,-2.27,-2.27,0.03,0.25,1.18,-0.89,-0.89
22,0x8aaaac8e8523492db360b722af35177f4d4d51df,353,751,129113.19,31249.64,3767.51,41,2026-02-28 06:10:00+00:00,0.08,1.67,6075.00,4528.06,57267.13,255460.76,-26017.49,157692.83,34875.03,94238.16,70297.16,16473.83,80518.27,-12706.32,0.22,-0.16,9596.84,0.70,1.06,-0.57,0.52,0.18,0.15,0.09,11.44,0.19,1.20,0.24,0.12,0.20,0.77,0.57,-9.35,-9.35,0.03,1.20,0.20,-5.53,-5.53
8,0x2853240a0f4e9e11a949a5cfa6e0fe953a293482,3113,3553,165100.25,20971.10,3251.23,847,2025-10-20 14:25:00+00:00,0.02,0.43,738.98,413.05,18393.26,220123.79,2577.85,72857.68,120188.93,44911.32,22461.25,3214.30,14543.68,36.92,0.08,0.04,12263.98,0.28,0.43,-0.05,0.60,0.10,0.05,0.01,1.13,0.04,0.13,0.13,0.16,0.07,1.00,0.05,-1.13,-1.13,0.02,0.13,0.67,-0.41,-0.41

In [699]:
wallets = set(wallet_cohorts['copyable_group']['wallet'])

df = df_full #[~df_full["is_train"]].copy()
print(len(df))

df_wallets = df[
    (df['wallet'].isin(wallets))
    & ~df['is_train']
    ].copy()
print(len(df_wallets))

df = df_wallets.groupby('condition_id').agg(
    pnl=('pnl', 'sum'),
    notional=('notional', 'sum'),
    sell_count=('side', lambda x: (x == 'SELL').sum()),
    buy_count=('side', lambda x: (x == 'BUY').sum()),
    wallets=('wallet', lambda x: x.nunique()),
).sort_values(by="pnl", key=np.abs, ascending=False).merge(mdf, on="condition_id", how="left")

13282697
4185

In [700]:
df_wallets[df_wallets['side'] == 'BUY'].groupby('condition_id').agg(
    primary_tag=('primary_tag', 'first'),
    pnl=('pnl', 'sum'),
    copyable_pnl=('copyable_pnl', 'sum'),
    notional=('notional', 'sum'),
    sell_count=('side', lambda x: (x == 'SELL').sum()),
    buy_count=('side', lambda x: (x == 'BUY').sum()),
    wallets=('wallet', lambda x: x.nunique())
).reset_index(drop=False).groupby('primary_tag').agg(
    pnl=('pnl', 'sum'),
    copyable_pnl=('copyable_pnl', 'sum'),
    count=('condition_id', 'size')).sort_values(by="copyable_pnl", key=np.abs, ascending=False).head(20)

                  pnl  copyable_pnl  count
primary_tag
Politics    266490.12      88058.99    451

In [701]:
wallet_set = set(wallet_cohorts['copyable_group']['wallet'])
print(f"Copyable wallets: {len(wallet_set)} with fills {df_wallets[df_wallets['wallet'].isin(wallet_set)].shape[0]} with total PnL: {df_wallets[df_wallets['wallet'].isin(wallet_set)]['pnl'].sum():,.2f}")
df_wallets[df_wallets['wallet'].isin(wallet_set)]['trade_pnl'].sum()

Copyable wallets: 24 with fills 4185 with total PnL: 260,258.19

np.float64(260258.189046)

In [702]:
df_wallets[df_wallets['wallet'].isin(wallet_set)].groupby('wallet').agg(
    pnl=('trade_pnl', 'sum'),
    notional=('notional', 'sum'),
    trades=('wallet', 'count'),
    copyable_pnl=('copyable_pnl', 'sum'),
    copyable_qty=('copyable_qty', 'sum'),
    ).sort_values(by="pnl", key=np.abs, ascending=False).head(20)

,pnl,notional,trades,copyable_pnl,copyable_qty
wallet,,,,,
0x134a63b764ac7b008356e8db1857db94e6b09e42,260740.16,760514.42,1547,75824.95,509665.67
0x3c0c8df8eb256e41f5586e5b89b27181497cfbb7,-18869.31,91073.04,194,-5373.55,29881.34
0x3b4484b6c8cbfdaa383ba337ab3f0d71055e264e,13126.57,97006.27,193,601.97,32372.60
0x78a19803306d350cd1120bb07fcfe91a665be6bd,3870.71,2580.90,43,3274.86,20791.03
0x8aaaac8e8523492db360b722af35177f4d4d51df,2277.04,55677.23,172,-12454.71,70816.02
0xb9c1ea9b9ae211e384e7128255e8387edb380791,905.94,2119.93,30,95.07,992.60
0x6d16c33b540069f5aa0d9f705b0d759dec927228,-888.37,50999.07,207,1011.67,9620.00
0x88b59d79b6e1659c95a0043028e5bb7a26e6205c,791.90,2729.38,16,121.72,446.58
0x7b05f8e36980dffe4d784edf664970e623956180,782.00,10817.97,32,575.00,2175.24
0x04c30228da9e4346a2dd4e958499dfb81aef9a7c,-754.41,9378.42,127,-227.59,5606.58
0xdaa6a2cd4ba545befb3dbdc25d2b444c46873e62,-686.91,47300.83,747,-2663.39,50051.70
0xf658449199d0bcf544de0ff928a3b66685f3dcfe,-671.55,3690.71,45,-512.43,4301.92
0x744a283ddda3533d6abf89240bfe2f43201a923b,-382.81,2302.79,7,-444.63,2820.19
0x30f67d821c57a54e25e5e521dbd3b5b18309004f,198.83,7525.58,788,130.66,4056.91
0xc3196c92f4b18cb13efbc16871d722a93ed90e0c,-165.39,4198.38,35,-654.77,10631.17
0x566d32ba7a326f1a1bb0b7d3555215f14421d58f,-16.22,50.00,2,3.63,41.71

In [703]:
MARKET = '0xaabf22a03217285585592f3082f27e2b0f4c1cee2bb4003e84817100bbcf1938'

market_def = mdf.loc[mdf['condition_id'] == MARKET].head(1).squeeze()
print(f"Market: {market_def}")

dfc = df_full[(df_full['condition_id'] == MARKET)
              & (df_full['wallet'].isin(wallets))].copy()
# dfc['bucket'] = dfc['dt'].dt.floor('1h')


dfc = dfc.groupby(['dt', 'wallet', 'side', 'outcome']).agg( 
        pnl=('pnl', 'sum'),
        notional=('notional', 'sum'),
        quantity=('quantity', 'sum'),
        position=('position', 'last'),
        avg_price=('price', lambda x: (x * dfc.loc[x.index, 'quantity']).sum() / dfc.loc[x.index, 'quantity'].sum()),
        copyable_qty=('copyable_qty', 'sum'),
        copyable_pnl=('copyable_pnl', 'sum'),
)[['pnl', 'position', 'notional', 'quantity', 'avg_price', 'copyable_qty', 'copyable_pnl']].reset_index().sort_values(['dt', 'wallet', 'side', 'outcome'])

Market: Empty DataFrame
Columns: [condition_id, end_date_iso, question, tags, primary_tag, winner_token_id, outcome]
Index: []

In [704]:
# dominant tags
wallet_fills = df_full[df_full['wallet'].isin(wallet_cohorts['multi_filter']['wallet'])]

dominant_tags = (
    wallet_fills
    .groupby(['wallet', 'primary_tag'], as_index=False)[['quantity', 'pnl']].sum()
    .sort_values(['wallet', 'quantity'], ascending=[True, False])
    .assign(total_qty=lambda df: df.groupby('wallet')['quantity'].transform('sum'))
    .drop_duplicates('wallet')
    .assign(primary_tag_ratio=lambda df: df['quantity'] / df['total_qty'])
    .rename(columns={
        'quantity': 'primary_tag_qty'
    })[['wallet', 'primary_tag', 'primary_tag_qty', 'primary_tag_ratio', 'pnl']]
)

In [705]:
print(len(dominant_tags))
dominant_tags.sort_values('pnl', ascending=False).head(20)

24

,wallet,primary_tag,primary_tag_qty,primary_tag_ratio,pnl
1,0x134a63b764ac7b008356e8db1857db94e6b09e42,Politics,5870483.02,1.00,447797.85
5,0x3b4484b6c8cbfdaa383ba337ab3f0d71055e264e,Politics,2077181.41,1.00,140501.34
23,0xf989bd9c62b1eae2c388515fcc766527a8b147cc,Politics,162341.81,1.00,49868.54
15,0x88b59d79b6e1659c95a0043028e5bb7a26e6205c,Politics,456158.98,1.00,47743.81
6,0x3c0c8df8eb256e41f5586e5b89b27181497cfbb7,Politics,565865.02,1.00,35240.24
16,0x8aaaac8e8523492db360b722af35177f4d4d51df,Politics,556033.21,1.00,33526.69
11,0x744a283ddda3533d6abf89240bfe2f43201a923b,Politics,156779.92,1.00,21345.98
2,0x2853240a0f4e9e11a949a5cfa6e0fe953a293482,Politics,292981.48,1.00,20971.10
9,0x566d32ba7a326f1a1bb0b7d3555215f14421d58f,Politics,69347.27,1.00,16283.45
13,0x78a19803306d350cd1120bb07fcfe91a665be6bd,Politics,102646.55,1.00,12048.40
12,0x7656ed7f597a0a61cd307591db198a42b2a7194b,Politics,132048.41,1.00,9893.17
20,0xdaa6a2cd4ba545befb3dbdc25d2b444c46873e62,Politics,370010.45,1.00,9438.95
22,0xf658449199d0bcf544de0ff928a3b66685f3dcfe,Politics,99804.00,1.00,9189.41
8,0x444e1b2ccf56b63e6b54e1357df184843f3401d0,Politics,56926.80,1.00,8333.11
10,0x6d16c33b540069f5aa0d9f705b0d759dec927228,Politics,199987.00,1.00,8287.91
14,0x7b05f8e36980dffe4d784edf664970e623956180,Politics,111249.45,1.00,7371.43
18,0xb9c1ea9b9ae211e384e7128255e8387edb380791,Politics,41257.16,1.00,4687.13
19,0xc3196c92f4b18cb13efbc16871d722a93ed90e0c,Politics,49174.48,1.00,4521.67
21,0xe97b7b1396a99341b32984fa8bbf62f2f68ab2ea,Politics,54937.20,1.00,4358.33
4,0x37a46125cfa561a8b52c4a6ddd093a65bb4ca487,Politics,53741.98,1.00,3223.60

In [706]:
watched_wallets = wallet_cohorts['multi_filter'].sort_values("copyable_pnl", key=abs, ascending=False)['wallet'].head(10).to_list()
for w in watched_wallets:
    wallet_df = wallet_vol_train[wallet_vol_train['wallet'] == w]
    wallet_cohorts[w] = wallet_df.copy().reset_index(drop=True)

In [707]:
import plotly.graph_objects as go

print(f"copyable_group wallets: {len(wallet_cohorts['copyable_group']):,}")
print(f"predicting_group wallets: {len(wallet_cohorts['predicting_group']):,}")

pd.set_option('display.max_rows', 100)

copyable_view = wallet_cohorts['copyable_group'].sort_values('final_score', ascending=False).head(20)
predicting_view = wallet_cohorts['predicting_group'].sort_values('predicting_final_score', ascending=False).head(20)

plot_rows = []
for group_label, cohort_name in [('copyable', 'copyable_group'), ('predicting', 'predicting_group')]:
    wallets = set(wallet_cohorts[cohort_name]['wallet'])
    group_trades = df_full[
        (df_full['wallet'].isin(wallets))
        & (~df_full['is_train'])
    ][['dt', 'pnl', 'copyable_pnl']].copy()

    daily = (
        group_trades
        .assign(plot_dt=group_trades['dt'].dt.floor('D'))
        .groupby('plot_dt', as_index=False)[['pnl', 'copyable_pnl']]
        .sum()
        .sort_values('plot_dt')
        .reset_index(drop=True)
    )
    daily['cum_trade_pnl'] = daily['pnl'].cumsum()
    daily['cum_copyable_pnl'] = daily['copyable_pnl'].cumsum()
    daily['wallet_group'] = group_label
    plot_rows.append(daily)

group_perf = pd.concat(plot_rows, ignore_index=True)

fig = go.Figure()
colors = {'copyable': '#1f77b4', 'predicting': '#ff7f0e'}
for group_label in ['copyable', 'predicting']:
    g = group_perf[group_perf['wallet_group'] == group_label]
    fig.add_trace(
        go.Scatter(
            x=g['plot_dt'],
            y=g['cum_trade_pnl'],
            mode='lines',
            name=f'{group_label} trade pnl',
            line=dict(color=colors[group_label], width=2),
        )
    )
    fig.add_trace(
        go.Scatter(
            x=g['plot_dt'],
            y=g['cum_copyable_pnl'],
            mode='lines',
            name=f'{group_label} copyable pnl',
            line=dict(color=colors[group_label], width=2, dash='dash'),
        )
    )

fig.update_layout(
    title='Stage1 wallet-group performance on test period',
    xaxis_title='Date',
    yaxis_title='Cumulative PnL (USDC)',
    template='plotly_white',
)
fig.show(renderer='browser')

copyable_group wallets: 24
predicting_group wallets: 75

In [708]:
copyable_wallets = wallet_cohorts['copyable_group'].copy().assign(wallet_group='copyable')
predicting_wallets = wallet_cohorts['predicting_group'].copy().assign(wallet_group='predicting')

selected_wallets = (
    pd.concat([copyable_wallets, predicting_wallets], ignore_index=True)
    .drop_duplicates(subset=['wallet', 'wallet_group'])
    .reset_index(drop=True)
)

selected_wallets.to_parquet(WORKSPACE_DIR / 'selected_wallets_v2.parquet', index=False)
print(f"Saved selected wallets: {len(selected_wallets):,}")
print(selected_wallets['wallet_group'].value_counts().to_dict())

Saved selected wallets: 99
{'predicting': 75, 'copyable': 24}

## Build and save strategy registry

All cohorts × all trigger variants → persisted `WalletSelectionStrategy` files.
The backtest loads these directly.

In [709]:
from polymarket_analysis.strategy.definition import TriggerSpec, WalletSelectionStrategy
from polymarket_analysis.strategy.registry import save_strategy

SIGNAL_THRESHOLD = 0.65

selected_wallets = wallet_cohorts['copyable_group'].copy().reset_index(drop=True)
predicting_wallets = selected_wallets.copy()
if 'wallet_quality' not in predicting_wallets.columns:
    if 'predicting_final_score' in predicting_wallets.columns:
        predicting_wallets['wallet_quality'] = predicting_wallets['predicting_final_score']
    else:
        predicting_wallets['wallet_quality'] = 0.0

strategy_specs = [
    (
        'predicting_group__score_threshold',
        f'predicting_group | score >= {SIGNAL_THRESHOLD:.2f} (Kelly)',
        TriggerSpec(
            fn_ref='polymarket_analysis.strategy.triggers.score_threshold',
            params={'threshold': SIGNAL_THRESHOLD, 'dynamic_sizing': True},
            mode='frame',
        ),
    ),
    (
        'predicting_group__all_open_buys',
        'predicting_group | all open-buys (fixed stake)',
        TriggerSpec(
            fn_ref='polymarket_analysis.strategy.triggers.all_open_buys',
            params={'dynamic_sizing': False},
            mode='frame',
        ),
    ),
    (
        'predicting_group__copy_triggers',
        'predicting_group | copy all triggers (tight slippage)',
        TriggerSpec(
            fn_ref='polymarket_analysis.strategy.triggers.copy_triggers',
            params={'dynamic_sizing': False},
            mode='frame',
        ),
    ),
]

all_strategies = []
for strategy_id, name, trigger in strategy_specs:
    all_strategies.append(
        WalletSelectionStrategy(
            strategy_id=strategy_id,
            name=name,
            selection_method='predicting_group',
            trigger=trigger,
            wallets=predicting_wallets.copy(),
            params={
                'selection_metric': 'predicting_final_score',
                'top_n': len(predicting_wallets),
                'signal_threshold': SIGNAL_THRESHOLD if trigger.fn_ref.endswith('score_threshold') else None,
            },
            metadata={
                'cohort': 'predicting_group',
                'wallet_group': 'predicting',
                'selection_metric': 'predicting_final_score',
                'signal_threshold': SIGNAL_THRESHOLD,
                'top_n': len(predicting_wallets),
                'end_date_train': None,
                'train_a_end_date': None,
                'selection_notes': (
                    'threshold-based: copyable group uses copyability quality gates, '
                    'predicting group uses predictability threshold on remaining wallets'
                ),
            },
        )
    )

for strategy in all_strategies:
    parquet_path, json_path = save_strategy(strategy, WORKSPACE_DIR)
    print(f"Saved [{strategy.strategy_id}] wallets={len(strategy.wallets):3d} trigger={strategy.trigger.fn_ref.split('.')[-1]}")

print(f'\nTotal strategies saved: {len(all_strategies)}')

Saved [predicting_group__score_threshold] wallets= 24 trigger=score_threshold
Saved [predicting_group__all_open_buys] wallets= 24 trigger=all_open_buys
Saved [predicting_group__copy_triggers] wallets= 24 trigger=copy_triggers

Total strategies saved: 3

## Strategy registry summary

In [710]:
from polymarket_analysis.strategy.registry import load_all_strategies

registry = load_all_strategies(WORKSPACE_DIR)
summary_rows = []
for sid, s in registry.items():
    summary_rows.append({
        'strategy_id': s.strategy_id,
        'name': s.name,
        'selection_method': s.selection_method,
        'num_wallets': len(s.wallets),
        'trigger_fn': s.trigger.fn_ref.split('.')[-1],
        'threshold': s.trigger.params.get('threshold'),
        'dynamic_sizing': s.trigger.params.get('dynamic_sizing'),
    })

pd.DataFrame(summary_rows).sort_values('strategy_id').reset_index(drop=True).head(1)

,strategy_id,name,selection_method,num_wallets,trigger_fn,threshold,dynamic_sizing
0,0x0c058138ee8749433656cb5c696e0fd3dc7dfabf__all_open_buys,0x0c058138ee8749433656cb5c696e0fd3dc7dfabf | all open-buys (fixed stake),0x0c058138ee8749433656cb5c696e0fd3dc7dfabf,1,all_open_buys,NaN,False

## Wallet PnL over time

Three independent plots:
- **Training plot** — cohort aggregate cumulative PnL over the training period only
- **Test plot** — cohort aggregate cumulative PnL over the test period only (starts from 0)
- **Individual plot** — per-wallet cumulative PnL spanning train + test, with a train/test split
  vline and wallet address labels; test portion resets to 0 at the split boundary

Set `PLOT_WALLET_PNL = False` to skip (e.g. when running headlessly).

In [711]:
PLOT_WALLET_PNL  = True
TOP_N_INDIVIDUAL = 10   # wallets shown in panel 1 per cohort

In [712]:
df_fills = df_full.copy()
df_fills['copyable_pnl_exposure'] = np.where( 
    df_fills['copyable_qty'] > 0,
    df_fills['price'] * df_fills['copyable_qty'],
    np.nan
)

# Normalise grouped schema → canonical fill-level names
if "total_quantity" in df_fills.columns and "quantity" not in df_fills.columns:
    df_fills = df_fills.rename(columns={
        "total_quantity": "quantity",
        "avg_price": "price",
        "trade_value_usdc": "usdc_amount",
    })

df_fills["usdc_amount"]      = df_fills["usdc_amount"].astype(float)
df_fills["final_value_usdc"] = df_fills["final_value_usdc"].astype(float)
df_fills["quantity"]         = df_fills["quantity"].astype(float)

In [713]:
filter_fills = df_fills[
    (df_fills['wallet'].isin(wallet_cohorts['multi_filter']['wallet']))
    & (df_fills['side'] == 'BUY')
    & (TAGS is None or df_fills['primary_tag'].isin(TAGS))
    & (df_fills["is_train"] == False)
    ].copy().reset_index(drop=True)

print(len(filter_fills))
filter_fills = filter_fills[filter_fills['copyable_qty'] >= 1].copy().reset_index(drop=True)
print(len(filter_fills))
filter_fills.head(2)

3090
1299

,wallet,condition_id,token_id,dt,side,position,quantity,price,usdc_amount,final_value_usdc,trade_pnl,copyable_pnl,token_winner,final_price,last_condition_trade_ts,tx_hash,num_fills,is_train,copyable_qty,avail_copy_qty,avail_copy_total_vol,avail_copy_count,copyable_qty_098,copyable_qty_095,copyable_qty_090,avail_copy_qty_098,avail_copy_qty_095,avail_copy_qty_090,end_date_iso,question,tags,primary_tag,winner_token_id,outcome,pnl,notional,copyable_pnl_098,copyable_pnl_095,copyable_pnl_090,copyable_notional,roi,copyable_roi,bucket,copyable_pnl_exposure
0,0x04c30228da9e4346a2dd4e958499dfb81aef9a7c,0x09508d57e81543629e170ccd145e0da1d1c1fa68817914336c0dff4e1993d230,1724675288893466978169502340055027608595307725916510941563170988088714561616,2026-06-16 09:53:43+00:00,BUY,49.18,49.18,0.61,30.00,49.18,19.18,0.94,True,1.00,2026-07-31 21:24:47+00:00,0x76e0fbc2d3ee24d53bb8c08a07295d47da9b1a8a110c888e32ef560227d22bdb,2,False,2.40,2.40,1.87,4.00,0.00,0.00,0.00,0.00,0.00,0.00,2026-08-01T00:00:00Z,Will Sheikh Tamim bin Hamad Al Thani sign a U.S. x Iran deal by July 31?,"[Politics, Iran, Trump, Peace Deal, deprecgeopolitcs, U.S. x Iran]",Politics,1724675288893466978169502340055027608595307725916510941563170988088714561616,No,19.18,30.00,0.00,0.00,0.00,1.46,0.64,0.64,2026-06-16 09:55:00+00:00,1.46
1,0x134a63b764ac7b008356e8db1857db94e6b09e42,0x0e2e5c0146c730a2e4ef8031c9128b4efef451a9f4832f42b46997926f9e1303,24606039444792628072348728486218619466386821084675596998252795028502077675336,2026-06-03 05:26:30+00:00,BUY,516.80,516.80,0.31,158.78,516.80,358.02,21.37,True,1.00,2026-06-09 00:24:34+00:00,0xbac40267ce348858289cf36ae0d400bcfcb666434ccec89e5711250653ea2347,3,False,30.85,30.85,26.84,3.00,30.85,30.85,0.00,30.85,30.85,0.00,2026-06-02T00:00:00Z,Will Karen Bass & Spencer Pratt advance to the second round of the 2026 Los Angeles mayoral elec...,"[Politics, Elections, US Election, Los Angeles, Rewards 300 4.5 50 Deprec, Los Angeles Mayoral E...",Politics,24606039444792628072348728486218619466386821084675596998252795028502077675336,No,358.02,158.78,21.56,21.85,0.00,9.48,2.25,2.25,2026-06-03 05:25:00+00:00,9.48

In [714]:
pd.set_option('display.max_colwidth', 100)
pd.set_option('display.max_rows', 1000)

In [715]:
filter_fills["bucket"] = filter_fills["dt"].dt.floor('5min')

MAX_EXPOSURE = 1000

df = filter_fills.groupby(['bucket', 'condition_id', 'wallet', 'side']).agg(
    copyable_pnl_exposure=('copyable_pnl_exposure', 'sum'),
    total_copyable_qty=('copyable_qty', 'sum'),
    trade_pnl =('trade_pnl', 'sum'),
    copyable_pnl = ('copyable_pnl', 'sum'),
    trades=('condition_id', 'count'),
    copyable_qty=('copyable_qty', 'sum'),
    wallets=('wallet', lambda x: x.nunique()),
).reset_index()

df = filter_fills


scale = np.minimum(1, MAX_EXPOSURE / df["copyable_pnl_exposure"].replace(0, np.nan))

df = df.assign(
    scaled_copyable_pnl_exposure = df["copyable_pnl_exposure"] * scale,
    scaled_copyable_pnl = df["copyable_pnl"] * scale,
    scaled_copyable_qty = df["copyable_qty"] * scale,
)

df.head(1)

,wallet,condition_id,token_id,dt,side,position,quantity,price,usdc_amount,final_value_usdc,trade_pnl,copyable_pnl,token_winner,final_price,last_condition_trade_ts,tx_hash,num_fills,is_train,copyable_qty,avail_copy_qty,avail_copy_total_vol,avail_copy_count,copyable_qty_098,copyable_qty_095,copyable_qty_090,avail_copy_qty_098,avail_copy_qty_095,avail_copy_qty_090,end_date_iso,question,tags,primary_tag,winner_token_id,outcome,pnl,notional,copyable_pnl_098,copyable_pnl_095,copyable_pnl_090,copyable_notional,roi,copyable_roi,bucket,copyable_pnl_exposure,scaled_copyable_pnl_exposure,scaled_copyable_pnl,scaled_copyable_qty
0,0x04c30228da9e4346a2dd4e958499dfb81aef9a7c,0x09508d57e81543629e170ccd145e0da1d1c1fa68817914336c0dff4e1993d230,1724675288893466978169502340055027608595307725916510941563170988088714561616,2026-06-16 09:53:43+00:00,BUY,49.18,49.18,0.61,30.00,49.18,19.18,0.94,True,1.00,2026-07-31 21:24:47+00:00,0x76e0fbc2d3ee24d53bb8c08a07295d47da9b1a8a110c888e32ef560227d22bdb,2,False,2.40,2.40,1.87,4.00,0.00,0.00,0.00,0.00,0.00,0.00,2026-08-01T00:00:00Z,Will Sheikh Tamim bin Hamad Al Thani sign a U.S. x Iran deal by July 31?,"[Politics, Iran, Trump, Peace Deal, deprecgeopolitcs, U.S. x Iran]",Politics,1724675288893466978169502340055027608595307725916510941563170988088714561616,No,19.18,30.00,0.00,0.00,0.00,1.46,0.64,0.64,2026-06-16 09:50:00+00:00,1.46,1.46,0.94,2.40

In [716]:
df_plot = df.groupby('end_date_iso').agg(
    scaled_copyable_pnl=('scaled_copyable_pnl', 'sum'),
    ending_exposure=('scaled_copyable_pnl_exposure', 'sum'),
).reset_index()

df.sort_values('bucket', inplace=True)
df['scaled_copyable_pnl_cumsum'] = df['scaled_copyable_pnl'].cumsum()

df_pnl = df[['bucket', 'scaled_copyable_pnl_cumsum']].copy()

# exposure ends at EOD of end_date, so shift by 24h
df_exposure = df_plot[['end_date_iso', 'ending_exposure']].copy()
df_exposure['end_date_iso'] = pd.to_datetime(df_exposure['end_date_iso']) + pd.Timedelta(days=1)
df_exposure.rename(columns={'end_date_iso': 'dt', 'ending_exposure': 'exposure_delta'}, inplace=True)

resolution_exposure = df_exposure.groupby('dt').agg(exposure_delta=('exposure_delta', 'sum')).reset_index()
resolution_exposure['exposure_delta'] = resolution_exposure['exposure_delta'] * -1

buy_exposure = df[['bucket', 'scaled_copyable_pnl_exposure']].rename(columns={'bucket': 'dt', 'scaled_copyable_pnl_exposure': 'exposure_delta'})

df_exposure = ( pd.concat([resolution_exposure, buy_exposure], ignore_index=True)
    .reset_index(drop=True)
)

df_exposure.sort_values('dt', inplace=True)
df_exposure['exposure'] = df_exposure['exposure_delta'].cumsum()

# df_plot['end_date_iso'] = pd.to_datetime(df_plot['end_date_iso']) + pd.Timedelta(days=1)

import plotly.graph_objects as go

fig = go.Figure()

fig.add_trace(go.Scatter(
    x=df_exposure['dt'],
    y=df_exposure['exposure'],
    mode='lines',
    name='exposure'
))

fig.add_trace(go.Scatter(
    x=df_pnl['bucket'],
    y=df_pnl['scaled_copyable_pnl_cumsum'],
    mode='lines',
    name='scaled_copyable_pnl_cumsum'
))

fig.show()

In [717]:
import plotly.express as px

# Aggregate by bucket
bucket_pnl = df.groupby('bucket')['scaled_copyable_pnl'].sum().reset_index()
bucket_pnl['scaled_copyable_pnl'] = bucket_pnl['scaled_copyable_pnl'].cumsum()

# Plot with Plotly
fig = px.line(
    bucket_pnl,
    x='bucket',
    y='scaled_copyable_pnl',
    title='Total Scaled Copyable PnL by Time Bucket',
    labels={'bucket': 'Time Bucket', 'scaled_copyable_pnl': 'Scaled Copyable PnL'}
)
fig.show()

In [718]:
bucket_pnl.head(10)

                     bucket  scaled_copyable_pnl
0 2026-04-29 23:50:00+00:00                -7.12
1 2026-04-30 12:35:00+00:00                 8.88
2 2026-05-02 07:50:00+00:00               233.86
3 2026-05-03 18:15:00+00:00               240.86
4 2026-05-03 20:35:00+00:00                31.19
5 2026-05-04 03:40:00+00:00               -36.38
6 2026-05-04 05:10:00+00:00               -31.38
7 2026-05-06 00:35:00+00:00               -30.30
8 2026-05-06 00:45:00+00:00               -28.58
9 2026-05-07 21:40:00+00:00               -74.03

In [719]:
import plotly.express as px

# Aggregate by bucket
# bucket_pnl = df.groupby('bucket')['copyable_pnl_098'].sum().reset_index()
# bucket_pnl['copyable_pnl_098'] = bucket_pnl['copyable_pnl_098'].cumsum()

bucket_pnl = df.groupby('bucket').agg(
    scaled_copyable_pnl=('scaled_copyable_pnl', 'sum'),
    copyable_pnl=('copyable_pnl', 'sum'),
    copyable_pnl_098=('copyable_pnl_098', 'sum'),
    copyable_pnl_095=('copyable_pnl_095', 'sum'),
    copyable_pnl_090=('copyable_pnl_090', 'sum')
)

bucket_pnl.reset_index(inplace=True)


# cumsum of copyable pnl columns
bucket_pnl['scaled_copyable_pnl'] = bucket_pnl['scaled_copyable_pnl'].cumsum()
bucket_pnl['copyable_pnl'] = bucket_pnl['copyable_pnl'].cumsum()
bucket_pnl['copyable_pnl_098'] = bucket_pnl['copyable_pnl_098'].cumsum()
bucket_pnl['copyable_pnl_095'] = bucket_pnl['copyable_pnl_095'].cumsum()
bucket_pnl['copyable_pnl_090'] = bucket_pnl['copyable_pnl_090'].cumsum()


# Plot with Plotly

# TODO: different colors and legend...

fig = px.line(
    bucket_pnl,
    x='bucket',
    y='copyable_pnl_098',
    title='Total Copyable PnL by Time Bucket',
    labels={'bucket': 'Time Bucket', 'copyable_pnl_098': 'Copyable PnL 98%'}
)

fig.add_trace(px.line(
    bucket_pnl,
    x='bucket',
    y='copyable_pnl_095',
    labels={'bucket': 'Time Bucket', 'copyable_pnl_095': 'Copyable PnL 95%'},
    color_discrete_sequence=['orange']
).data[0])

fig.add_trace(px.line(
    bucket_pnl,
    x='bucket',
    y='copyable_pnl_090',
    labels={'bucket': 'Time Bucket', 'copyable_pnl_090': 'Copyable PnL 90%'},
    color_discrete_sequence=['green']
).data[0])


fig.add_trace(px.line(
    bucket_pnl,
    x='bucket',
    y='scaled_copyable_pnl',
    labels={'bucket': 'Time Bucket', 'scaled_copyable_pnl': 'Scaled Copyable PnL'},
    color_discrete_sequence=['red']
).data[0])


fig.show()

In [720]:
df_fills[(
    (df_fills['is_train'] == False)
    & (df_fills['wallet'].isin(wallet_set))
    & (df_fills['side'] == 'BUY')
          )].groupby(['primary_tag', 'side']).agg(
    copyable_pnl=('copyable_pnl', 'sum'),
    total_copyable_qty=('copyable_qty', 'sum'),
    trade_pnl=('trade_pnl', 'sum'),
    trades=('condition_id', 'count'),
    condition_count=('condition_id', 'nunique'),
    wallets=('wallet', lambda x: x.nunique()),
).sort_values('copyable_pnl', key=abs, ascending=False).reset_index().head(10)

,primary_tag,side,copyable_pnl,total_copyable_qty,trade_pnl,trades,condition_count,wallets
0,Politics,BUY,88058.99,568104.80,266490.12,3090,451,16

In [721]:
from polymarket_analysis.visualization.wallet_plots import (
    plot_wallet_selection_pnl,
    plot_wallet_individual_pnl,
)

if PLOT_WALLET_PNL:
    # Cohort aggregate PnL — training period
    fig_train = plot_wallet_selection_pnl(
        df_fills,
        wallet_cohorts,
        period="train",
        title="Wallet selection cohorts — cohort cumulative PnL (training period)",
    )
    fig_train.show(renderer="browser")

    # Cohort aggregate PnL — test period (starts from 0)
    fig_test = plot_wallet_selection_pnl(
        df_fills,
        wallet_cohorts,
        period="test",
        title="Wallet selection cohorts — cohort cumulative PnL (test period)",
    )
    fig_test.show(renderer="browser")

    # # Individual wallet lines (train + test) with split vline and labels
    # fig_ind = plot_wallet_individual_pnl(
    #     df_fills,
    #     wallet_cohorts,
    #     split_date=split_dt,
    #     top_n_individual=TOP_N_INDIVIDUAL,
    #     title="Individual wallet cumulative PnL (train + test, resets at split)",
    # )
    # fig_ind.show(renderer="browser")

else:
    print("PLOT_WALLET_PNL=False — skipping plots")

In [722]:
wals = pd.read_parquet('/Users/vobornij/projects/polymarket/data/trade_signals_workspace_v2/selected_wallets_v2.parquet')

In [723]:
wals[wals['wallet_group'] == 'copyable'].sort_values('wallet_quality', ascending=False).head(20)

,wallet,num_buckets,trade_count,total_notional,total_pnl,copyable_pnl,num_markets,median_dt,median_roi,average_roi,max_drawdown,max_copyable_drawdown,buy_pnl,buy_quantity,sell_pnl,sell_quantity,buy_notional,sell_notional,buy_copyable_quantity,buy_copyable_pnl,sell_copyable_quantity,sell_copyable_pnl,buy_roi,sell_roi,buy_copyable_notional,top5_pnl_pct,top10_pnl_pct,worst5_pnl_pct,positive_bucket_share,top_market_pnl_pct,top_market_abs_pnl_pct,market_pnl_hhi,pnl_volatility,max_drawdown_to_pnl,max_copyable_drawdown_to_copyable_pnl,return,copyable_pnl_factor,copyable_roi,sample_mult,downside_tail,predictability_score,predicting_final_score,copyable_efficiency,copyable_dd_ratio,copyable_score,final_score,wallet_quality,wallet_group
0,0x3e438fdb437d90925b47b6f8ab85405ba8ffa83f,54,61,5728.71,934.03,559.08,31,2025-06-24 06:15:00+00:00,0.18,0.67,100.00,73.91,991.23,7719.90,-57.20,1285.93,5325.09,403.62,4266.94,625.04,551.64,-65.96,0.13,-0.04,2943.28,0.60,0.87,-0.30,0.70,0.16,0.11,0.06,1.05,0.11,0.13,0.16,0.60,0.40,0.53,0.30,-0.64,-0.64,0.10,0.13,3.72,1.11,1.11,copyable
1,0x04c30228da9e4346a2dd4e958499dfb81aef9a7c,707,727,6889.06,1151.24,875.68,218,2026-03-01 07:50:00+00:00,0.06,0.20,118.02,118.02,1560.97,8132.08,-409.73,6360.12,5547.16,1341.90,5046.86,1206.48,3459.24,-330.80,0.19,-0.06,3442.63,0.48,0.70,-0.20,0.61,0.18,0.14,0.07,1.26,0.10,0.13,0.17,0.76,0.15,0.86,0.20,-1.30,-1.30,0.13,0.13,4.19,0.89,0.89,copyable
2,0x6d16c33b540069f5aa0d9f705b0d759dec927228,212,288,20724.28,9176.28,3238.68,30,2026-04-25 08:22:30+00:00,0.23,0.91,935.10,646.92,10220.06,48194.70,-1043.78,28947.06,19580.49,1143.78,13998.42,3678.37,4932.02,-439.68,0.21,-0.04,5687.26,0.37,0.61,-0.14,0.59,0.19,0.15,0.09,2.07,0.10,0.20,0.44,0.35,0.32,0.71,0.14,-1.64,-1.64,0.16,0.20,4.67,0.88,0.88,copyable
3,0x30f67d821c57a54e25e5e521dbd3b5b18309004f,632,1628,6993.86,2328.85,643.22,169,2026-04-25 08:15:00+00:00,0.19,0.43,294.09,140.21,2586.62,12374.20,-257.77,3046.50,5434.43,1559.42,3479.36,775.96,1314.29,-132.74,0.21,-0.08,1528.04,0.38,0.62,-0.25,0.62,0.16,0.09,0.02,1.03,0.13,0.22,0.33,0.28,0.12,0.85,0.25,-1.06,-1.06,0.09,0.22,2.62,0.41,0.41,copyable
4,0xc3196c92f4b18cb13efbc16871d722a93ed90e0c,96,168,12403.57,4687.06,2670.65,29,2026-04-21 20:10:00+00:00,-1.00,0.31,638.88,523.18,5087.32,20897.70,-400.26,14810.84,5302.57,7101.00,10177.32,2170.71,7150.11,499.94,0.24,-0.03,2582.39,0.86,1.34,-0.39,0.45,0.19,0.15,0.07,5.27,0.14,0.20,0.38,0.57,0.17,0.60,0.39,-3.52,-3.52,0.22,0.20,6.15,0.35,0.35,copyable
5,0xe97b7b1396a99341b32984fa8bbf62f2f68ab2ea,173,193,33251.24,4358.33,1006.24,36,2025-02-02 14:45:00+00:00,0.08,1.82,631.30,391.04,3150.95,41489.75,1207.38,13447.45,28017.02,5234.21,4954.63,865.37,4142.32,140.87,0.08,0.09,3345.74,0.56,0.85,-0.30,0.75,0.20,0.16,0.09,1.70,0.14,0.39,0.13,0.23,0.42,0.68,0.30,-1.29,-1.29,0.03,0.39,1.40,-0.21,-0.21,copyable
6,0x37a46125cfa561a8b52c4a6ddd093a65bb4ca487,548,877,31776.79,3223.60,919.42,150,2025-04-04 21:30:00+00:00,0.06,0.23,401.45,84.92,3312.52,47853.53,-88.93,5888.45,29069.67,2707.12,3695.31,763.69,1323.24,155.73,0.07,-0.02,2244.80,0.45,0.71,-0.28,0.48,0.12,0.06,0.02,1.09,0.12,0.09,0.10,0.29,0.07,0.83,0.28,-1.21,-1.21,0.03,0.09,1.08,-0.29,-0.29,copyable
7,0xb9c1ea9b9ae211e384e7128255e8387edb380791,544,626,17786.38,3781.20,710.31,200,2026-02-08 06:00:00+00:00,0.27,0.34,335.67,201.37,2743.02,27396.34,1038.18,8170.65,14524.68,3261.70,2667.97,64.76,1872.31,645.55,0.10,0.13,1414.47,0.39,0.54,-0.14,0.69,0.17,0.09,0.02,1.57,0.09,0.28,0.21,0.19,0.06,0.83,0.14,-1.32,-1.32,0.04,0.28,1.07,-0.36,-0.36,copyable
8,0x2853240a0f4e9e11a949a5cfa6e0fe953a293482,3113,3553,165100.25,20971.10,3251.23,847,2025-10-20 14:25:00+00:00,0.02,0.43,738.98,413.05,18393.26,220123.79,2577.85,72857.68,120188.93,44911.32,22461.25,3214.30,14543.68,36.92,0.08,0.04,12263.98,0.28,0.43,-0.05,0.60,0.10,0.05,0.01,1.13,0.04,0.13,0.13,0.16,0.07,1.00,0.05,-1.13,-1.13,0.02,0.13,0.67,-0.41,-0.41,copyable
9,0x78a19803306d350cd1120bb07fcfe91a665be6bd,151,289,21235.20,8177.69,4990.60,70,2026-04-14 15:20:00+00:00,-1.00,0.19,1510.48,1095.33,10548.74,54890.90,-2371.06,23730.40,10201.38,11033.82,28201.40,6235.40,6620.23,-1244.80,0.19,-0.10,5241.18,0.88,1.24,-0.43,0.43,0.20,0.11,0.04,7.21,0.18,0.22,0.39,0.61,0.12,0.66,0.43,-5.18,-5.18,0.24,0.22,6.59,-0.47,-0.47,copyable
10,0xdaa6a2cd4ba545befb3dbdc25d2b444c46873e62,2168,3395,122865.46,10125.86,3832.98,235,2026-01-23 18:07:30+00:00,0.00,0.25,1662.26,977.19,14040.91,143428.30,-3915.05,129472.55,66730.17,56135.29,55124.92,5140.34,55740.46,-1307.36,0.10,-0.03,25646.93,0.33,0.56,-0.26,0.52,0.07,0.04,0.01,1.92,0.16,0.25,0.08,0.38,0.09,1.00,0.26,-2.27,-2.27,0.03,0.25,1.18,-0.89,-0.89,copyable
11,0x444e1b2ccf56b63e6b54e1357df184843f3401d0,169,182,32331.62,8333.11,577.82,71,2025-02-08 22:50:00+00:00,0.18,1.61,1290.63,25.36,9314.47,47480.61,-981.36,9446.19,26704.09,5627.54,2333.50,577.83,1.00,-0.00,0.20,-0.10,1312.41,0.44,0.71,-0.22,0.66,0.14,0.10,0.04,2.90,0.15,0.04,0.26,0.07,0.11,0.68,0.22,-2.11,-2.11,0.02,0.04,0.65,-1.01,-1.01,copyable
12,0x957f691adbd03039025f06d285a5c3e5384499c8,1419,1532,18871.21,3061.20,97.32,856,2025-11-02 21:10:00+00:00,-1.00,3.68,146.34,196.45,3302.70,61595.68,-241.50,19072.16,14498.92,4372.29,10795.77,140.40,4141.11,-43.08,0.05,-0.01,2541.20,0.32,0.47,-0.14,0.38,0.15,0.08,0.01,0.79,0.05,2.02,0.16,0.03,0.12,0.95,0.14,-1.07,-1.07,0.01,2.02,-1.28,-1.16,-1.16,copyable
13,0x88b59d79b6e1659c95a0043028e5bb7a26e6205c,231,493,323337.96,46951.91,18953.80,29,2025-06-24 10:30:00+00:00,0.17,0.23,2775.43,1673.08,55146.37,379672.12,-8194.46,72965.58,314800.10,8537.86,90779.36,21732.18,9097.38,-2778.38,0.15,-0.11,75268.50,0.49,0.72,-0.18,0.82,0.24,0.21,0.11,4.78,0.06,0.09,0.15,0.40,0.09,0.72,0.18,-3.43,-3.43,0.06,0.09,1.94,-1.28,-1.28,copyable
14,0x566d32ba7a326f1a1bb0b7d3555215f14421d58f,183,187,39294.66,16299.67,2037.69,102,2025-09-15 21:10:00+00:00,0.11,0.46,1025.00,1008.17,16132.85,63406.27,166.82,5868.75,36125.08,3169.59,12648.74,2120.63,2178.02,-82.94,0.25,0.03,7206.49,0.43,0.67,-0.14,0.70,0.21,0.15,0.07,4.30,0.06,0.49,0.41,0.13,0.06,0.69,0.14,-2.99,-2.99,0.05,0.49,1.08,-1.36,-1.36,copyable
15,0x744a283ddda3533d6abf89240bfe2f43201a923b,104,187,58099.35,21728.78,7937.46,23,2026-02-27 15:20:00+00:00,-1.00,0.60,2219.16,2879.45,33325.11,83580.24,-11596.33,69359.71,45733.93,12365.42,32095.30,14174.74,26203.42,-6237.28,0.40,-0.17,17562.10,0.78,1.20,-0.37,0.52,0.22,0.21,0.13,7.49,0.10,0.36,0.37,0.37,0.22,0.61,0.37,-4.91,-4.91,0.14,0.36,3.85,-1.41,-1.41,copyable
16,0xf989bd9c62b1eae2c388515fcc766527a8b147cc,78,91,101969.01,49868.54,5321.01,31,2025-03-03 22:20:00+00:00,0.45,0.62,1386.68,0.27,51334.38,152100.85,-1465.84,10240.96,100444.14,1524.87,12604.57,5314.21,21.10,6.80,0.34,-0.14,8323.79,0.38,0.60,-0.03,0.84,0.20,0.20,0.10,6.05,0.03,0.00,0.49,0.11,0.07,0.57,0.03,-3.39,-3.39,0.05,0.00,1.45,-1.45,-1.45,copyable
17,0xf658449199d0bcf544de0ff928a3b66685f3dcfe,470,632,39592.77,9860.96,1167.48,200,2026-03-11 21:07:30+00:00,0.27,0.43,1422.37,1097.99,12466.37,74918.06,-2605.41,14911.79,34932.06,4660.70,16583.42,2826.56,5438.65,-1659.08,0.17,-0.17,7732.35,0.34,0.53,-0.23,0.65,0.11,0.06,0.02,3.18,0.14,0.94,0.25,0.12,0.05,0.81,0.23,-2.70,-2.70,0.03,0.94,0.19,-1.54,-1.54,copyable
18,0x7656ed7f597a0a61cd307591db198a42b2a7194b,913,1155,81177.10,9893.17,2771.11,236,2025-11-30 09:00:00+00:00,0.03,0.30,1584.15,613.78,11920.64,99027.57,-2027.47,33020.84,60770.81,20406.29,24950.16,3783.52,13040.76,-1012.41,0.12,-0.06,15311.30,0.51,0.79,-0.24,0.58,0.16,0.11,0.03,3.41,0.16,0.22,0.12,0.28,0.08,0.90,0.24,-3.34,-3.34,0.03,0.22,1.11,-1.56,-1.56,copyable
19,0x7b05f8e36980dffe4d784edf664970e623956180,107,142,58540.69,6589.43,975.83,24,2026-01-21 16:05:00+00:00,0.23,1.03,655.00,430.00,5631.61,72705.99,957.82,15343.53,51861.11,6679.58,7628.62,1323.78,3523.90,-347.95,0.08,0.06,5441.49,0.72,1.09,-0.32,0.69,0.23,0.18,0.11,6.90,0.10,0.44,0.11,0.15,0.15,0.62,0.32,-4.42,-4.42,0.02,0.44,0.43,-2.48,-2.48,copyable