# TODO:

Politics / Mentions: two promising wallets
0x9e8ecc4cb3c4e48f544cba2fbbb252a6a65e8db8	
0x0cb10c40b0776e9ee8cef970af85724654dda76c

# Wallet Strategy Selection

This stage tracks two distinct wallet groups on the full trade stream (BUY + SELL):

- `copyable_group`: wallets that pass base eligibility and strong copyability thresholds.
- `predicting_group`: the remaining eligible wallets (not in copyable) that pass a predictability score threshold.

Notes:
- Group membership is threshold-based (absolute scores), not target-count based.
- Open-buy skill metrics are kept for diagnostics/legacy comparison.
- `selected_wallets_v2.parquet` stores both groups with a `wallet_group` label.
- Stage2 backtest uses only `predicting_group`.

In [253]:
%load_ext autoreload
%autoreload 2

import datetime
from pathlib import Path
import json

import numpy as np
import pandas as pd
import pyarrow.dataset as ds

np.set_printoptions(precision=4, suppress=True)
pd.options.display.float_format = '{:.2f}'.format

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

## Configuration

In [254]:
# ── configuration ─────────────────────────────────────────────────────────────
RECENCY_DAYS     = 90
MAX_LEAD_DAYS = 2  # keep only trades within this many days of contract resolution (2 weeks)

PRICE_BUCKET_BINS   = [0.0, 0.1, 0.25, 0.4, 0.6, 0.75, 0.9, 1.0]
PRICE_BUCKET_LABELS = [
    "0.00-0.10", "0.10-0.25", "0.25-0.40", "0.40-0.60",
    "0.60-0.75", "0.75-0.90", "0.90-1.00",
]

TRADES_DIR    = Path("../../data/polygon_trades_processed")
WORKSPACE_DIR = Path("../../data/trade_signals_workspace_v2")
WORKSPACE_DIR.mkdir(parents=True, exist_ok=True)

dataset = ds.dataset(TRADES_DIR, format="parquet")
TAGS = set(['Weather'])
# TAGS = set(['Politics'])
# TAGS = set(['Awards'])
# TAGS = set(['MrBeast', 'Trump', 'Elections', 'Celebrities', 'Elon Musk', 'YouTube'])

WALLET_FILTER = None
# WALLET_FILTER = [
#     '0x919698b19427cbe6945b0dc823f2d9e126a4d934',
#     '0x85d22a973e817f87afe0a7fd346a39823cce7479',
#     '0x6011655c4afb76f36dd1b08a137a1ba73466b31e',
#     '0x5f612351a9e46afbe3f164473a7d77a69ec9840a',
# ]
DATASET_COLUMNS        = set(dataset.schema.names)
TRIGGER_TX_HASH_COLUMN = (
    "transaction_hash" if "transaction_hash" in DATASET_COLUMNS
    else ("tx_hash" if "tx_hash" in DATASET_COLUMNS else None)
)

## Derive train/test dates from data

## Full-stream wallet metrics for copy-trigger selection

Build per-wallet metrics on the full training trade stream (BUY + SELL).
Copyability is considered here (stage1), not in stage0 filtering.

In [255]:
from polymarket_analysis.wallet_selection.volatility import (
    compute_wallet_metrics,
    filter_wallets_by_volatility,
)

from polymarket_analysis.data.data_catalogue import load_markets_processed
mdf = load_markets_processed()

print(mdf.groupby('primary_tag').size().sort_values(ascending=False).head(20))

mdf = mdf[
    # (TAGS is None or mdf['primary_tag'].isin(TAGS))
    ~(mdf['primary_tag'].isin(['Sports', 'Crypto']))
    & ((TAGS is None) or mdf["tags"].apply(lambda tags: any(tag in TAGS for tag in tags)))
    & (mdf['winner_token_id'].notna())
].copy().reset_index(drop=True)

print(f'selected markets for tags {TAGS}: {len(mdf)}')

primary_tag
Sports         1610735
Crypto          777081
Weather         113544
Politics         82482
Finance          40251
Awards           10525
Movies            9617
Music             6786
Culture           6245
AI                5478
All               3808
Esports           3671
Business          3242
MrBeast           1833
Science           1730
Iran              1304
Trump             1248
Celebrities       1144
Elections          889
Tech               744
dtype: int64
selected markets for tags {'Weather'}: 111045

In [256]:
# Load full processed trades for the full-stream path
trade_files = sorted(TRADES_DIR.glob("*.parquet"))
df_full = pd.concat(
    [pd.read_parquet(f).merge(mdf, on="condition_id", how="inner") for f in trade_files], ignore_index=True
    )

df_full = df_full[
    # (df_full['avg_price'] <= 1) 
    (df_full['side'] == 'BUY') 
    ].copy().reset_index(drop=True)

# df_full = df_full.merge(mdf, on="condition_id", how="inner")

if TAGS is not None:
    df_full = df_full[df_full['primary_tag'].isin(TAGS)].copy().reset_index(drop=True)

df_full['outcome'] = df_full['outcome_x']
del df_full['outcome_x'], df_full['outcome_y']

df_full["dt"] = pd.to_datetime(df_full["dt"], utc=True)

lead = (
    pd.to_datetime(df_full["last_condition_trade_ts"], utc=True, errors="coerce")
    - df_full["dt"]
)
df_full = df_full[lead <= pd.Timedelta(days=MAX_LEAD_DAYS)].copy()
print(
    f"Lead filter (<= {MAX_LEAD_DAYS}d before resolution): "
    f"{len(df_full):,} trades"
)

# Normalise grouped schema → canonical fill-level names
if "total_quantity" in df_full.columns and "quantity" not in df_full.columns:
    df_full = df_full.rename(columns={
        "total_quantity": "quantity",
        "avg_price": "price",
        "trade_value_usdc": "usdc_amount",
    })

df_full["usdc_amount"] = df_full["usdc_amount"].astype(float)
df_full["final_value_usdc"] = df_full["final_value_usdc"].astype(float)
df_full["quantity"] = df_full["quantity"].astype(float)

# Full-stream PnL / notional across BUY + SELL
df_full["pnl"] = np.where(
    df_full["side"] == "BUY",
    df_full["final_value_usdc"] - df_full["usdc_amount"],
    df_full["usdc_amount"] - df_full["final_value_usdc"],
)
df_full["notional"] = np.where(
    df_full["side"] == "BUY",
    df_full["usdc_amount"],
    df_full["quantity"] * (1 - df_full["price"].astype(float)),
)
TRAIN_END = pd.Timestamp("2026-08-01", tz="UTC")
df_full['is_train'] = df_full['last_condition_trade_ts'] <= TRAIN_END

# TRAIN_START = TRAIN_END - pd.Timedelta(days=30)
# df_full = df_full[df_full['dt'] >= TRAIN_START]

df_slice = df_full[df_full["is_train"]].copy()

wallet_vol_train, _ = compute_wallet_metrics(df_slice)
del df_slice
print(len(wallet_vol_train))

Lead filter (<= 2d before resolution): 13,629,316 trades
3625

In [257]:
df_full[~df_full["is_train"]]['last_condition_trade_ts'].min()

Timestamp('2026-08-01 00:03:03+0000', tz='UTC')

In [258]:
# mdf = load_markets_processed()
# df_full = pd.concat(
#     [
#         (
#             pd.read_parquet(f)
#             .merge(mdf, on="condition_id", how="inner")
#             .assign(dt=lambda df: pd.to_datetime(df["dt"], utc=True))
#             .loc[lambda df: df["dt"] >=  datetime.datetime(2026, 7, 1, tzinfo=datetime.timezone.utc)]
#         )
#         for f in trade_files
#     ],
#     ignore_index=True,
# )

In [259]:
print (df_full.columns)
print(df_full.index.names)

Index(['wallet', 'condition_id', 'token_id', 'dt', 'side', 'position',
       'quantity', 'price', 'usdc_amount', 'final_value_usdc', 'trade_pnl',
       'copyable_pnl', 'token_winner', 'final_price',
       'last_condition_trade_ts', 'tx_hash', 'num_fills', 'is_train',
       'copyable_qty_5m_100', 'avail_copy_qty_5m_100',
       'avail_copy_total_vol_5m_100', 'avail_copy_count_5m_100',
       'copyable_qty_5m_095', 'copyable_qty_20m_100', 'avail_copy_qty_5m_095',
       'avail_copy_qty_20m_100', 'end_date_iso', 'question', 'tags',
       'primary_tag', 'winner_token_id', 'outcome', 'pnl', 'notional'],
      dtype='object')
[None]

In [260]:
_copy_scale = np.minimum(2, df_full['avail_copy_qty_5m_100'] / df_full['quantity'])
df_full['copyable_qty_2x'] = df_full['copyable_qty_5m_100'] * _copy_scale
df_full['copyable_pnl_2x'] = df_full['copyable_pnl'] * _copy_scale

_copy_scale = np.minimum(0.5, df_full['avail_copy_qty_5m_100'] / df_full['quantity'])

df_full['copyable_qty_0.5x'] = df_full['copyable_qty_5m_100'] * _copy_scale
df_full['copyable_pnl_0.5x'] = df_full['copyable_pnl'] * _copy_scale

In [261]:
# ── Copyable PnL variants ─────────────────────────────────────────────────────
# Per-fill copyable PnL under different lookback-window / fill-price assumptions.
# Computed in stage1 for now (stage0 may later export these per-fill columns).
COPYABLE_PNL_BASE = "copyable_pnl"
COPYABLE_VARIANTS = {
    # "5m_095": dict(qty_col="copyable_qty_5m_095", fill_factor=0.95),
    "20m_100": dict(qty_col="copyable_qty_20m_100", fill_factor=1.0),
    "2x": dict(qty_col="copyable_qty_2x", fill_factor=1.0),
    # "0.5x": dict(qty_col="copyable_qty_0.5x", fill_factor=1.0),
}

for key, cfg in COPYABLE_VARIANTS.items():
    qty = df_full[cfg["qty_col"]]
    df_full[f"copyable_pnl_{key}"] = np.where(
        df_full["side"] == "BUY",
        (df_full["final_price"] - df_full["price"] * cfg["fill_factor"]) * qty,
        (df_full["price"] / cfg["fill_factor"] - df_full["final_price"]) * qty,
    )

COPYABLE_PNL_COLS = [COPYABLE_PNL_BASE] + [f"copyable_pnl_{k}" for k in COPYABLE_VARIANTS]
COPYABLE_PNL_VARIANTS = COPYABLE_PNL_COLS[1:]

In [262]:
df_full['copyable_notional'] = df_full['notional'] * (df_full['copyable_pnl'] / df_full['pnl'].replace(0, np.nan))
df_full['roi'] = df_full['pnl'] / df_full['notional'].replace(0, np.nan)
df_full['copyable_roi'] = df_full['copyable_pnl'] / df_full['copyable_notional'].replace(0, np.nan)

df_full.head()

,wallet,condition_id,token_id,dt,side,position,quantity,price,usdc_amount,final_value_usdc,trade_pnl,copyable_pnl,token_winner,final_price,last_condition_trade_ts,tx_hash,num_fills,is_train,copyable_qty_5m_100,avail_copy_qty_5m_100,avail_copy_total_vol_5m_100,avail_copy_count_5m_100,copyable_qty_5m_095,copyable_qty_20m_100,avail_copy_qty_5m_095,avail_copy_qty_20m_100,end_date_iso,question,tags,primary_tag,winner_token_id,outcome,pnl,notional,copyable_qty_2x,copyable_pnl_2x,copyable_qty_0.5x,copyable_pnl_0.5x,copyable_pnl_20m_100,copyable_notional,roi,copyable_roi
0,0x00328e0f5993e36ba99da9e072508b752c8ce886,0x044a838ceada7e84dfb3203c6c81dfb30396f989aff12b2660f0f239e572a14e,15137287428929432040454685842498924704511862428909496493595049815075368690282,2026-04-29 22:03:46+00:00,BUY,5.50,5.50,0.99,5.47,5.50,0.03,0.00,True,1.00,2026-04-30 06:57:52+00:00,0x52a1f7923fad37371ae8534dcce7e6c2b648850b549bf8108c0dcc64dc699bb6,1,True,-0.00,-0.00,0.00,0.00,-0.00,-0.00,-0.00,-0.00,2026-04-29T00:00:00Z,Will the highest temperature in Atlanta be between 84-85°F on April 29?,"[Weather, Recurring, Hide From New, Atlanta, Daily Temperature, Rewards Automation 50 4.5 50, Hi...",Weather,15137287428929432040454685842498924704511862428909496493595049815075368690282,No,0.03,5.47,0.00,0.00,0.00,-0.00,-0.00,0.00,0.01,NaN
1,0x00328e0f5993e36ba99da9e072508b752c8ce886,0x0cb060148061b907d88e02d51ebf0aee57874fa03d48159125990672084bc9a1,83739909512003997377637877154027164286599697900722157828991452076232122850514,2026-04-30 16:34:16+00:00,BUY,1.14,1.14,0.99,1.13,1.14,0.01,0.00,True,1.00,2026-04-30 21:46:44+00:00,0xf0faab27f3e796c5f2ad878bba57e77be3c4c881d5db5e6b64abb83f0939e127,1,True,0.00,0.00,-0.00,0.00,-0.00,0.00,-0.00,0.00,2026-04-30T00:00:00Z,Will the highest temperature in Munich be 16°C on April 30?,"[Weather, Recurring, Hide From New, Daily Temperature, Munich, Rewards Automation 50 4.5 50, Hig...",Weather,83739909512003997377637877154027164286599697900722157828991452076232122850514,No,0.01,1.13,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.01
2,0x00328e0f5993e36ba99da9e072508b752c8ce886,0x0a35a029855e86c1a031c65ed16fe726868baa4f6b68319fdcbd567f503f3353,87613043293933612046961849396391754018475439367577612263481396524616732077947,2026-04-30 18:52:34+00:00,BUY,151.21,151.21,0.99,150.00,151.21,1.21,0.80,True,1.00,2026-05-01 00:00:30+00:00,0x2fd969b663b25c1673a2ab235d3fb74362979e4c659d45a72473de110e0fabcd,1,True,100.00,100.00,0.90,1.00,0.00,100.00,0.00,100.00,2026-04-30T00:00:00Z,Will the highest temperature in Cape Town be 21°C on April 30?,"[Weather, Recurring, Hide From New, Daily Temperature, Rewards Automation 50 4.5 50, Cape Town, ...",Weather,87613043293933612046961849396391754018475439367577612263481396524616732077947,No,1.21,150.00,66.13,0.53,50.00,0.40,0.80,99.20,0.01,0.01
3,0x00328e0f5993e36ba99da9e072508b752c8ce886,0x0b0526229b5e027c53745dfe48e7b6648e10c615183dff7263c77c1f36ba9256,48379716558305764787817902932662678069352890459946635540447578208437870202600,2026-05-01 16:14:32+00:00,BUY,4.78,4.78,0.99,4.75,4.78,0.03,0.00,True,1.00,2026-05-02 01:06:58+00:00,0x56a7dfe747a2a105b0749482d87205b8e451d381917085aac6da48ca82e01166,1,True,0.00,0.00,-0.00,0.00,-0.00,-0.00,-0.00,-0.00,2026-05-01T00:00:00Z,Will the highest temperature in Istanbul be 11°C on May 1?,"[Weather, istanbul, Recurring, Hide From New, Daily Temperature, Rewards Automation 50 4.5 50 De...",Weather,48379716558305764787817902932662678069352890459946635540447578208437870202600,Yes,0.03,4.75,0.00,0.00,0.00,0.00,-0.00,0.00,0.01,0.01
4,0x00328e0f5993e36ba99da9e072508b752c8ce886,0x08c22421bc9da28fffe716bdca4e1c9432724cd90324a63031864a6c2396eef0,104386141273918598684344396669522220408210889552307252966552201002950871883518,2026-05-01 16:18:22+00:00,BUY,69.98,69.98,0.99,69.42,69.98,0.56,0.00,True,1.00,2026-05-02 00:12:06+00:00,0x7ade43e508e6b9701206f9eb12e7b613ed481f26040357e3900516045bec8901,1,True,0.00,0.00,0.00,0.00,-0.00,-0.00,-0.00,-0.00,2026-05-01T00:00:00Z,Will the highest temperature in Munich be 21°C on May 1?,"[Weather, Recurring, Hide From New, Daily Temperature, Munich, Rewards Automation 50 4.5 50 Depr...",Weather,104386141273918598684344396669522220408210889552307252966552201002950871883518,No,0.56,69.42,0.00,0.00,0.00,0.00,-0.00,0.00,0.01,0.01

In [263]:
wallet_vol_test, _ = compute_wallet_metrics(df_full[~df_full["is_train"]].copy())

In [264]:
df_test=wallet_vol_test.sort_values('copyable_pnl', key=abs, ascending=False)

In [265]:
df_full['bucket'] = df_full['dt'].dt.round("5min")

In [266]:
# # WALLET COMBINATION CELL

# df = df_full[
#     (df_full['wallet'].isin(wallet_cohorts['predicting_group']['wallet']) | df_full['wallet'].isin(wallet_cohorts['copyable_group']['wallet']) | df_full['wallet'].isin(WALLET_FILTER))
#      & (df_full["is_train"])].copy()

# df['is_predicting_group'] = df['wallet'].isin(wallet_cohorts['predicting_group']['wallet'])
# df['is_filter_group'] = df['wallet'].isin(WALLET_FILTER)
# df['is_copyable_group'] = df['wallet'].isin(wallet_cohorts['copyable_group']['wallet']) & ~df['is_filter_group']



# print(f'predicting_size: {len(wallet_cohorts["predicting_group"]["wallet"])}')
# print(f'copyable_size: {len(wallet_cohorts["copyable_group"]["wallet"])}')

# print('\n')
# print('*** Total PnL / Copyable PnL before filtering ***')
# print(df[['pnl', 'copyable_pnl']].sum())
# print(f'wallet_roi={df["pnl"].sum() / df["notional"].sum()}')
# print(f'copyable_roi={df["copyable_pnl"].sum() / df["copyable_notional"].sum()}')


# print('\n')
# print('*** Predicting group PnL ***')
# print(df[df['is_predicting_group']][['pnl', 'copyable_pnl']].sum())
# print(f'wallet_roi={df[df["is_predicting_group"]]["pnl"].sum() / df[df["is_predicting_group"]]["notional"].sum()}')
# print(f'copyable_roi={df[df["is_predicting_group"]]["copyable_pnl"].sum() / df[df["is_predicting_group"]]["copyable_notional"].sum()}')

# print('\n')
# print('*** Copyable group PnL ***')
# print(df[df['is_copyable_group']][['pnl', 'copyable_pnl']].sum())
# print(f'wallet_roi={df[df["is_copyable_group"]]["pnl"].sum() / df[df["is_copyable_group"]]["notional"].sum()}')
# print(f'copyable_roi={df[df["is_copyable_group"]]["copyable_pnl"].sum() / df[df["is_copyable_group"]]["copyable_notional"].sum()}')

# df = df.groupby(['bucket', 'token_id', 'side']).agg(
#     copyable_pnl=('copyable_pnl', 'sum'),
#     wallet_count=('wallet', 'nunique'),
#     pnl=('pnl', 'sum'),
#     predicting_group_count=('is_predicting_group', 'sum'),
#     copyable_group_count=('is_copyable_group', 'sum'),
#     wallet_in_filter_count=('is_filter_group', 'sum'),
#     notional=('notional', 'sum'),
#     copyable_notional=('copyable_notional', 'sum'),
# )
# df.reset_index(inplace=True)
# df = df[
#     ((df['wallet_count'] > 1)
#     & (df['predicting_group_count'] <= 0)
#     & (df['copyable_group_count'] >= 0)
#      & (df['wallet_in_filter_count'] >= 0) )
#       | ( df['wallet_count'] == df['wallet_in_filter_count'])
#      ]

# print('\n')
# print('*** Combined PnL ***')
# print(df[['pnl', 'copyable_pnl']].sum())
# print(f'wallet_roi={df["pnl"].sum() / df["notional"].sum() if "notional" in df.columns else np.nan}')
# print(f'copyable_roi={df["copyable_pnl"].sum() / df["copyable_notional"].sum() if "copyable_notional" in df.columns else np.nan}')

In [267]:
wallet_vol_train['copyable_pnl_factor'] = np.clip(
    wallet_vol_train['copyable_pnl'] / wallet_vol_train['total_pnl'].replace(0, np.nan),
    0,
    1.0,
).fillna(0.0)
wallet_vol_train['copyable_roi'] = wallet_vol_train['average_roi'] * wallet_vol_train['copyable_pnl_factor']
wallet_vol_train['buy_copyable_roi'] = wallet_vol_train['buy_copyable_pnl'] / wallet_vol_train['buy_copyable_notional'].replace(0, np.nan)

# Keep sorting deterministic for downstream filtering/inspection.
wallet_vol_train.sort_values('copyable_roi', ascending=False, inplace=True)
wallet_vol_train.reset_index(drop=True, inplace=True)

In [268]:
wallet_cohorts = {}

In [383]:
# Final wallet selection: threshold-based copyable + predicting groups
# COPYABLE_SCORE_MIN = -1
# PREDICTING_SCORE_MIN = -2

candidates = wallet_vol_train.copy()
candidates['buy_copyable_factor'] = candidates['buy_copyable_pnl'] / candidates['buy_pnl']

for col, default in {
    'top10_pnl_pct': np.nan,
    'top_market_abs_pnl_pct': np.nan,
    'market_pnl_hhi': np.nan,
    'positive_bucket_share': np.nan,
}.items():
    if col not in candidates.columns:
        candidates[col] = default

for col in [
    'average_roi', 'median_roi', 'num_buckets', 'num_markets',
    'pnl_volatility', 'max_drawdown_to_pnl',
    'top_market_pnl_pct', 'top_market_abs_pnl_pct', 'top5_pnl_pct', 'top10_pnl_pct', 'market_pnl_hhi',
    'copyable_roi', 'copyable_pnl_factor', 'copyable_pnl', 'total_notional',
    'max_copyable_drawdown_to_copyable_pnl', 'worst5_pnl_pct', 'positive_bucket_share',
]:
    if col in candidates.columns:
        candidates[col] = pd.to_numeric(candidates[col], errors='coerce')

# # politics: 
# base_mask = (
#     (candidates['total_pnl'] > 2000)
#     & (candidates['buy_roi'] >= 0.1)
#     & (candidates['copyable_pnl'] >= 1000)
#     & (candidates['trade_count'] >= 300)
#     # & (candidates['median_roi'] >= 0)
#     & (candidates['num_buckets'] >= 30)
#     # & (candidates['num_markets'] >= 50)
#     & (candidates['estimated_buy_sharpe'] >= 3)
#     & (candidates['market_pnl_hhi'].fillna(0.20) < 0.2)
#     & (candidates['max_drawdown_to_pnl'] <= 0.2)
#     # & (candidates['top5_pnl_pct'] < 0.55)
#     # & (candidates['top10_pnl_pct'].fillna(0.85) < 0.8)
#     # & (candidates['top_market_abs_pnl_pct'].fillna(candidates['top_market_pnl_pct']) < 0.25)
#     & (candidates['median_dt'].dt.date <= (pd.Timestamp.today().date() - pd.Timedelta(days=30)))
#     & (candidates['total_notional'] >= 5_000)
# )

# Weather: 
base_mask = (
    (candidates['buy_roi'] >= 0.02)
    & (candidates['buy_pnl'] >= 300)
    & (candidates['num_markets'] >= 20)
    & (candidates['num_buckets'] >= 50)
    # & (candidates['max_drawdown_to_pnl'] <= 0.2)
    # & (candidates['market_pnl_hhi'].fillna(0.20) < 0.2)
    # & (candidates['median_dt'].dt.date <= (pd.Timestamp.today().date() - pd.Timedelta(days=30)))
    & (candidates['total_notional'] >= 5_000)
    & (candidates['estimated_buy_sharpe'] >= 4)
    & (candidates['buy_copyable_pnl'] > 300)
)

eligible_base = candidates[base_mask].copy()
if eligible_base.empty:
    raise ValueError('No wallets passed base eligibility filters.')

eligible_base['sample_mult'] = np.clip(
    np.log1p(eligible_base['num_buckets']) / np.log(2000.0),
    0.20,
    1.00,
)
eligible_base['downside_tail'] = eligible_base['worst5_pnl_pct'].abs().fillna(0.0)
eligible_base['predictability_score'] = eligible_base['sample_mult'] * (
    # 2.5 * eligible_base['average_roi'].fillna(0.0)
    # + 1.5 * eligible_base['median_roi'].fillna(0.0)
    + 1.2 * (eligible_base['positive_bucket_share'].fillna(0.5) - 0.5)
    - 1.0 * eligible_base['pnl_volatility'].fillna(0.0)
    - 1.2 * eligible_base['max_drawdown_to_pnl'].fillna(0.0)
    - 0.8 * eligible_base['top_market_abs_pnl_pct'].fillna(eligible_base['top_market_pnl_pct']).fillna(0.0)
    - 0.6 * eligible_base['market_pnl_hhi'].fillna(0.0)
    - 0.5 * eligible_base['downside_tail']
)
eligible_base['predicting_final_score'] = eligible_base['predictability_score']

# Weather: 
copyable_mask = (
    (eligible_base['buy_copyable_pnl'] > 1000)
    & (eligible_base['buy_copyable_roi'] >= 0.04)
    & (eligible_base['estimated_copyable_buy_sharpe'] >= 4)
)

# Politics:
# copyable_mask = (
#     (eligible_base['buy_copyable_pnl'] > 1000)
#     & (eligible_base['buy_copyable_roi'] >= 0.05)
#     & (eligible_base['estimated_copyable_buy_sharpe'] > 2.3)
#     # & (eligible_base['max_copyable_drawdown_to_copyable_pnl'] <= 0.3)
#     # & (eligible_base['copyable_pnl_similarity_profit_20m_100'] > 0.3)
#     # & (eligible_base['copyable_pnl_similarity_20m_100'] > 0.8)
# )

copyable_candidates = eligible_base[copyable_mask].copy()
copyable_candidates['copyable_efficiency'] = copyable_candidates['copyable_pnl'].fillna(0.0) / (copyable_candidates['total_notional'].fillna(0.0) + 1.0)
copyable_candidates['copyable_dd_ratio'] = (
    copyable_candidates['max_copyable_drawdown_to_copyable_pnl']
    .fillna(copyable_candidates['max_drawdown_to_pnl'])
    .fillna(0.0)
)
copyable_candidates['copyable_score'] = (
    1.8 * copyable_candidates['copyable_roi'].fillna(0.0)
    + 1.2 * copyable_candidates['copyable_pnl_factor'].fillna(0.0)
    + 25.0 * copyable_candidates['copyable_efficiency'].clip(lower=-1.0, upper=1.0)
    - 0.8 * copyable_candidates['copyable_dd_ratio'].clip(lower=0.0)
    - 0.5 * copyable_candidates['top_market_abs_pnl_pct'].fillna(copyable_candidates['top_market_pnl_pct']).fillna(0.0)
)
copyable_candidates['final_score'] = (
    0.60 * copyable_candidates['predictability_score']
    + 0.40 * copyable_candidates['copyable_score']
)

wallet_cohorts['copyable_group'] = (
    copyable_candidates
    .sort_values('final_score', ascending=False)
    .reset_index(drop=True)
)

predicting_pool = eligible_base[
    ~eligible_base['wallet'].isin(wallet_cohorts['copyable_group']['wallet'])
].copy()
wallet_cohorts['predicting_group'] = (
    predicting_pool
    # predicting_pool[predicting_pool['predicting_final_score'] >= PREDICTING_SCORE_MIN]
    .sort_values('predicting_final_score', ascending=False)
    .reset_index(drop=True)
)

overlap = set(wallet_cohorts['copyable_group']['wallet']) & set(wallet_cohorts['predicting_group']['wallet'])
if overlap:
    raise ValueError(f'Wallet groups must be disjoint; found overlap of {len(overlap)} wallets.')

wallet_cohorts['copyable_group']['wallet_quality'] = wallet_cohorts['copyable_group']['final_score']
wallet_cohorts['predicting_group']['wallet_quality'] = wallet_cohorts['predicting_group']['predicting_final_score']

wallet_cohorts['multi_filter'] = wallet_cohorts['copyable_group'].copy()

# Split the copyable group into 3 terciles by estimated_copyable_buy_sharpe
_sharpe = wallet_cohorts['copyable_group']['estimated_copyable_buy_sharpe']
_terciles = pd.qcut(_sharpe, 3, labels=['copyable_buy_sharpe_low', 'copyable_buy_sharpe_mid', 'copyable_buy_sharpe_high'])
for _label in _terciles.cat.categories:
    wallet_cohorts[_label] = wallet_cohorts['copyable_group'][_terciles == _label].copy().reset_index(drop=True)


print(f"Base-eligible wallets: {len(eligible_base):,}")
print(f"Copyable candidates: {len(copyable_candidates):,}")
print(f"Selected wallets (copyable group): {len(wallet_cohorts['copyable_group']):,} total copyable pnl {wallet_cohorts['copyable_group']['copyable_pnl'].sum()}")
print(f"Selected wallets (predicting group): {len(wallet_cohorts['predicting_group']):,}")
print("Copyable sharpe terciles: " + ", ".join(f"{k}={len(wallet_cohorts[k])}" for k in ['copyable_buy_sharpe_low', 'copyable_buy_sharpe_mid', 'copyable_buy_sharpe_high']))
wallet_cohorts['copyable_group'].sort_values('estimated_copyable_buy_sharpe', key=abs, ascending=False).head(50)

Base-eligible wallets: 108
Copyable candidates: 22
Selected wallets (copyable group): 22 total copyable pnl 46823.29934744483
Selected wallets (predicting group): 86
Copyable sharpe terciles: copyable_buy_sharpe_low=8, copyable_buy_sharpe_mid=6, copyable_buy_sharpe_high=8

,wallet,num_buckets,trade_count,total_notional,total_pnl,copyable_pnl,num_markets,median_dt,median_roi,average_roi,max_drawdown,max_copyable_drawdown,buy_pnl,buy_quantity,sell_pnl,sell_quantity,buy_notional,sell_notional,buy_copyable_quantity,buy_copyable_pnl,sell_copyable_quantity,sell_copyable_pnl,buy_roi,sell_roi,buy_copyable_notional,top5_pnl_pct,top10_pnl_pct,worst5_pnl_pct,positive_bucket_share,top_market_pnl_pct,top_market_abs_pnl_pct,market_pnl_hhi,pnl_volatility,estimated_sharpe,estimated_buy_sharpe,estimated_copyable_buy_sharpe,copyable_pnl_similarity,copyable_pnl_similarity_profit,copyable_pnl_similarity_loss,copyable_pnl_similarity_20m_100,copyable_pnl_similarity_profit_20m_100,copyable_pnl_similarity_loss_20m_100,max_drawdown_to_pnl,max_copyable_drawdown_to_copyable_pnl,return,copyable_pnl_factor,copyable_roi,buy_copyable_roi,buy_copyable_factor,sample_mult,downside_tail,predictability_score,predicting_final_score,copyable_efficiency,copyable_dd_ratio,copyable_score,final_score,wallet_quality
13,0x0f607897e7a3e05ae15e7a99e57856454d17026a,6043,6629,96474.50,2325.67,1000.20,2615,2026-05-06 20:15:00+00:00,0.12,0.05,1093.57,243.22,2325.67,130225.02,0.00,0.00,96474.50,0.00,20718.87,1000.20,0.00,0.00,0.02,0.00,15349.14,0.22,0.39,-0.27,0.76,0.11,0.01,0.00,0.33,6.92,6.92,9.26,0.53,0.59,0.47,0.70,0.74,0.68,0.47,0.24,0.02,0.43,0.02,0.07,0.43,1.00,0.27,-0.72,-0.72,0.01,0.24,0.61,-0.18,-0.18
2,0x331d8ec8d8931b479007f4931a6b25b0b6628846,1012,1443,18955.64,8490.54,1737.20,528,2026-07-03 05:32:30+00:00,-1.00,0.72,430.16,268.77,8490.54,95115.57,0.00,0.00,18955.64,0.00,18458.30,1737.20,0.00,0.00,0.45,0.00,3678.57,0.21,0.32,-0.08,0.35,0.06,0.03,0.01,0.57,12.99,12.99,9.18,0.54,0.54,0.58,0.79,0.78,0.84,0.05,0.15,0.45,0.20,0.15,0.47,0.20,0.91,0.08,-0.80,-0.80,0.09,0.15,2.67,0.59,0.59
19,0xc00837a29d51e8cb51a8ce6c1062f512d9f66adf,178,532,11884.65,7408.16,1403.83,32,2026-06-30 04:25:00+00:00,-1.00,-0.27,796.02,59.54,7408.16,47474.55,0.00,0.00,11884.65,0.00,5070.77,1403.83,0.00,0.00,0.62,0.00,1269.40,0.60,0.93,-0.15,0.36,0.46,0.26,0.12,4.13,10.17,10.17,9.18,0.32,0.33,0.32,0.36,0.35,0.40,0.11,0.04,0.62,0.19,-0.05,1.11,0.19,0.68,0.15,-3.27,-3.27,0.12,0.04,2.92,-0.79,-0.79
11,0x919698b19427cbe6945b0dc823f2d9e126a4d934,5080,7284,225292.54,17933.89,3555.89,1973,2026-06-24 05:02:30+00:00,-1.00,0.17,652.43,341.22,17933.89,399845.83,0.00,0.00,225292.54,0.00,60115.39,3555.89,0.00,0.00,0.08,0.00,33871.93,0.09,0.15,-0.07,0.41,0.03,0.01,0.00,0.34,15.98,15.98,8.82,0.57,0.57,0.57,0.71,0.68,0.77,0.04,0.10,0.08,0.20,0.03,0.10,0.20,1.00,0.07,-0.54,-0.54,0.02,0.10,0.61,-0.08,-0.08
3,0x04b3f873b003eba3774df1e5e47a370d27ee1b7e,2998,3044,38445.63,4184.53,1409.42,2730,2026-06-07 04:57:30+00:00,0.20,0.12,282.55,164.83,4184.53,66661.71,0.00,0.00,38445.63,0.00,22238.97,1409.42,0.00,0.00,0.11,0.00,12825.82,0.20,0.31,-0.03,0.72,0.07,0.01,0.00,0.24,10.94,10.94,8.46,0.59,0.56,0.65,0.69,0.65,0.81,0.07,0.12,0.11,0.34,0.04,0.11,0.34,1.00,0.03,-0.09,-0.09,0.04,0.12,1.29,0.47,0.47
1,0x1f127e31717c8d74232fc4d5693e9236b49c9424,623,669,19033.34,2706.51,1567.73,418,2026-05-24 12:20:00+00:00,0.07,0.27,227.07,57.69,2706.51,35919.93,0.00,0.00,19033.34,0.00,11599.22,1567.73,0.00,0.00,0.14,0.00,6146.22,0.37,0.50,-0.11,0.52,0.17,0.05,0.01,0.52,7.37,7.37,8.34,0.67,0.74,0.52,0.85,0.85,0.85,0.08,0.04,0.14,0.58,0.15,0.26,0.58,0.85,0.11,-0.60,-0.60,0.08,0.04,2.97,0.83,0.83
12,0x6011655c4afb76f36dd1b08a137a1ba73466b31e,1653,2075,548445.70,58441.07,4138.46,1619,2026-06-26 17:55:00+00:00,0.05,0.15,2931.26,890.54,58441.07,616272.68,0.00,0.00,548445.70,0.00,47531.75,4138.46,0.00,0.00,0.11,0.00,42300.40,0.06,0.11,-0.08,0.99,0.01,0.02,0.00,0.77,24.16,24.16,7.96,0.66,0.54,0.94,0.64,0.54,0.97,0.05,0.22,0.11,0.07,0.01,0.10,0.07,0.98,0.08,-0.30,-0.30,0.01,0.22,0.11,-0.13,-0.13
10,0xb9012e0d9b60d3920286309328b935cdfa609fc4,1166,3594,435015.92,26153.05,2300.81,983,2026-06-03 13:20:00+00:00,0.01,0.84,990.00,190.58,26153.05,485923.94,0.00,0.00,435015.92,0.00,39808.71,2300.81,0.00,0.00,0.06,0.00,35638.13,0.15,0.23,-0.07,0.94,0.05,0.05,0.01,0.67,15.28,15.28,7.62,0.46,0.48,0.32,0.47,0.50,0.41,0.04,0.08,0.06,0.09,0.07,0.06,0.09,0.93,0.07,-0.24,-0.24,0.01,0.08,0.28,-0.03,-0.03
14,0x41f623e0baae41e385875a3759c474cf0622828e,2659,5423,92315.97,21218.43,4867.32,756,2026-06-13 12:50:00+00:00,-1.00,0.22,1498.24,512.44,21218.43,394481.44,0.00,0.00,92315.97,0.00,65016.50,4867.32,0.00,0.00,0.23,0.00,15215.07,0.26,0.42,-0.07,0.29,0.11,0.03,0.01,1.09,8.09,8.09,5.62,0.57,0.57,0.57,0.80,0.80,0.77,0.07,0.11,0.23,0.23,0.05,0.32,0.23,1.00,0.07,-1.49,-1.49,0.05,0.11,1.58,-0.26,-0.26
4,0xa2eded4da718244771d4f2b7810da45533de9d98,3472,4010,36128.68,3880.07,1133.73,2292,2026-06-13 08:07:30+00:00,0.19,0.07,165.99,147.33,3880.07,65472.99,0.00,0.00,36128.68,0.00,33425.74,1133.73,0.00,0.00,0.11,0.00,18444.68,0.18,0.28,-0.04,0.70,0.05,0.01,0.00,0.18,10.61,10.61,5.54,0.70,0.65,0.81,0.90,0.89,0.93,0.04,0.13,0.11,0.29,0.02,0.06,0.29,1.00,0.04,-0.03,-0.03,0.03,0.13,1.06,0.41,0.41
0,0xb7b9ce6c3db2ebf1dcd12db8ae64cfb2e9f01e0e,291,508,12478.02,4302.98,2432.80,89,2026-07-06 09:55:00+00:00,0.16,0.36,1162.91,687.19,4302.98,36053.41,0.00,0.00,12478.02,0.00,13708.10,2432.80,0.00,0.00,0.34,0.00,4744.35,0.44,0.68,-0.25,0.49,0.26,0.11,0.03,1.53,5.30,5.30,5.33,0.82,0.82,0.80,0.86,0.84,0.95,0.27,0.28,0.34,0.57,0.20,0.51,0.57,0.75,0.25,-1.58,-1.58,0.19,0.28,5.64,1.31,1.31
6,0x2753b2db276ffdddc2b26155815f509fe349e28a,1217,1483,39740.89,2975.95,1078.61,840,2026-06-08 05:55:00+00:00,0.08,0.09,358.27,301.52,2975.95,57655.92,0.00,0.00,39740.89,0.00,21000.28,1078.61,0.00,0.00,0.07,0.00,14475.01,0.20,0.32,-0.21,0.78,0.05,0.02,0.00,0.58,8.12,8.12,5.28,0.82,0.81,0.83,0.91,0.88,0.95,0.12,0.28,0.07,0.36,0.03,0.07,0.36,0.93,0.21,-0.48,-0.48,0.03,0.28,0.94,0.09,0.09
9,0xed541ad118dea9103306043869e83344cac44967,1864,2700,49136.66,5838.10,1119.92,842,2026-06-19 09:00:00+00:00,0.00,0.15,503.71,257.94,5838.10,104313.37,0.00,0.00,49136.66,0.00,16633.71,1119.92,0.00,0.00,0.12,0.00,7835.28,0.14,0.24,-0.10,0.52,0.05,0.02,0.00,0.36,9.76,9.76,5.23,0.60,0.59,0.63,0.76,0.76,0.77,0.09,0.23,0.12,0.19,0.03,0.14,0.19,0.99,0.10,-0.49,-0.49,0.02,0.23,0.66,-0.03,-0.03
17,0x8fb431f5057112cfdb0e7f566b4b687cb69cb9ed,1333,3257,40787.36,10528.84,2856.17,364,2026-05-07 14:10:00+00:00,-1.00,0.21,3588.27,1056.08,10528.84,218785.50,0.00,0.00,40787.36,0.00,50176.32,2856.17,0.00,0.00,0.26,0.00,9354.18,0.53,0.76,-0.16,0.28,0.26,0.07,0.02,1.35,5.84,5.84,5.00,0.56,0.53,0.69,0.81,0.80,0.87,0.34,0.37,0.26,0.27,0.06,0.31,0.27,0.95,0.16,-2.05,-2.05,0.07,0.37,1.85,-0.49,-0.49
5,0x5fe79a73af0a8ad6a83d89256026b14f35981ea9,640,1488,55269.43,9186.69,4424.49,349,2026-06-21 12:22:30+00:00,0.09,0.48,1709.00,579.55,9186.69,144194.65,0.00,0.00,55269.43,0.00,36076.71,4424.49,0.00,0.00,0.17,0.00,13828.11,0.49,0.74,-0.28,0.82,0.24,0.10,0.03,1.56,4.74,4.74,4.90,0.72,0.76,0.56,0.77,0.78,0.71,0.19,0.13,0.17,0.48,0.23,0.32,0.48,0.85,0.28,-1.39,-1.39,0.08,0.13,2.84,0.30,0.30
7,0xbd71233ab7a25bc420929cd67476219762f31281,1660,2466,19953.73,3014.98,1210.01,959,2026-06-29 08:12:30+00:00,-1.00,0.20,624.46,608.07,3014.98,67462.51,0.00,0.00,19953.73,0.00,34502.15,1210.01,0.00,0.00,0.15,0.00,10204.88,0.17,0.31,-0.24,0.42,0.05,0.01,0.00,0.57,8.75,8.75,4.65,0.77,0.73,0.83,0.91,0.88,0.96,0.21,0.50,0.15,0.40,0.08,0.12,0.40,0.98,0.24,-1.02,-1.02,0.06,0.50,1.73,0.08,0.08
16,0xa89518aca5a633a79ad1e9737209c9689f83faac,753,1589,51624.18,20714.19,2210.17,329,2026-06-15 14:50:00+00:00,-1.00,1.45,270.43,116.60,20714.19,183842.30,0.00,0.00,51624.18,0.00,14794.29,2210.17,0.00,0.00,0.40,0.00,4154.34,0.46,0.73,-0.02,0.47,0.11,0.10,0.05,1.76,5.99,5.99,4.60,0.41,0.41,0.79,0.60,0.60,0.88,0.01,0.05,0.40,0.11,0.15,0.53,0.11,0.87,0.02,-1.68,-1.68,0.04,0.05,1.39,-0.46,-0.46
18,0x1cd2da1d25c07776dcc6bfee2c5589da2d98c304,653,1041,13295.70,6569.68,1054.31,287,2026-07-09 02:35:00+00:00,-1.00,1.64,803.64,109.11,6569.68,88962.70,0.00,0.00,13295.70,0.00,3782.58,1054.31,0.00,0.00,0.49,0.00,565.32,0.58,0.89,-0.22,0.28,0.31,0.12,0.03,2.53,9.41,9.41,4.51,0.29,0.31,0.18,0.55,0.59,0.27,0.12,0.10,0.49,0.16,0.26,1.86,0.16,0.85,0.22,-2.70,-2.70,0.08,0.10,2.51,-0.61,-0.61
15,0x85c06787486a90e05ba1df96c034ef95c8cce01d,2026,3947,32556.78,6647.43,2000.22,871,2026-06-02 12:57:30+00:00,-1.00,0.11,2259.80,464.21,6647.43,209871.25,0.00,0.00,32556.78,0.00,32756.86,2000.22,0.00,0.00,0.20,0.00,5081.49,0.39,0.65,-0.10,0.20,0.19,0.03,0.01,0.83,5.72,5.72,4.27,0.59,0.59,0.60,0.83,0.83,0.83,0.34,0.23,0.20,0.30,0.03,0.39,0.30,1.00,0.10,-1.68,-1.68,0.06,0.23,1.76,-0.30,-0.30
21,0xf1e18ec32b2f1e123bc098e3956e6fd00012c152,1172,3591,23560.98,13204.68,1886.19,375,2026-05-31 21:15:00+00:00,-1.00,0.68,685.68,193.49,13204.68,223663.76,0.00,0.00,23560.98,0.00,18373.15,1886.19,0.00,0.00,0.56,0.00,1935.45,0.60,0.80,-0.11,0.21,0.30,0.15,0.05,8.41,5.27,5.27,4.20,0.71,0.73,0.46,0.47,0.47,0.73,0.05,0.10,0.56,0.14,0.10,0.97,0.14,0.93,0.11,-8.40,-8.40,0.08,0.10,2.19,-4.16,-4.16
20,0xb94aa26e2844c47232377604c6001e88f8a5d680,1157,2225,227892.86,6990.63,2155.57,456,2026-05-13 06:30:00+00:00,0.04,0.12,2648.94,830.78,6990.63,255187.02,0.00,0.00,227892.86,0.00,50620.82,2155.57,0.00,0.00,0.03,0.00,45206.55,0.30,0.48,-0.63,0.77,0.10,0.08,0.02,2.41,5.91,5.91,4.09,0.61,0.73,0.58,0.72,0.81,0.71,0.38,0.39,0.03,0.31,0.04,0.05,0.31,0.93,0.63,-2.73,-2.73,0.01,0.39,0.32,-1.51,-1.51
8,0x0af29cc14fb231218c8d005685ac3db427a1ce86,476,767,22703.75,3438.23,1280.25,90,2026-05-11 02:52:30+00:00,0.08,0.51,897.80,324.19,3438.23,40615.22,0.00,0.00,22703.75,0.00,11721.63,1280.25,0.00,0.00,0.15,0.00,6552.35,0.57,0.84,-0.35,0.61,0.27,0.10,0.04,1.13,5.78,5.78,4.07,0.71,0.76,0.59,0.83,0.86,0.77,0.26,0.25,0.15,0.37,0.19,0.20,0.37,0.81,0.35,-1.29,-1.29,0.06,0.25,1.95,0.00,0.00

In [384]:
df_ana = df_full[df_full["is_train"] == False].copy()

In [385]:
wallet_vol_train[wallet_vol_train['wallet'] == '0xeface9902242b0399856f981600b907dcc9bc9a1'].head()

,wallet,num_buckets,trade_count,total_notional,total_pnl,copyable_pnl,num_markets,median_dt,median_roi,average_roi,max_drawdown,max_copyable_drawdown,buy_pnl,buy_quantity,sell_pnl,sell_quantity,buy_notional,sell_notional,buy_copyable_quantity,buy_copyable_pnl,sell_copyable_quantity,sell_copyable_pnl,buy_roi,sell_roi,buy_copyable_notional,top5_pnl_pct,top10_pnl_pct,worst5_pnl_pct,positive_bucket_share,top_market_pnl_pct,top_market_abs_pnl_pct,market_pnl_hhi,pnl_volatility,estimated_sharpe,estimated_buy_sharpe,estimated_copyable_buy_sharpe,copyable_pnl_similarity,copyable_pnl_similarity_profit,copyable_pnl_similarity_loss,copyable_pnl_similarity_20m_100,copyable_pnl_similarity_profit_20m_100,copyable_pnl_similarity_loss_20m_100,max_drawdown_to_pnl,max_copyable_drawdown_to_copyable_pnl,return,copyable_pnl_factor,copyable_roi,buy_copyable_roi
2558,0xeface9902242b0399856f981600b907dcc9bc9a1,1,1,2.78,-2.78,-0.00,1,2025-05-09 01:05:00+00:00,-1.00,-1.00,2.78,0.00,-2.78,927.72,0.00,0.00,2.78,0.00,0.00,-0.00,0.00,0.00,-1.00,0.00,0.00,1.00,1.00,1.00,0.00,1.00,1.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.00,0.00,-0.00,-1.00

In [386]:
wallet_vol_test.sort_values('copyable_pnl', key=abs, ascending=False)

,wallet,num_buckets,trade_count,total_notional,total_pnl,copyable_pnl,num_markets,median_dt,median_roi,average_roi,max_drawdown,max_copyable_drawdown,buy_pnl,buy_quantity,sell_pnl,sell_quantity,buy_notional,sell_notional,buy_copyable_quantity,buy_copyable_pnl,sell_copyable_quantity,sell_copyable_pnl,buy_roi,sell_roi,buy_copyable_notional,top5_pnl_pct,top10_pnl_pct,worst5_pnl_pct,positive_bucket_share,top_market_pnl_pct,top_market_abs_pnl_pct,market_pnl_hhi,pnl_volatility,estimated_sharpe,estimated_buy_sharpe,estimated_copyable_buy_sharpe,copyable_pnl_similarity,copyable_pnl_similarity_profit,copyable_pnl_similarity_loss,copyable_pnl_similarity_20m_100,copyable_pnl_similarity_profit_20m_100,copyable_pnl_similarity_loss_20m_100,max_drawdown_to_pnl,max_copyable_drawdown_to_copyable_pnl,return
395,0x7300833941f579802d58791eb1d0152c1b17e52c,3951,7490,48878.94,-3626.31,-4559.70,1635,2026-08-10 11:40:00+00:00,-1.00,0.13,5399.96,4858.81,-3626.31,402164.10,0.00,0.00,48878.94,0.00,93753.14,-4559.70,0.00,0.00,-0.07,0.00,11394.74,-1.02,-1.75,0.50,0.18,-0.30,0.02,0.00,NaN,-3.40,-3.40,-9.24,0.62,0.57,0.73,0.79,0.75,0.89,NaN,NaN,-0.07
722,0xe040ffe586e21cb49449e8daf19b1cdff87a824f,20050,26275,314324.38,-281.61,-4230.82,4968,2026-08-06 08:25:00+00:00,0.01,-0.03,3787.04,4573.06,-281.61,447829.94,0.00,0.00,314324.38,0.00,119015.93,-4230.82,0.00,0.00,-0.00,0.00,83535.30,-3.92,-6.93,4.34,0.76,-2.05,0.01,0.00,NaN,-0.57,-0.57,-10.77,0.68,0.65,0.72,0.80,0.77,0.83,NaN,NaN,-0.00
486,0x945a49252f772a10c6ddd1d1e1e24ee20438a48c,41270,62054,107660.48,-706.61,-4201.32,3888,2026-08-10 13:35:00+00:00,-1.00,-0.01,2492.07,4289.51,-706.61,351592.07,0.00,0.00,107660.48,0.00,181068.82,-4201.32,0.00,0.00,-0.01,0.00,55444.81,-0.61,-1.04,0.36,0.31,-0.30,0.01,0.00,NaN,-2.02,-2.02,-16.32,0.82,0.79,0.85,0.91,0.89,0.94,NaN,NaN,-0.01
228,0x441ad4887046db7732623c72bb6edb72652be9c7,918,1399,93118.12,2006.47,-3332.07,545,2026-08-12 21:15:00+00:00,-1.00,0.06,4691.34,3370.39,2006.47,168167.23,0.00,0.00,93118.12,0.00,14761.44,-3332.07,0.00,0.00,0.02,0.00,8173.75,4.29,6.63,-3.73,0.46,1.80,0.06,0.01,25.90,1.33,1.33,-5.04,0.42,0.26,0.61,0.51,0.32,0.70,2.34,NaN,0.02
585,0xb40e89677d59665d5188541ad860450a6e2a7cc9,35032,49010,289615.77,6527.80,-3236.61,4537,2026-08-11 10:15:00+00:00,0.11,0.02,2131.13,4103.41,6527.80,555319.43,0.00,0.00,289615.77,0.00,197369.45,-3236.61,0.00,0.00,0.02,0.00,102934.10,0.14,0.24,-0.12,0.60,0.06,0.00,0.00,0.22,7.52,7.52,-8.23,0.71,0.67,0.76,0.83,0.81,0.87,0.33,NaN,0.02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1023,0xce5fbbc9b59fc959e7a899393311ea2134f4c468,2,4,11.64,-11.64,0.00,1,2026-08-09 03:02:30+00:00,-1.00,-1.00,11.64,0.00,-11.64,388.00,0.00,0.00,11.64,0.00,0.00,0.00,0.00,0.00,-1.00,0.00,0.00,1.00,1.00,1.00,0.00,1.00,1.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.00
1018,0x9ffaa9cd1fb96e1fd635cae0a13e2022827fc8fc,1,1,1.00,-1.00,0.00,1,2026-08-06 11:05:00+00:00,-1.00,-1.00,1.00,0.00,-1.00,33.33,0.00,0.00,1.00,0.00,-0.00,0.00,0.00,0.00,-1.00,0.00,-0.00,1.00,1.00,1.00,0.00,1.00,1.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.00
864,0x2fdb5df2a326fdfad9ebd030cafe72359da88ffc,3,3,133.34,39.18,0.00,3,2026-08-10 03:55:00+00:00,0.05,0.15,0.00,0.00,39.18,172.52,0.00,0.00,133.34,0.00,-0.00,0.00,0.00,0.00,0.29,0.00,-0.00,1.00,1.00,1.00,1.00,0.96,0.96,0.92,2.51,5.78,5.78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,0.29
1145,0x6a3cb4e6a2b0998151e04093671c1c6a448bc646,1,1,24.98,0.02,0.00,1,2026-08-07 12:00:00+00:00,0.00,0.00,0.00,0.00,0.02,25.00,0.00,0.00,24.98,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,0.00
943,0x313ab978014530595d5714a876a819f5b4646475,1,1,49.90,0.10,0.00,1,2026-07-31 00:35:00+00:00,0.00,0.00,0.00,0.00,0.10,50.00,0.00,0.00,49.90,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,0.00

In [387]:
df_full['is_copyable'] = df_full['avail_copy_count_5m_100'] >=1

In [388]:
wallet_cohorts['copyable_group']['wallet']

0     0xb7b9ce6c3db2ebf1dcd12db8ae64cfb2e9f01e0e
1     0x1f127e31717c8d74232fc4d5693e9236b49c9424
2     0x331d8ec8d8931b479007f4931a6b25b0b6628846
3     0x04b3f873b003eba3774df1e5e47a370d27ee1b7e
4     0xa2eded4da718244771d4f2b7810da45533de9d98
5     0x5fe79a73af0a8ad6a83d89256026b14f35981ea9
6     0x2753b2db276ffdddc2b26155815f509fe349e28a
7     0xbd71233ab7a25bc420929cd67476219762f31281
8     0x0af29cc14fb231218c8d005685ac3db427a1ce86
9     0xed541ad118dea9103306043869e83344cac44967
10    0xb9012e0d9b60d3920286309328b935cdfa609fc4
11    0x919698b19427cbe6945b0dc823f2d9e126a4d934
12    0x6011655c4afb76f36dd1b08a137a1ba73466b31e
13    0x0f607897e7a3e05ae15e7a99e57856454d17026a
14    0x41f623e0baae41e385875a3759c474cf0622828e
15    0x85c06787486a90e05ba1df96c034ef95c8cce01d
16    0xa89518aca5a633a79ad1e9737209c9689f83faac
17    0x8fb431f5057112cfdb0e7f566b4b687cb69cb9ed
18    0x1cd2da1d25c07776dcc6bfee2c5589da2d98c304
19    0xc00837a29d51e8cb51a8ce6c1062f512d9f66adf
20    0xb94aa26e2844c47232377604c6001e88f8a5d680
21    0xf1e18ec32b2f1e123bc098e3956e6fd00012c152
Name: wallet, dtype: object

In [389]:
df_full[df_full['wallet'].isin(wallet_cohorts['copyable_group']['wallet'])] \
    .groupby('wallet') \
    .agg(
        trade_count=('wallet', 'count'),
        copyable_count=('is_copyable', 'sum')
    ) \
    .assign(copyable_ratio=lambda x: x['copyable_count'] / x['trade_count']) \
    .reset_index().sort_values('trade_count', ascending=False)

,wallet,trade_count,copyable_count,copyable_ratio
12,0x919698b19427cbe6945b0dc823f2d9e126a4d934,9610,4425,0.46
2,0x0f607897e7a3e05ae15e7a99e57856454d17026a,6629,1999,0.30
7,0x41f623e0baae41e385875a3759c474cf0622828e,5434,2827,0.52
16,0xb9012e0d9b60d3920286309328b935cdfa609fc4,4521,2066,0.46
13,0xa2eded4da718244771d4f2b7810da45533de9d98,4446,3277,0.74
18,0xbd71233ab7a25bc420929cd67476219762f31281,3973,2866,0.72
10,0x85c06787486a90e05ba1df96c034ef95c8cce01d,3951,1884,0.48
21,0xf1e18ec32b2f1e123bc098e3956e6fd00012c152,3624,992,0.27
0,0x04b3f873b003eba3774df1e5e47a370d27ee1b7e,3540,2368,0.67
11,0x8fb431f5057112cfdb0e7f566b4b687cb69cb9ed,3257,1796,0.55
20,0xed541ad118dea9103306043869e83344cac44967,2997,1349,0.45
9,0x6011655c4afb76f36dd1b08a137a1ba73466b31e,2739,842,0.31
17,0xb94aa26e2844c47232377604c6001e88f8a5d680,2225,1493,0.67
14,0xa89518aca5a633a79ad1e9737209c9689f83faac,2042,585,0.29
5,0x2753b2db276ffdddc2b26155815f509fe349e28a,1890,1100,0.58
8,0x5fe79a73af0a8ad6a83d89256026b14f35981ea9,1670,1275,0.76
6,0x331d8ec8d8931b479007f4931a6b25b0b6628846,1443,608,0.42
3,0x1cd2da1d25c07776dcc6bfee2c5589da2d98c304,1041,216,0.21
1,0x0af29cc14fb231218c8d005685ac3db427a1ce86,767,476,0.62
4,0x1f127e31717c8d74232fc4d5693e9236b49c9424,669,449,0.67
15,0xb7b9ce6c3db2ebf1dcd12db8ae64cfb2e9f01e0e,602,423,0.70
19,0xc00837a29d51e8cb51a8ce6c1062f512d9f66adf,532,120,0.23

In [390]:
wallet_cohorts['copyable_group'].columns

Index(['wallet', 'num_buckets', 'trade_count', 'total_notional', 'total_pnl',
       'copyable_pnl', 'num_markets', 'median_dt', 'median_roi', 'average_roi',
       'max_drawdown', 'max_copyable_drawdown', 'buy_pnl', 'buy_quantity',
       'sell_pnl', 'sell_quantity', 'buy_notional', 'sell_notional',
       'buy_copyable_quantity', 'buy_copyable_pnl', 'sell_copyable_quantity',
       'sell_copyable_pnl', 'buy_roi', 'sell_roi', 'buy_copyable_notional',
       'top5_pnl_pct', 'top10_pnl_pct', 'worst5_pnl_pct',
       'positive_bucket_share', 'top_market_pnl_pct', 'top_market_abs_pnl_pct',
       'market_pnl_hhi', 'pnl_volatility', 'estimated_sharpe',
       'estimated_buy_sharpe', 'estimated_copyable_buy_sharpe',
       'copyable_pnl_similarity', 'copyable_pnl_similarity_profit',
       'copyable_pnl_similarity_loss', 'copyable_pnl_similarity_20m_100',
       'copyable_pnl_similarity_profit_20m_100',
       'copyable_pnl_similarity_loss_20m_100', 'max_drawdown_to_pnl',
       'max_copyable_drawdown_to_copyable_pnl', 'return',
       'copyable_pnl_factor', 'copyable_roi', 'buy_copyable_roi',
       'buy_copyable_factor', 'sample_mult', 'downside_tail',
       'predictability_score', 'predicting_final_score', 'copyable_efficiency',
       'copyable_dd_ratio', 'copyable_score', 'final_score', 'wallet_quality'],
      dtype='object')

In [391]:
wallet_cohorts['copyable_group'].sort_values('estimated_buy_sharpe', ascending=False)

,wallet,num_buckets,trade_count,total_notional,total_pnl,copyable_pnl,num_markets,median_dt,median_roi,average_roi,max_drawdown,max_copyable_drawdown,buy_pnl,buy_quantity,sell_pnl,sell_quantity,buy_notional,sell_notional,buy_copyable_quantity,buy_copyable_pnl,sell_copyable_quantity,sell_copyable_pnl,buy_roi,sell_roi,buy_copyable_notional,top5_pnl_pct,top10_pnl_pct,worst5_pnl_pct,positive_bucket_share,top_market_pnl_pct,top_market_abs_pnl_pct,market_pnl_hhi,pnl_volatility,estimated_sharpe,estimated_buy_sharpe,estimated_copyable_buy_sharpe,copyable_pnl_similarity,copyable_pnl_similarity_profit,copyable_pnl_similarity_loss,copyable_pnl_similarity_20m_100,copyable_pnl_similarity_profit_20m_100,copyable_pnl_similarity_loss_20m_100,max_drawdown_to_pnl,max_copyable_drawdown_to_copyable_pnl,return,copyable_pnl_factor,copyable_roi,buy_copyable_roi,buy_copyable_factor,sample_mult,downside_tail,predictability_score,predicting_final_score,copyable_efficiency,copyable_dd_ratio,copyable_score,final_score,wallet_quality
12,0x6011655c4afb76f36dd1b08a137a1ba73466b31e,1653,2075,548445.70,58441.07,4138.46,1619,2026-06-26 17:55:00+00:00,0.05,0.15,2931.26,890.54,58441.07,616272.68,0.00,0.00,548445.70,0.00,47531.75,4138.46,0.00,0.00,0.11,0.00,42300.40,0.06,0.11,-0.08,0.99,0.01,0.02,0.00,0.77,24.16,24.16,7.96,0.66,0.54,0.94,0.64,0.54,0.97,0.05,0.22,0.11,0.07,0.01,0.10,0.07,0.98,0.08,-0.30,-0.30,0.01,0.22,0.11,-0.13,-0.13
11,0x919698b19427cbe6945b0dc823f2d9e126a4d934,5080,7284,225292.54,17933.89,3555.89,1973,2026-06-24 05:02:30+00:00,-1.00,0.17,652.43,341.22,17933.89,399845.83,0.00,0.00,225292.54,0.00,60115.39,3555.89,0.00,0.00,0.08,0.00,33871.93,0.09,0.15,-0.07,0.41,0.03,0.01,0.00,0.34,15.98,15.98,8.82,0.57,0.57,0.57,0.71,0.68,0.77,0.04,0.10,0.08,0.20,0.03,0.10,0.20,1.00,0.07,-0.54,-0.54,0.02,0.10,0.61,-0.08,-0.08
10,0xb9012e0d9b60d3920286309328b935cdfa609fc4,1166,3594,435015.92,26153.05,2300.81,983,2026-06-03 13:20:00+00:00,0.01,0.84,990.00,190.58,26153.05,485923.94,0.00,0.00,435015.92,0.00,39808.71,2300.81,0.00,0.00,0.06,0.00,35638.13,0.15,0.23,-0.07,0.94,0.05,0.05,0.01,0.67,15.28,15.28,7.62,0.46,0.48,0.32,0.47,0.50,0.41,0.04,0.08,0.06,0.09,0.07,0.06,0.09,0.93,0.07,-0.24,-0.24,0.01,0.08,0.28,-0.03,-0.03
2,0x331d8ec8d8931b479007f4931a6b25b0b6628846,1012,1443,18955.64,8490.54,1737.20,528,2026-07-03 05:32:30+00:00,-1.00,0.72,430.16,268.77,8490.54,95115.57,0.00,0.00,18955.64,0.00,18458.30,1737.20,0.00,0.00,0.45,0.00,3678.57,0.21,0.32,-0.08,0.35,0.06,0.03,0.01,0.57,12.99,12.99,9.18,0.54,0.54,0.58,0.79,0.78,0.84,0.05,0.15,0.45,0.20,0.15,0.47,0.20,0.91,0.08,-0.80,-0.80,0.09,0.15,2.67,0.59,0.59
3,0x04b3f873b003eba3774df1e5e47a370d27ee1b7e,2998,3044,38445.63,4184.53,1409.42,2730,2026-06-07 04:57:30+00:00,0.20,0.12,282.55,164.83,4184.53,66661.71,0.00,0.00,38445.63,0.00,22238.97,1409.42,0.00,0.00,0.11,0.00,12825.82,0.20,0.31,-0.03,0.72,0.07,0.01,0.00,0.24,10.94,10.94,8.46,0.59,0.56,0.65,0.69,0.65,0.81,0.07,0.12,0.11,0.34,0.04,0.11,0.34,1.00,0.03,-0.09,-0.09,0.04,0.12,1.29,0.47,0.47
4,0xa2eded4da718244771d4f2b7810da45533de9d98,3472,4010,36128.68,3880.07,1133.73,2292,2026-06-13 08:07:30+00:00,0.19,0.07,165.99,147.33,3880.07,65472.99,0.00,0.00,36128.68,0.00,33425.74,1133.73,0.00,0.00,0.11,0.00,18444.68,0.18,0.28,-0.04,0.70,0.05,0.01,0.00,0.18,10.61,10.61,5.54,0.70,0.65,0.81,0.90,0.89,0.93,0.04,0.13,0.11,0.29,0.02,0.06,0.29,1.00,0.04,-0.03,-0.03,0.03,0.13,1.06,0.41,0.41
19,0xc00837a29d51e8cb51a8ce6c1062f512d9f66adf,178,532,11884.65,7408.16,1403.83,32,2026-06-30 04:25:00+00:00,-1.00,-0.27,796.02,59.54,7408.16,47474.55,0.00,0.00,11884.65,0.00,5070.77,1403.83,0.00,0.00,0.62,0.00,1269.40,0.60,0.93,-0.15,0.36,0.46,0.26,0.12,4.13,10.17,10.17,9.18,0.32,0.33,0.32,0.36,0.35,0.40,0.11,0.04,0.62,0.19,-0.05,1.11,0.19,0.68,0.15,-3.27,-3.27,0.12,0.04,2.92,-0.79,-0.79
9,0xed541ad118dea9103306043869e83344cac44967,1864,2700,49136.66,5838.10,1119.92,842,2026-06-19 09:00:00+00:00,0.00,0.15,503.71,257.94,5838.10,104313.37,0.00,0.00,49136.66,0.00,16633.71,1119.92,0.00,0.00,0.12,0.00,7835.28,0.14,0.24,-0.10,0.52,0.05,0.02,0.00,0.36,9.76,9.76,5.23,0.60,0.59,0.63,0.76,0.76,0.77,0.09,0.23,0.12,0.19,0.03,0.14,0.19,0.99,0.10,-0.49,-0.49,0.02,0.23,0.66,-0.03,-0.03
18,0x1cd2da1d25c07776dcc6bfee2c5589da2d98c304,653,1041,13295.70,6569.68,1054.31,287,2026-07-09 02:35:00+00:00,-1.00,1.64,803.64,109.11,6569.68,88962.70,0.00,0.00,13295.70,0.00,3782.58,1054.31,0.00,0.00,0.49,0.00,565.32,0.58,0.89,-0.22,0.28,0.31,0.12,0.03,2.53,9.41,9.41,4.51,0.29,0.31,0.18,0.55,0.59,0.27,0.12,0.10,0.49,0.16,0.26,1.86,0.16,0.85,0.22,-2.70,-2.70,0.08,0.10,2.51,-0.61,-0.61
7,0xbd71233ab7a25bc420929cd67476219762f31281,1660,2466,19953.73,3014.98,1210.01,959,2026-06-29 08:12:30+00:00,-1.00,0.20,624.46,608.07,3014.98,67462.51,0.00,0.00,19953.73,0.00,34502.15,1210.01,0.00,0.00,0.15,0.00,10204.88,0.17,0.31,-0.24,0.42,0.05,0.01,0.00,0.57,8.75,8.75,4.65,0.77,0.73,0.83,0.91,0.88,0.96,0.21,0.50,0.15,0.40,0.08,0.12,0.40,0.98,0.24,-1.02,-1.02,0.06,0.50,1.73,0.08,0.08
6,0x2753b2db276ffdddc2b26155815f509fe349e28a,1217,1483,39740.89,2975.95,1078.61,840,2026-06-08 05:55:00+00:00,0.08,0.09,358.27,301.52,2975.95,57655.92,0.00,0.00,39740.89,0.00,21000.28,1078.61,0.00,0.00,0.07,0.00,14475.01,0.20,0.32,-0.21,0.78,0.05,0.02,0.00,0.58,8.12,8.12,5.28,0.82,0.81,0.83,0.91,0.88,0.95,0.12,0.28,0.07,0.36,0.03,0.07,0.36,0.93,0.21,-0.48,-0.48,0.03,0.28,0.94,0.09,0.09
14,0x41f623e0baae41e385875a3759c474cf0622828e,2659,5423,92315.97,21218.43,4867.32,756,2026-06-13 12:50:00+00:00,-1.00,0.22,1498.24,512.44,21218.43,394481.44,0.00,0.00,92315.97,0.00,65016.50,4867.32,0.00,0.00,0.23,0.00,15215.07,0.26,0.42,-0.07,0.29,0.11,0.03,0.01,1.09,8.09,8.09,5.62,0.57,0.57,0.57,0.80,0.80,0.77,0.07,0.11,0.23,0.23,0.05,0.32,0.23,1.00,0.07,-1.49,-1.49,0.05,0.11,1.58,-0.26,-0.26
1,0x1f127e31717c8d74232fc4d5693e9236b49c9424,623,669,19033.34,2706.51,1567.73,418,2026-05-24 12:20:00+00:00,0.07,0.27,227.07,57.69,2706.51,35919.93,0.00,0.00,19033.34,0.00,11599.22,1567.73,0.00,0.00,0.14,0.00,6146.22,0.37,0.50,-0.11,0.52,0.17,0.05,0.01,0.52,7.37,7.37,8.34,0.67,0.74,0.52,0.85,0.85,0.85,0.08,0.04,0.14,0.58,0.15,0.26,0.58,0.85,0.11,-0.60,-0.60,0.08,0.04,2.97,0.83,0.83
13,0x0f607897e7a3e05ae15e7a99e57856454d17026a,6043,6629,96474.50,2325.67,1000.20,2615,2026-05-06 20:15:00+00:00,0.12,0.05,1093.57,243.22,2325.67,130225.02,0.00,0.00,96474.50,0.00,20718.87,1000.20,0.00,0.00,0.02,0.00,15349.14,0.22,0.39,-0.27,0.76,0.11,0.01,0.00,0.33,6.92,6.92,9.26,0.53,0.59,0.47,0.70,0.74,0.68,0.47,0.24,0.02,0.43,0.02,0.07,0.43,1.00,0.27,-0.72,-0.72,0.01,0.24,0.61,-0.18,-0.18
16,0xa89518aca5a633a79ad1e9737209c9689f83faac,753,1589,51624.18,20714.19,2210.17,329,2026-06-15 14:50:00+00:00,-1.00,1.45,270.43,116.60,20714.19,183842.30,0.00,0.00,51624.18,0.00,14794.29,2210.17,0.00,0.00,0.40,0.00,4154.34,0.46,0.73,-0.02,0.47,0.11,0.10,0.05,1.76,5.99,5.99,4.60,0.41,0.41,0.79,0.60,0.60,0.88,0.01,0.05,0.40,0.11,0.15,0.53,0.11,0.87,0.02,-1.68,-1.68,0.04,0.05,1.39,-0.46,-0.46
20,0xb94aa26e2844c47232377604c6001e88f8a5d680,1157,2225,227892.86,6990.63,2155.57,456,2026-05-13 06:30:00+00:00,0.04,0.12,2648.94,830.78,6990.63,255187.02,0.00,0.00,227892.86,0.00,50620.82,2155.57,0.00,0.00,0.03,0.00,45206.55,0.30,0.48,-0.63,0.77,0.10,0.08,0.02,2.41,5.91,5.91,4.09,0.61,0.73,0.58,0.72,0.81,0.71,0.38,0.39,0.03,0.31,0.04,0.05,0.31,0.93,0.63,-2.73,-2.73,0.01,0.39,0.32,-1.51,-1.51
17,0x8fb431f5057112cfdb0e7f566b4b687cb69cb9ed,1333,3257,40787.36,10528.84,2856.17,364,2026-05-07 14:10:00+00:00,-1.00,0.21,3588.27,1056.08,10528.84,218785.50,0.00,0.00,40787.36,0.00,50176.32,2856.17,0.00,0.00,0.26,0.00,9354.18,0.53,0.76,-0.16,0.28,0.26,0.07,0.02,1.35,5.84,5.84,5.00,0.56,0.53,0.69,0.81,0.80,0.87,0.34,0.37,0.26,0.27,0.06,0.31,0.27,0.95,0.16,-2.05,-2.05,0.07,0.37,1.85,-0.49,-0.49
8,0x0af29cc14fb231218c8d005685ac3db427a1ce86,476,767,22703.75,3438.23,1280.25,90,2026-05-11 02:52:30+00:00,0.08,0.51,897.80,324.19,3438.23,40615.22,0.00,0.00,22703.75,0.00,11721.63,1280.25,0.00,0.00,0.15,0.00,6552.35,0.57,0.84,-0.35,0.61,0.27,0.10,0.04,1.13,5.78,5.78,4.07,0.71,0.76,0.59,0.83,0.86,0.77,0.26,0.25,0.15,0.37,0.19,0.20,0.37,0.81,0.35,-1.29,-1.29,0.06,0.25,1.95,0.00,0.00
15,0x85c06787486a90e05ba1df96c034ef95c8cce01d,2026,3947,32556.78,6647.43,2000.22,871,2026-06-02 12:57:30+00:00,-1.00,0.11,2259.80,464.21,6647.43,209871.25,0.00,0.00,32556.78,0.00,32756.86,2000.22,0.00,0.00,0.20,0.00,5081.49,0.39,0.65,-0.10,0.20,0.19,0.03,0.01,0.83,5.72,5.72,4.27,0.59,0.59,0.60,0.83,0.83,0.83,0.34,0.23,0.20,0.30,0.03,0.39,0.30,1.00,0.10,-1.68,-1.68,0.06,0.23,1.76,-0.30,-0.30
0,0xb7b9ce6c3db2ebf1dcd12db8ae64cfb2e9f01e0e,291,508,12478.02,4302.98,2432.80,89,2026-07-06 09:55:00+00:00,0.16,0.36,1162.91,687.19,4302.98,36053.41,0.00,0.00,12478.02,0.00,13708.10,2432.80,0.00,0.00,0.34,0.00,4744.35,0.44,0.68,-0.25,0.49,0.26,0.11,0.03,1.53,5.30,5.30,5.33,0.82,0.82,0.80,0.86,0.84,0.95,0.27,0.28,0.34,0.57,0.20,0.51,0.57,0.75,0.25,-1.58,-1.58,0.19,0.28,5.64,1.31,1.31
21,0xf1e18ec32b2f1e123bc098e3956e6fd00012c152,1172,3591,23560.98,13204.68,1886.19,375,2026-05-31 21:15:00+00:00,-1.00,0.68,685.68,193.49,13204.68,223663.76,0.00,0.00,23560.98,0.00,18373.15,1886.19,0.00,0.00,0.56,0.00,1935.45,0.60,0.80,-0.11,0.21,0.30,0.15,0.05,8.41,5.27,5.27,4.20,0.71,0.73,0.46,0.47,0.47,0.73,0.05,0.10,0.56,0.14,0.10,0.97,0.14,0.93,0.11,-8.40,-8.40,0.08,0.10,2.19,-4.16,-4.16
5,0x5fe79a73af0a8ad6a83d89256026b14f35981ea9,640,1488,55269.43,9186.69,4424.49,349,2026-06-21 12:22:30+00:00,0.09,0.48,1709.00,579.55,9186.69,144194.65,0.00,0.00,55269.43,0.00,36076.71,4424.49,0.00,0.00,0.17,0.00,13828.11,0.49,0.74,-0.28,0.82,0.24,0.10,0.03,1.56,4.74,4.74,4.90,0.72,0.76,0.56,0.77,0.78,0.71,0.19,0.13,0.17,0.48,0.23,0.32,0.48,0.85,0.28,-1.39,-1.39,0.08,0.13,2.84,0.30,0.30

In [392]:
# Copyable group total and open PnL

opening_res = df_ana[
    df_ana['wallet'].isin(wallet_cohorts['copyable_group']['wallet'])
    & (df_ana['position'] == df_ana['quantity'])
][['trade_pnl', 'copyable_pnl', 'notional', 'copyable_notional']].sum()

total_res = df_ana[
    df_ana['wallet'].isin(wallet_cohorts['copyable_group']['wallet'])
][['trade_pnl', 'copyable_pnl', 'notional', 'copyable_notional']].sum()

print('*** Copyable group Open PnL ***')
print(f'wallet_pnl={opening_res["trade_pnl"]} roi={opening_res["trade_pnl"] / opening_res["notional"]}')
print(f'copyable_pnl={opening_res["copyable_pnl"]} roi={opening_res["copyable_pnl"] / opening_res["copyable_notional"]}')
print('\n')

print('*** Copyable group Total PnL ***')
print(f'total_wallet_pnl={total_res["trade_pnl"]} roi={total_res["trade_pnl"] / total_res["notional"]}')
print(f'total_copyable_pnl={total_res["copyable_pnl"]} roi={total_res["copyable_pnl"] / total_res["copyable_notional"]}')

*** Copyable group Open PnL ***
wallet_pnl=13766.69765750346 roi=0.061155355952111384
copyable_pnl=1095.1555362316558 roi=0.05250655719834453


*** Copyable group Total PnL ***
total_wallet_pnl=28950.19525860346 roi=0.06738709748100859
total_copyable_pnl=2889.885811005375 roi=0.058639228096927176

In [393]:
df_ana[df_ana['wallet'].isin(wallet_cohorts['copyable_group']['wallet'])].groupby('condition_id').agg(
    num_wallets=('wallet', 'nunique'),
    total_pnl=('pnl', 'sum'),
    total_copyable_pnl=('copyable_pnl', 'sum'),
    total_notional=('notional', 'sum'),
    trades=('wallet', 'count')
).sort_values('total_copyable_pnl', ascending=False, key=abs).head(20)

,num_wallets,total_pnl,total_copyable_pnl,total_notional,trades
condition_id,,,,,
0x05f8bce23757fe455224bc44c24a57351ac3e318f805bf6105952a11fe2270f4,3,509.99,441.20,2561.80,4
0x04059f75b5e836a96a8624166bef8c97f0ca4a3e2cd33813547f82aea177ccbe,4,-549.60,-335.37,549.60,56
0x013dd91620377bf6d5c4be5ca6ca3fbd3f7a610979b6ef525daa076402d62dfa,3,337.80,248.74,330.24,29
0x9617b531542f1ee0989191749d7f961b3e0099054222536ca387c4b776add357,1,207.69,184.05,200.00,1
0x3948c667d3ad9646304d8a743b2864c7e062ee61e146ff27a899b405cf1409bb,1,-169.60,-169.60,169.60,8
0xfd0eea00a07f884248c1683e5737ff260144460b521b12c9048c868bc4f81fc1,1,1517.78,158.16,17.58,2
0x5f4907329888bfe36b5f58c9a8b954442134eca2f4e37fe742bbd78adc321ad1,2,-170.01,-157.98,170.01,19
0xce58b46c86f7a72c3f553ba77775068fd5056c95da566f23066b401b5b218390,1,162.88,156.54,110.00,2
0x4033530db0e982f7fe404cd486d6d13676c732d90dbe3fc36a52eed956b8e6e6,3,161.74,146.17,78.04,8
0x0b8f2288a708733a9c9332244f9340c2af84e05c26f2095cac80f234a354a349,1,130.98,138.98,68.99,9
0x9764ac90122c76967dd358715759d31c2b35ee39c8bb6f04c2b9d2c21f1aa758,3,-129.16,-128.11,129.16,19
0x193747068c4eb5908447892531ea8ca602c5ad6491c5a0f905a1bf5d32292a6b,1,124.32,124.32,206.46,2
0xfe307d786fe4f43e4dd85dae217c649cce004ccba7d30f584364118969676197,2,-131.08,-124.18,131.08,27
0x209962b94077ac57471f7ff74471936ccd7aeb0abed0192e4e634cfe8efeec8f,2,130.08,119.33,479.84,21
0xe244b0a5380b3a6dbcc1a6ac586512feadc335595757d417a91d86eacab0c1e8,1,104.48,119.14,567.97,9
0x0f1a5ea1652e3efd25aee325e7437ba6659309f2a129afee103ea66258441785,2,180.18,111.58,55.05,20
0xb02126d42e2721e697249b16803fc8b4af9b5839efea34fed28d63590eb7f5bf,4,-118.18,-110.43,190.21,19
0xa5025bb3ccafb9414e4355c8e9fe23769d587055efa896805b5a3a5ca303e9c1,2,-110.00,-110.00,110.00,2
0x52813fb406722a99edfc2d31b1aa1f605013d85eaddc42275dbe851b318bb557,3,236.42,107.87,35.14,9
0xe268db829ffd5b5fb89cb7381b2187d113b74a51058b6dab5d51edafa3709516,4,118.31,102.55,341.22,11

In [394]:
if(WALLET_FILTER is not None):
    wallet_cohorts['copyable_group'] = wallet_cohorts['copyable_group'].query("wallet in @WALLET_FILTER").copy().reset_index(drop=True)

In [395]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [396]:
filter_wallets = set(wallet_cohorts['multi_filter']["wallet"])
df_test =  df_full[
    (df_full['wallet'].isin(filter_wallets))
    ].groupby(['question', 'condition_id', 'outcome']).agg(
    # ].groupby(['wallet']).agg(
        pnl_sum=('pnl', 'sum'),
        trade_count=('pnl', 'size'),
        wallet_count=('wallet', 'nunique'),
    ).reset_index().sort_values('pnl_sum', key=abs, ascending=False)

big_conditions = df_test.groupby('condition_id').agg(
    abs_pnl_sum=('pnl_sum', lambda x: abs(x).sum()),
    min_abs_pnl_pct=('pnl_sum', lambda x: abs(x).min() / abs(x).sum() if abs(x).sum() > 0 else 0)
).reset_index().sort_values('abs_pnl_sum', ascending=False)



print(df_test['pnl_sum'].sum())
df_test = df_test[df_test['condition_id'].isin(big_conditions['condition_id'])].sort_values('question', ascending=False).merge(big_conditions, on='condition_id', how='left')

print(df_test[df_test['min_abs_pnl_pct']<0.1]['pnl_sum'].sum()) 

df_test[df_test['min_abs_pnl_pct'] < 0.1].sort_values(['abs_pnl_sum'], ascending=False).head(2)

275104.4901984331
105068.26811545496

,question,condition_id,outcome,pnl_sum,trade_count,wallet_count,abs_pnl_sum,min_abs_pnl_pct
17760,Will the highest temperature in Austin be between 82-83°F on May 20?,0xe026b92fd7b14d6b003224a3b1a3df6f5f74e598d9828e2888e22d1f217721df,No,3964.41,7,1,3976.41,0.00
17761,Will the highest temperature in Austin be between 82-83°F on May 20?,0xe026b92fd7b14d6b003224a3b1a3df6f5f74e598d9828e2888e22d1f217721df,Yes,-12.00,1,1,3976.41,0.00

In [397]:
wallets = set(wallet_cohorts['copyable_group']['wallet'])

df = df_full #[~df_full["is_train"]].copy()
print(len(df))

df_wallets = df[
    (df['wallet'].isin(wallets))
    & ~df['is_train']
    ].copy()
print(len(df_wallets))

df = df_wallets.groupby('condition_id').agg(
    pnl=('pnl', 'sum'),
    notional=('notional', 'sum'),
    sell_count=('side', lambda x: (x == 'SELL').sum()),
    buy_count=('side', lambda x: (x == 'BUY').sum()),
    wallets=('wallet', lambda x: x.nunique()),
).sort_values(by="pnl", key=np.abs, ascending=False).merge(mdf, on="condition_id", how="left")

13629316
7837

In [398]:
df_wallets[df_wallets['side'] == 'BUY'].groupby('condition_id').agg(
    primary_tag=('primary_tag', 'first'),
    pnl=('pnl', 'sum'),
    copyable_pnl=('copyable_pnl', 'sum'),
    notional=('notional', 'sum'),
    sell_count=('side', lambda x: (x == 'SELL').sum()),
    buy_count=('side', lambda x: (x == 'BUY').sum()),
    wallets=('wallet', lambda x: x.nunique())
).reset_index(drop=False).groupby('primary_tag').agg(
    pnl=('pnl', 'sum'),
    copyable_pnl=('copyable_pnl', 'sum'),
    count=('condition_id', 'size')).sort_values(by="copyable_pnl", key=np.abs, ascending=False).head(20)

                 pnl  copyable_pnl  count
primary_tag
Weather     28950.20       2889.89   2316

In [399]:
wallet_set = set(wallet_cohorts['copyable_group']['wallet'])
print(f"Copyable wallets: {len(wallet_set)} with fills {df_wallets[df_wallets['wallet'].isin(wallet_set)].shape[0]} with total PnL: {df_wallets[df_wallets['wallet'].isin(wallet_set)]['pnl'].sum():,.2f}")
df_wallets[df_wallets['wallet'].isin(wallet_set)]['trade_pnl'].sum()

Copyable wallets: 22 with fills 7837 with total PnL: 28,950.20

np.float64(28950.19525860346)

In [400]:
df_wallets[df_wallets['wallet'].isin(wallet_set)].groupby('wallet').agg(
    pnl=('trade_pnl', 'sum'),
    notional=('notional', 'sum'),
    trades=('wallet', 'count'),
    copyable_pnl=('copyable_pnl', 'sum'),
    copyable_qty_5m_100=('copyable_qty_5m_100', 'sum'),
    ).sort_values(by="pnl", key=np.abs, ascending=False).head(20)

,pnl,notional,trades,copyable_pnl,copyable_qty_5m_100
wallet,,,,,
0x6011655c4afb76f36dd1b08a137a1ba73466b31e,15129.95,155773.26,664,234.34,2463.22
0xb9012e0d9b60d3920286309328b935cdfa609fc4,5215.15,124928.89,927,645.06,9328.03
0x919698b19427cbe6945b0dc823f2d9e126a4d934,3627.92,69014.33,2326,691.51,27094.51
0xa89518aca5a633a79ad1e9737209c9689f83faac,2145.00,22293.28,453,255.84,4231.78
0x5fe79a73af0a8ad6a83d89256026b14f35981ea9,1716.88,14322.85,182,1022.65,12147.50
0xbd71233ab7a25bc420929cd67476219762f31281,1278.02,8804.12,1507,77.59,17758.96
0xb7b9ce6c3db2ebf1dcd12db8ae64cfb2e9f01e0e,-418.88,1739.85,94,-369.29,1977.27
0x04b3f873b003eba3774df1e5e47a370d27ee1b7e,314.78,8115.46,496,282.47,4576.01
0x85c06787486a90e05ba1df96c034ef95c8cce01d,-115.79,165.79,4,3.75,54.71
0x41f623e0baae41e385875a3759c474cf0622828e,-110.11,110.11,11,-17.61,119.79
0xed541ad118dea9103306043869e83344cac44967,94.84,14420.18,297,166.55,4620.74
0x2753b2db276ffdddc2b26155815f509fe349e28a,88.96,6076.27,407,-29.94,4248.49
0xf1e18ec32b2f1e123bc098e3956e6fd00012c152,-39.66,59.66,33,-34.07,318.42
0xa2eded4da718244771d4f2b7810da45533de9d98,23.14,3786.31,436,-38.96,5148.75

In [401]:
MARKET = '0xaabf22a03217285585592f3082f27e2b0f4c1cee2bb4003e84817100bbcf1938'

market_def = mdf.loc[mdf['condition_id'] == MARKET].head(1).squeeze()
print(f"Market: {market_def}")

dfc = df_full[(df_full['condition_id'] == MARKET)
              & (df_full['wallet'].isin(wallets))].copy()
# dfc['bucket'] = dfc['dt'].dt.floor('1h')


dfc = dfc.groupby(['dt', 'wallet', 'side', 'outcome']).agg( 
        pnl=('pnl', 'sum'),
        notional=('notional', 'sum'),
        quantity=('quantity', 'sum'),
        position=('position', 'last'),
        avg_price=('price', lambda x: (x * dfc.loc[x.index, 'quantity']).sum() / dfc.loc[x.index, 'quantity'].sum()),
        copyable_qty_5m_100=('copyable_qty_5m_100', 'sum'),
        copyable_pnl=('copyable_pnl', 'sum'),
)[['pnl', 'position', 'notional', 'quantity', 'avg_price', 'copyable_qty_5m_100', 'copyable_pnl']].reset_index().sort_values(['dt', 'wallet', 'side', 'outcome'])

Market: Empty DataFrame
Columns: [condition_id, end_date_iso, question, tags, primary_tag, winner_token_id, outcome]
Index: []

In [402]:
# dominant tags
wallet_fills = df_full[df_full['wallet'].isin(wallet_cohorts['multi_filter']['wallet'])]

dominant_tags = (
    wallet_fills
    .groupby(['wallet', 'primary_tag'], as_index=False)[['quantity', 'pnl']].sum()
    .sort_values(['wallet', 'quantity'], ascending=[True, False])
    .assign(total_qty=lambda df: df.groupby('wallet')['quantity'].transform('sum'))
    .drop_duplicates('wallet')
    .assign(primary_tag_ratio=lambda df: df['quantity'] / df['total_qty'])
    .rename(columns={
        'quantity': 'primary_tag_qty'
    })[['wallet', 'primary_tag', 'primary_tag_qty', 'primary_tag_ratio', 'pnl']]
)

In [403]:
print(len(dominant_tags))
dominant_tags.sort_values('pnl', ascending=False).head(20)

22

,wallet,primary_tag,primary_tag_qty,primary_tag_ratio,pnl
9,0x6011655c4afb76f36dd1b08a137a1ba73466b31e,Weather,787282.89,1.00,73571.03
16,0xb9012e0d9b60d3920286309328b935cdfa609fc4,Weather,616885.27,1.00,31368.20
14,0xa89518aca5a633a79ad1e9737209c9689f83faac,Weather,245210.80,1.00,22859.19
12,0x919698b19427cbe6945b0dc823f2d9e126a4d934,Weather,511337.16,1.00,21561.81
7,0x41f623e0baae41e385875a3759c474cf0622828e,Weather,395361.03,1.00,21108.32
21,0xf1e18ec32b2f1e123bc098e3956e6fd00012c152,Weather,224314.85,1.00,13165.02
8,0x5fe79a73af0a8ad6a83d89256026b14f35981ea9,Weather,168748.91,1.00,10903.56
11,0x8fb431f5057112cfdb0e7f566b4b687cb69cb9ed,Weather,218785.50,1.00,10528.84
6,0x331d8ec8d8931b479007f4931a6b25b0b6628846,Weather,95115.57,1.00,8490.54
19,0xc00837a29d51e8cb51a8ce6c1062f512d9f66adf,Weather,47474.55,1.00,7408.16
17,0xb94aa26e2844c47232377604c6001e88f8a5d680,Weather,255187.02,1.00,6990.63
3,0x1cd2da1d25c07776dcc6bfee2c5589da2d98c304,Weather,88962.70,1.00,6569.68
10,0x85c06787486a90e05ba1df96c034ef95c8cce01d,Weather,210179.76,1.00,6531.64
20,0xed541ad118dea9103306043869e83344cac44967,Weather,127035.81,1.00,5932.93
0,0x04b3f873b003eba3774df1e5e47a370d27ee1b7e,Weather,80411.36,1.00,4499.31
18,0xbd71233ab7a25bc420929cd67476219762f31281,Weather,96201.91,1.00,4293.00
13,0xa2eded4da718244771d4f2b7810da45533de9d98,Weather,73296.03,1.00,3903.22
15,0xb7b9ce6c3db2ebf1dcd12db8ae64cfb2e9f01e0e,Weather,40723.95,1.00,3884.10
1,0x0af29cc14fb231218c8d005685ac3db427a1ce86,Weather,40615.22,1.00,3438.23
5,0x2753b2db276ffdddc2b26155815f509fe349e28a,Weather,68941.05,1.00,3064.91

In [404]:
watched_wallets = wallet_cohorts['multi_filter'].sort_values("copyable_pnl", key=abs, ascending=False)['wallet'].head(10).to_list()
for w in watched_wallets:
    wallet_df = wallet_vol_train[wallet_vol_train['wallet'] == w]
    wallet_cohorts[w] = wallet_df.copy().reset_index(drop=True)

In [405]:
import plotly.graph_objects as go

from polymarket_analysis.visualization.wallet_plots import copyable_exposure_series

print(f"copyable_group wallets: {len(wallet_cohorts['copyable_group']):,}")
print(f"predicting_group wallets: {len(wallet_cohorts['predicting_group']):,}")

pd.set_option('display.max_rows', 100)

copyable_view = wallet_cohorts['copyable_group'].sort_values('final_score', ascending=False).head(20)
predicting_view = wallet_cohorts['predicting_group'].sort_values('predicting_final_score', ascending=False).head(20)

PNL_TO_QTY = {
    COPYABLE_PNL_BASE: "copyable_qty_5m_100",
    **{f"copyable_pnl_{k}": cfg["qty_col"] for k, cfg in COPYABLE_VARIANTS.items()},
}

plot_rows = []
exposure_rows = []
for group_label, cohort_name in [('copyable', 'copyable_group'), ('predicting', 'predicting_group')]:
    wallets = set(wallet_cohorts[cohort_name]['wallet'])
    group_trades = df_full[
        (df_full['wallet'].isin(wallets))
        & (~df_full['is_train'])
    ][['dt', 'side', 'price', 'pnl', 'last_condition_trade_ts', *COPYABLE_PNL_COLS, *PNL_TO_QTY.values()]].copy()

    # per-fill copy exposure (price × copyable qty, BUY only)
    for pnl_col, qty_col in PNL_TO_QTY.items():
        group_trades[f'{pnl_col}_exposure'] = np.where(
            group_trades[qty_col] > 0,
            group_trades['price'] * group_trades[qty_col],
            np.nan,
        )

    daily = (
        group_trades
        .assign(plot_dt=group_trades['dt'].dt.floor('D'))
        .groupby('plot_dt', as_index=False)[['pnl', *COPYABLE_PNL_COLS]]
        .sum()
        .sort_values('plot_dt')
        .reset_index(drop=True)
    )
    daily['cum_trade_pnl'] = daily['pnl'].cumsum()
    for c in COPYABLE_PNL_COLS:
        daily[f'cum_{c}'] = daily[c].cumsum()
    daily['wallet_group'] = group_label
    plot_rows.append(daily)

    for c in COPYABLE_PNL_COLS:
        exp = copyable_exposure_series(group_trades, f'{c}_exposure', bucket_freq='D')
        exp['wallet_group'] = group_label
        exp['variant'] = c
        exposure_rows.append(exp)

group_perf = pd.concat(plot_rows, ignore_index=True)
group_exposure = pd.concat(exposure_rows, ignore_index=True)

fig = go.Figure()
colors = {'copyable': '#1f77b4', 'predicting': '#ff7f0e'}
dashes = ['dash', 'dot', 'dashdot']
for group_label in ['copyable', 'predicting']:
    g = group_perf[group_perf['wallet_group'] == group_label]
    fig.add_trace(
        go.Scatter(
            x=g['plot_dt'],
            y=g['cum_trade_pnl'],
            mode='lines',
            name=f'{group_label} trade pnl',
            line=dict(color=colors[group_label], width=2),
        )
    )
    for i, c in enumerate(COPYABLE_PNL_COLS):
        fig.add_trace(
            go.Scatter(
                x=g['plot_dt'],
                y=g[f'cum_{c}'],
                mode='lines',
                name=f'{group_label} {c} (raw, unlimited)',
                line=dict(color=colors[group_label], width=2, dash=dashes[i % len(dashes)]),
            )
        )
    for c in COPYABLE_PNL_COLS:
        e = group_exposure[
            (group_exposure['wallet_group'] == group_label)
            & (group_exposure['variant'] == c)
        ]
        fig.add_trace(
            go.Scatter(
                x=e['dt'],
                y=e['exposure'],
                mode='lines',
                name=f'{group_label} {c} exposure',
                line=dict(color=colors[group_label], width=1.5, dash='dot'),
                opacity=0.75,
                yaxis='y2',
            )
        )

fig.update_layout(
    title='Stage1 wallet-group performance on test period — copyable PnL raw/unlimited, exposure on right axis',
    xaxis_title='Date',
    yaxis_title='Cumulative PnL (USDC)',
    yaxis2=dict(title='Exposure (USDC)', overlaying='y', side='right', showgrid=False),
    template='plotly_white',
)
fig.show()

copyable_group wallets: 22
predicting_group wallets: 86

In [406]:
copyable_wallets = wallet_cohorts['copyable_group'].copy().assign(wallet_group='copyable')
predicting_wallets = wallet_cohorts['predicting_group'].copy().assign(wallet_group='predicting')

selected_wallets = (
    pd.concat([copyable_wallets, predicting_wallets], ignore_index=True)
    .drop_duplicates(subset=['wallet', 'wallet_group'])
    .reset_index(drop=True)
)

selected_wallets.to_parquet(WORKSPACE_DIR / 'selected_wallets_v2.parquet', index=False)
print(f"Saved selected wallets: {len(selected_wallets):,}")
print(selected_wallets['wallet_group'].value_counts().to_dict())

Saved selected wallets: 108
{'predicting': 86, 'copyable': 22}

## Build and save strategy registry

All cohorts × all trigger variants → persisted `WalletSelectionStrategy` files.
The backtest loads these directly.

In [407]:
from polymarket_analysis.strategy.definition import TriggerSpec, WalletSelectionStrategy
from polymarket_analysis.strategy.registry import save_strategy

SIGNAL_THRESHOLD = 0.65

selected_wallets = wallet_cohorts['copyable_group'].copy().reset_index(drop=True)
predicting_wallets = selected_wallets.copy()
if 'wallet_quality' not in predicting_wallets.columns:
    if 'predicting_final_score' in predicting_wallets.columns:
        predicting_wallets['wallet_quality'] = predicting_wallets['predicting_final_score']
    else:
        predicting_wallets['wallet_quality'] = 0.0

strategy_specs = [
    (
        'predicting_group__score_threshold',
        f'predicting_group | score >= {SIGNAL_THRESHOLD:.2f} (Kelly)',
        TriggerSpec(
            fn_ref='polymarket_analysis.strategy.triggers.score_threshold',
            params={'threshold': SIGNAL_THRESHOLD, 'dynamic_sizing': True},
            mode='frame',
        ),
    ),
    (
        'predicting_group__all_open_buys',
        'predicting_group | all open-buys (fixed stake)',
        TriggerSpec(
            fn_ref='polymarket_analysis.strategy.triggers.all_open_buys',
            params={'dynamic_sizing': False},
            mode='frame',
        ),
    ),
    (
        'predicting_group__copy_triggers',
        'predicting_group | copy all triggers (tight slippage)',
        TriggerSpec(
            fn_ref='polymarket_analysis.strategy.triggers.copy_triggers',
            params={'dynamic_sizing': False},
            mode='frame',
        ),
    ),
]

all_strategies = []
for strategy_id, name, trigger in strategy_specs:
    all_strategies.append(
        WalletSelectionStrategy(
            strategy_id=strategy_id,
            name=name,
            selection_method='predicting_group',
            trigger=trigger,
            wallets=predicting_wallets.copy(),
            params={
                'selection_metric': 'predicting_final_score',
                'top_n': len(predicting_wallets),
                'signal_threshold': SIGNAL_THRESHOLD if trigger.fn_ref.endswith('score_threshold') else None,
            },
            metadata={
                'cohort': 'predicting_group',
                'wallet_group': 'predicting',
                'selection_metric': 'predicting_final_score',
                'signal_threshold': SIGNAL_THRESHOLD,
                'top_n': len(predicting_wallets),
                'end_date_train': None,
                'train_a_end_date': None,
                'selection_notes': (
                    'threshold-based: copyable group uses copyability quality gates, '
                    'predicting group uses predictability threshold on remaining wallets'
                ),
            },
        )
    )

for strategy in all_strategies:
    parquet_path, json_path = save_strategy(strategy, WORKSPACE_DIR)
    print(f"Saved [{strategy.strategy_id}] wallets={len(strategy.wallets):3d} trigger={strategy.trigger.fn_ref.split('.')[-1]}")

print(f'\nTotal strategies saved: {len(all_strategies)}')

Saved [predicting_group__score_threshold] wallets= 22 trigger=score_threshold
Saved [predicting_group__all_open_buys] wallets= 22 trigger=all_open_buys
Saved [predicting_group__copy_triggers] wallets= 22 trigger=copy_triggers

Total strategies saved: 3

## Strategy registry summary

In [408]:
from polymarket_analysis.strategy.registry import load_all_strategies

registry = load_all_strategies(WORKSPACE_DIR)
summary_rows = []
for sid, s in registry.items():
    summary_rows.append({
        'strategy_id': s.strategy_id,
        'name': s.name,
        'selection_method': s.selection_method,
        'num_wallets': len(s.wallets),
        'trigger_fn': s.trigger.fn_ref.split('.')[-1],
        'threshold': s.trigger.params.get('threshold'),
        'dynamic_sizing': s.trigger.params.get('dynamic_sizing'),
    })

pd.DataFrame(summary_rows).sort_values('strategy_id').reset_index(drop=True).head(1)

,strategy_id,name,selection_method,num_wallets,trigger_fn,threshold,dynamic_sizing
0,0x0c058138ee8749433656cb5c696e0fd3dc7dfabf__all_open_buys,0x0c058138ee8749433656cb5c696e0fd3dc7dfabf | all open-buys (fixed stake),0x0c058138ee8749433656cb5c696e0fd3dc7dfabf,1,all_open_buys,NaN,False

## Wallet PnL over time

Three independent plots:
- **Training plot** — cohort aggregate cumulative PnL over the training period only
- **Test plot** — cohort aggregate cumulative PnL over the test period only (starts from 0)
- **Individual plot** — per-wallet cumulative PnL spanning train + test, with a train/test split
  vline and wallet address labels; test portion resets to 0 at the split boundary

Set `PLOT_WALLET_PNL = False` to skip (e.g. when running headlessly).

In [409]:
PLOT_WALLET_PNL  = True
TOP_N_INDIVIDUAL = 10   # wallets shown in panel 1 per cohort

In [410]:
df_fills = df_full.copy()
df_fills["end_date_iso"] = pd.to_datetime(df_fills["last_condition_trade_ts"], utc=True).dt.floor("D")

# per-variant fill exposure: capital needed to fill the copyable qty at the fill price
PNL_TO_QTY = {
    COPYABLE_PNL_BASE: "copyable_qty_5m_100",
    **{f"copyable_pnl_{k}": cfg["qty_col"] for k, cfg in COPYABLE_VARIANTS.items()},
}
for pnl_col, qty_col in PNL_TO_QTY.items():
    df_fills[f"{pnl_col}_exposure"] = np.where(
        df_fills[qty_col] > 0,
        df_fills["price"] * df_fills[qty_col],
        np.nan,
    )

# Normalise grouped schema → canonical fill-level names
if "total_quantity" in df_fills.columns and "quantity" not in df_fills.columns:
    df_fills = df_fills.rename(columns={
        "total_quantity": "quantity",
        "avg_price": "price",
        "trade_value_usdc": "usdc_amount",
    })

df_fills["usdc_amount"]      = df_fills["usdc_amount"].astype(float)
df_fills["final_value_usdc"] = df_fills["final_value_usdc"].astype(float)
df_fills["quantity"]         = df_fills["quantity"].astype(float)

In [411]:
filter_fills = df_fills[
    (df_fills['wallet'].isin(wallet_cohorts['multi_filter']['wallet']))
    & (df_fills['side'] == 'BUY')
    & (TAGS is None or df_fills['primary_tag'].isin(TAGS))
    & (df_fills["is_train"] == False)
    ].copy().reset_index(drop=True)

print(len(filter_fills))
# filter_fills = filter_fills[filter_fills['copyable_qty_5m_100'] >= 1].copy().reset_index(drop=True)
print(len(filter_fills))
filter_fills.head(2)

7837
7837

,wallet,condition_id,token_id,dt,side,position,quantity,price,usdc_amount,final_value_usdc,trade_pnl,copyable_pnl,token_winner,final_price,last_condition_trade_ts,tx_hash,num_fills,is_train,copyable_qty_5m_100,avail_copy_qty_5m_100,avail_copy_total_vol_5m_100,avail_copy_count_5m_100,copyable_qty_5m_095,copyable_qty_20m_100,avail_copy_qty_5m_095,avail_copy_qty_20m_100,end_date_iso,question,tags,primary_tag,winner_token_id,outcome,pnl,notional,copyable_qty_2x,copyable_pnl_2x,copyable_qty_0.5x,copyable_pnl_0.5x,copyable_pnl_20m_100,copyable_notional,roi,copyable_roi,bucket,is_copyable,copyable_pnl_exposure,copyable_pnl_20m_100_exposure,copyable_pnl_2x_exposure
0,0x04b3f873b003eba3774df1e5e47a370d27ee1b7e,0x0bd49c2df56df4c84d422b737ee42629c99e5cb7611cd378b79f9ba49366635b,65437567914217330399711424962196145895213871032517146984505166608450716988701,2026-07-31 07:04:17+00:00,BUY,28.17,28.17,0.71,20.00,28.17,8.17,8.17,True,1.00,2026-08-01 16:28:50+00:00,0xb429e50129f113ee86609c557c651904740c080fbbf1b4247d26fbeee88b4ac0,1,False,28.17,111.13,77.52,8.00,0.00,28.17,0.00,111.13,2026-08-01 00:00:00+00:00,Will the highest temperature in Taipei be 37°C on August 1?,"[Weather, Recurring, Hide From New, Daily Temperature, Taipei, Highest temperature]",Weather,65437567914217330399711424962196145895213871032517146984505166608450716988701,No,8.17,20.00,56.34,16.34,14.08,4.08,8.17,20.00,0.41,0.41,2026-07-31 07:05:00+00:00,True,20.00,20.00,40.00
1,0x04b3f873b003eba3774df1e5e47a370d27ee1b7e,0x06cfef5f6a2c1a17936819190c93ec16e0d5f0a2b718798bd3bd98e1a1fe81a8,14043844842954732214064839517330415540711824618648327882454904305560779275891,2026-08-03 05:22:51+00:00,BUY,38.70,38.70,0.52,20.00,0.00,-20.00,0.00,False,0.00,2026-08-03 15:11:47+00:00,0x7fc5db12b23970245d4e6a12104a4972500212df98f95a6047085de0c938c87e,2,False,-0.00,-0.00,0.00,0.00,-0.00,7.00,-0.00,7.00,2026-08-03 00:00:00+00:00,Will the highest temperature in Beijing be 35°C on August 3?,"[Weather, Recurring, Hide From New, Daily Temperature, Beijing, Highest temperature]",Weather,107848287102469510067330317349958205267283260960644358716420189174727956411263,Yes,-20.00,20.00,0.00,-0.00,0.00,-0.00,-3.62,-0.00,-1.00,NaN,2026-08-03 05:25:00+00:00,False,NaN,3.62,0.00

In [412]:
pd.set_option('display.max_colwidth', 100)
pd.set_option('display.max_rows', 1000)

In [413]:
# filter_fills['copyable_pnl_20m_100'].sum()

In [414]:
filter_fills["bucket"] = filter_fills["dt"].dt.floor("5min")

MAX_EXPOSURE = 100000

df = filter_fills.copy()

# scale each copyable variant to the per-fill MAX_EXPOSURE capital budget
for c in COPYABLE_PNL_COLS:
    exp_col = f"{c}_exposure"
    scale = np.minimum(1, MAX_EXPOSURE / df[exp_col].replace(0, np.nan))
    df[f"scaled_{c}"] = df[c] * scale
    df[f"scaled_{exp_col}"] = df[exp_col] * scale

df.head(1)

,wallet,condition_id,token_id,dt,side,position,quantity,price,usdc_amount,final_value_usdc,trade_pnl,copyable_pnl,token_winner,final_price,last_condition_trade_ts,tx_hash,num_fills,is_train,copyable_qty_5m_100,avail_copy_qty_5m_100,avail_copy_total_vol_5m_100,avail_copy_count_5m_100,copyable_qty_5m_095,copyable_qty_20m_100,avail_copy_qty_5m_095,avail_copy_qty_20m_100,end_date_iso,question,tags,primary_tag,winner_token_id,outcome,pnl,notional,copyable_qty_2x,copyable_pnl_2x,copyable_qty_0.5x,copyable_pnl_0.5x,copyable_pnl_20m_100,copyable_notional,roi,copyable_roi,bucket,is_copyable,copyable_pnl_exposure,copyable_pnl_20m_100_exposure,copyable_pnl_2x_exposure,scaled_copyable_pnl,scaled_copyable_pnl_exposure,scaled_copyable_pnl_20m_100,scaled_copyable_pnl_20m_100_exposure,scaled_copyable_pnl_2x,scaled_copyable_pnl_2x_exposure
0,0x04b3f873b003eba3774df1e5e47a370d27ee1b7e,0x0bd49c2df56df4c84d422b737ee42629c99e5cb7611cd378b79f9ba49366635b,65437567914217330399711424962196145895213871032517146984505166608450716988701,2026-07-31 07:04:17+00:00,BUY,28.17,28.17,0.71,20.00,28.17,8.17,8.17,True,1.00,2026-08-01 16:28:50+00:00,0xb429e50129f113ee86609c557c651904740c080fbbf1b4247d26fbeee88b4ac0,1,False,28.17,111.13,77.52,8.00,0.00,28.17,0.00,111.13,2026-08-01 00:00:00+00:00,Will the highest temperature in Taipei be 37°C on August 1?,"[Weather, Recurring, Hide From New, Daily Temperature, Taipei, Highest temperature]",Weather,65437567914217330399711424962196145895213871032517146984505166608450716988701,No,8.17,20.00,56.34,16.34,14.08,4.08,8.17,20.00,0.41,0.41,2026-07-31 07:00:00+00:00,True,20.00,20.00,40.00,8.17,20.00,8.17,20.00,16.34,40.00

In [415]:
# ── exposure + PnL over time, per copyable variant ────────────────────────────
agg_dict = {"wallet_pnl": ("trade_pnl", "sum")}
agg_dict.update({f"scaled_{c}": (f"scaled_{c}", "sum") for c in COPYABLE_PNL_COLS})
agg_dict.update({f"scaled_{c}_exposure": (f"scaled_{c}_exposure", "sum") for c in COPYABLE_PNL_COLS})
df_plot = df.groupby("end_date_iso").agg(**agg_dict).reset_index()

df.sort_values("bucket", inplace=True)
df["wallet_pnl_cumsum"] = df["trade_pnl"].cumsum()
for c in COPYABLE_PNL_COLS:
    df[f"scaled_{c}_cumsum"] = df[f"scaled_{c}"].cumsum()

# exposure per variant: fills add exposure at buy time; positions resolve at
# EOD of end_date_iso (+1 day), releasing the exposure (negative delta).
variant_exposure = []
for c in COPYABLE_PNL_COLS:
    exp_col = f"scaled_{c}_exposure"

    resolution = df_plot[["end_date_iso", exp_col]].rename(columns={exp_col: "exposure_delta"})
    resolution["dt"] = pd.to_datetime(resolution["end_date_iso"]) + pd.Timedelta(days=1)
    resolution["exposure_delta"] = -resolution["exposure_delta"]
    resolution["variant"] = c

    buy = df[["bucket", exp_col]].rename(columns={"bucket": "dt", exp_col: "exposure_delta"})
    buy["variant"] = c

    variant_exposure.append(
        pd.concat(
            [resolution[["dt", "variant", "exposure_delta"]], buy[["dt", "variant", "exposure_delta"]]],
            ignore_index=True,
        )
    )

df_exposure = pd.concat(variant_exposure, ignore_index=True)
df_exposure.sort_values("dt", inplace=True)
df_exposure["exposure"] = df_exposure.groupby("variant")["exposure_delta"].cumsum()

import plotly.graph_objects as go

fig = go.Figure()

fig.add_trace(go.Scatter(
    x=df["bucket"],
    y=df["wallet_pnl_cumsum"],
    mode="lines",
    name="wallet_pnl",
))

for c in COPYABLE_PNL_COLS:
    fig.add_trace(go.Scatter(
        x=df["bucket"],
        y=df[f"scaled_{c}_cumsum"],
        mode="lines",
        name=f"scaled_{c}",
        line=dict(dash="dash"),
    ))

for c in COPYABLE_PNL_COLS:
    exp_df = df_exposure[df_exposure["variant"] == c]
    fig.add_trace(go.Scatter(
        x=exp_df["dt"],
        y=exp_df["exposure"],
        mode="lines",
        name=f"exposure ({c})",
        line=dict(dash="dot"),
    ))

fig.show()

In [416]:
df_fills[(
    (df_fills['is_train'] == False)
    & (df_fills['wallet'].isin(wallet_set))
    & (df_fills['side'] == 'BUY')
          )].groupby(['primary_tag', 'side']).agg(
    copyable_pnl=('copyable_pnl', 'sum'),
    total_copyable_qty=('copyable_qty_5m_100', 'sum'),
    trade_pnl=('trade_pnl', 'sum'),
    trades=('condition_id', 'count'),
    condition_count=('condition_id', 'nunique'),
    wallets=('wallet', lambda x: x.nunique()),
).sort_values('copyable_pnl', key=abs, ascending=False).reset_index().head(10)

,primary_tag,side,copyable_pnl,total_copyable_qty,trade_pnl,trades,condition_count,wallets
0,Weather,BUY,2889.89,94088.18,28950.20,7837,2316,14

In [417]:
from polymarket_analysis.visualization.wallet_plots import (
    plot_wallet_selection_pnl,
    plot_wallet_individual_pnl,
)

if PLOT_WALLET_PNL:
    # Plot the copyable sharpe terciles in place of the combined copyable_group
    plot_cohorts = {k: v for k, v in wallet_cohorts.items() if k != 'copyable_group'}

    # Cohort aggregate PnL — training period
    fig_train = plot_wallet_selection_pnl(
        df_fills,
        plot_cohorts,
        split_date=TRAIN_END,
        period="train",
        title="Wallet selection cohorts — cohort cumulative PnL (training period, unlimited copyable PnL + exposure)",
        pnl_cols=COPYABLE_PNL_COLS,
    )
    fig_train.show(renderer="browser")

    # Cohort aggregate PnL — test period (starts from 0)
    fig_test = plot_wallet_selection_pnl(
        df_fills,
        plot_cohorts,
        split_date=TRAIN_END,
        period="test",
        title="Wallet selection cohorts — cohort cumulative PnL (test period, unlimited copyable PnL + exposure)",
        pnl_cols=COPYABLE_PNL_COLS,
    )
    fig_test.show(renderer="browser")

    # # Individual wallet lines (train + test) with split vline and labels
    # fig_ind = plot_wallet_individual_pnl(
    #     df_fills,
    #     wallet_cohorts,
    #     split_date=split_dt,
    #     top_n_individual=TOP_N_INDIVIDUAL,
    #     title="Individual wallet cumulative PnL (train + test, resets at split)",
    # )
    # fig_ind.show(renderer="browser")

In [418]:
wals = pd.read_parquet('/Users/vobornij/projects/polymarket/data/trade_signals_workspace_v2/selected_wallets_v2.parquet')

In [419]:
wals[wals['wallet_group'] == 'copyable'].sort_values('wallet_quality', ascending=False).head(20)

,wallet,num_buckets,trade_count,total_notional,total_pnl,copyable_pnl,num_markets,median_dt,median_roi,average_roi,max_drawdown,max_copyable_drawdown,buy_pnl,buy_quantity,sell_pnl,sell_quantity,buy_notional,sell_notional,buy_copyable_quantity,buy_copyable_pnl,sell_copyable_quantity,sell_copyable_pnl,buy_roi,sell_roi,buy_copyable_notional,top5_pnl_pct,top10_pnl_pct,worst5_pnl_pct,positive_bucket_share,top_market_pnl_pct,top_market_abs_pnl_pct,market_pnl_hhi,pnl_volatility,estimated_sharpe,estimated_buy_sharpe,estimated_copyable_buy_sharpe,copyable_pnl_similarity,copyable_pnl_similarity_profit,copyable_pnl_similarity_loss,copyable_pnl_similarity_20m_100,copyable_pnl_similarity_profit_20m_100,copyable_pnl_similarity_loss_20m_100,max_drawdown_to_pnl,max_copyable_drawdown_to_copyable_pnl,return,copyable_pnl_factor,copyable_roi,buy_copyable_roi,buy_copyable_factor,sample_mult,downside_tail,predictability_score,predicting_final_score,copyable_efficiency,copyable_dd_ratio,copyable_score,final_score,wallet_quality,wallet_group
0,0xb7b9ce6c3db2ebf1dcd12db8ae64cfb2e9f01e0e,291,508,12478.02,4302.98,2432.80,89,2026-07-06 09:55:00+00:00,0.16,0.36,1162.91,687.19,4302.98,36053.41,0.00,0.00,12478.02,0.00,13708.10,2432.80,0.00,0.00,0.34,0.00,4744.35,0.44,0.68,-0.25,0.49,0.26,0.11,0.03,1.53,5.30,5.30,5.33,0.82,0.82,0.80,0.86,0.84,0.95,0.27,0.28,0.34,0.57,0.20,0.51,0.57,0.75,0.25,-1.58,-1.58,0.19,0.28,5.64,1.31,1.31,copyable
1,0x1f127e31717c8d74232fc4d5693e9236b49c9424,623,669,19033.34,2706.51,1567.73,418,2026-05-24 12:20:00+00:00,0.07,0.27,227.07,57.69,2706.51,35919.93,0.00,0.00,19033.34,0.00,11599.22,1567.73,0.00,0.00,0.14,0.00,6146.22,0.37,0.50,-0.11,0.52,0.17,0.05,0.01,0.52,7.37,7.37,8.34,0.67,0.74,0.52,0.85,0.85,0.85,0.08,0.04,0.14,0.58,0.15,0.26,0.58,0.85,0.11,-0.60,-0.60,0.08,0.04,2.97,0.83,0.83,copyable
2,0x331d8ec8d8931b479007f4931a6b25b0b6628846,1012,1443,18955.64,8490.54,1737.20,528,2026-07-03 05:32:30+00:00,-1.00,0.72,430.16,268.77,8490.54,95115.57,0.00,0.00,18955.64,0.00,18458.30,1737.20,0.00,0.00,0.45,0.00,3678.57,0.21,0.32,-0.08,0.35,0.06,0.03,0.01,0.57,12.99,12.99,9.18,0.54,0.54,0.58,0.79,0.78,0.84,0.05,0.15,0.45,0.20,0.15,0.47,0.20,0.91,0.08,-0.80,-0.80,0.09,0.15,2.67,0.59,0.59,copyable
3,0x04b3f873b003eba3774df1e5e47a370d27ee1b7e,2998,3044,38445.63,4184.53,1409.42,2730,2026-06-07 04:57:30+00:00,0.20,0.12,282.55,164.83,4184.53,66661.71,0.00,0.00,38445.63,0.00,22238.97,1409.42,0.00,0.00,0.11,0.00,12825.82,0.20,0.31,-0.03,0.72,0.07,0.01,0.00,0.24,10.94,10.94,8.46,0.59,0.56,0.65,0.69,0.65,0.81,0.07,0.12,0.11,0.34,0.04,0.11,0.34,1.00,0.03,-0.09,-0.09,0.04,0.12,1.29,0.47,0.47,copyable
4,0xa2eded4da718244771d4f2b7810da45533de9d98,3472,4010,36128.68,3880.07,1133.73,2292,2026-06-13 08:07:30+00:00,0.19,0.07,165.99,147.33,3880.07,65472.99,0.00,0.00,36128.68,0.00,33425.74,1133.73,0.00,0.00,0.11,0.00,18444.68,0.18,0.28,-0.04,0.70,0.05,0.01,0.00,0.18,10.61,10.61,5.54,0.70,0.65,0.81,0.90,0.89,0.93,0.04,0.13,0.11,0.29,0.02,0.06,0.29,1.00,0.04,-0.03,-0.03,0.03,0.13,1.06,0.41,0.41,copyable
5,0x5fe79a73af0a8ad6a83d89256026b14f35981ea9,640,1488,55269.43,9186.69,4424.49,349,2026-06-21 12:22:30+00:00,0.09,0.48,1709.00,579.55,9186.69,144194.65,0.00,0.00,55269.43,0.00,36076.71,4424.49,0.00,0.00,0.17,0.00,13828.11,0.49,0.74,-0.28,0.82,0.24,0.10,0.03,1.56,4.74,4.74,4.90,0.72,0.76,0.56,0.77,0.78,0.71,0.19,0.13,0.17,0.48,0.23,0.32,0.48,0.85,0.28,-1.39,-1.39,0.08,0.13,2.84,0.30,0.30,copyable
6,0x2753b2db276ffdddc2b26155815f509fe349e28a,1217,1483,39740.89,2975.95,1078.61,840,2026-06-08 05:55:00+00:00,0.08,0.09,358.27,301.52,2975.95,57655.92,0.00,0.00,39740.89,0.00,21000.28,1078.61,0.00,0.00,0.07,0.00,14475.01,0.20,0.32,-0.21,0.78,0.05,0.02,0.00,0.58,8.12,8.12,5.28,0.82,0.81,0.83,0.91,0.88,0.95,0.12,0.28,0.07,0.36,0.03,0.07,0.36,0.93,0.21,-0.48,-0.48,0.03,0.28,0.94,0.09,0.09,copyable
7,0xbd71233ab7a25bc420929cd67476219762f31281,1660,2466,19953.73,3014.98,1210.01,959,2026-06-29 08:12:30+00:00,-1.00,0.20,624.46,608.07,3014.98,67462.51,0.00,0.00,19953.73,0.00,34502.15,1210.01,0.00,0.00,0.15,0.00,10204.88,0.17,0.31,-0.24,0.42,0.05,0.01,0.00,0.57,8.75,8.75,4.65,0.77,0.73,0.83,0.91,0.88,0.96,0.21,0.50,0.15,0.40,0.08,0.12,0.40,0.98,0.24,-1.02,-1.02,0.06,0.50,1.73,0.08,0.08,copyable
8,0x0af29cc14fb231218c8d005685ac3db427a1ce86,476,767,22703.75,3438.23,1280.25,90,2026-05-11 02:52:30+00:00,0.08,0.51,897.80,324.19,3438.23,40615.22,0.00,0.00,22703.75,0.00,11721.63,1280.25,0.00,0.00,0.15,0.00,6552.35,0.57,0.84,-0.35,0.61,0.27,0.10,0.04,1.13,5.78,5.78,4.07,0.71,0.76,0.59,0.83,0.86,0.77,0.26,0.25,0.15,0.37,0.19,0.20,0.37,0.81,0.35,-1.29,-1.29,0.06,0.25,1.95,0.00,0.00,copyable
9,0xed541ad118dea9103306043869e83344cac44967,1864,2700,49136.66,5838.10,1119.92,842,2026-06-19 09:00:00+00:00,0.00,0.15,503.71,257.94,5838.10,104313.37,0.00,0.00,49136.66,0.00,16633.71,1119.92,0.00,0.00,0.12,0.00,7835.28,0.14,0.24,-0.10,0.52,0.05,0.02,0.00,0.36,9.76,9.76,5.23,0.60,0.59,0.63,0.76,0.76,0.77,0.09,0.23,0.12,0.19,0.03,0.14,0.19,0.99,0.10,-0.49,-0.49,0.02,0.23,0.66,-0.03,-0.03,copyable
10,0xb9012e0d9b60d3920286309328b935cdfa609fc4,1166,3594,435015.92,26153.05,2300.81,983,2026-06-03 13:20:00+00:00,0.01,0.84,990.00,190.58,26153.05,485923.94,0.00,0.00,435015.92,0.00,39808.71,2300.81,0.00,0.00,0.06,0.00,35638.13,0.15,0.23,-0.07,0.94,0.05,0.05,0.01,0.67,15.28,15.28,7.62,0.46,0.48,0.32,0.47,0.50,0.41,0.04,0.08,0.06,0.09,0.07,0.06,0.09,0.93,0.07,-0.24,-0.24,0.01,0.08,0.28,-0.03,-0.03,copyable
11,0x919698b19427cbe6945b0dc823f2d9e126a4d934,5080,7284,225292.54,17933.89,3555.89,1973,2026-06-24 05:02:30+00:00,-1.00,0.17,652.43,341.22,17933.89,399845.83,0.00,0.00,225292.54,0.00,60115.39,3555.89,0.00,0.00,0.08,0.00,33871.93,0.09,0.15,-0.07,0.41,0.03,0.01,0.00,0.34,15.98,15.98,8.82,0.57,0.57,0.57,0.71,0.68,0.77,0.04,0.10,0.08,0.20,0.03,0.10,0.20,1.00,0.07,-0.54,-0.54,0.02,0.10,0.61,-0.08,-0.08,copyable
12,0x6011655c4afb76f36dd1b08a137a1ba73466b31e,1653,2075,548445.70,58441.07,4138.46,1619,2026-06-26 17:55:00+00:00,0.05,0.15,2931.26,890.54,58441.07,616272.68,0.00,0.00,548445.70,0.00,47531.75,4138.46,0.00,0.00,0.11,0.00,42300.40,0.06,0.11,-0.08,0.99,0.01,0.02,0.00,0.77,24.16,24.16,7.96,0.66,0.54,0.94,0.64,0.54,0.97,0.05,0.22,0.11,0.07,0.01,0.10,0.07,0.98,0.08,-0.30,-0.30,0.01,0.22,0.11,-0.13,-0.13,copyable
13,0x0f607897e7a3e05ae15e7a99e57856454d17026a,6043,6629,96474.50,2325.67,1000.20,2615,2026-05-06 20:15:00+00:00,0.12,0.05,1093.57,243.22,2325.67,130225.02,0.00,0.00,96474.50,0.00,20718.87,1000.20,0.00,0.00,0.02,0.00,15349.14,0.22,0.39,-0.27,0.76,0.11,0.01,0.00,0.33,6.92,6.92,9.26,0.53,0.59,0.47,0.70,0.74,0.68,0.47,0.24,0.02,0.43,0.02,0.07,0.43,1.00,0.27,-0.72,-0.72,0.01,0.24,0.61,-0.18,-0.18,copyable
14,0x41f623e0baae41e385875a3759c474cf0622828e,2659,5423,92315.97,21218.43,4867.32,756,2026-06-13 12:50:00+00:00,-1.00,0.22,1498.24,512.44,21218.43,394481.44,0.00,0.00,92315.97,0.00,65016.50,4867.32,0.00,0.00,0.23,0.00,15215.07,0.26,0.42,-0.07,0.29,0.11,0.03,0.01,1.09,8.09,8.09,5.62,0.57,0.57,0.57,0.80,0.80,0.77,0.07,0.11,0.23,0.23,0.05,0.32,0.23,1.00,0.07,-1.49,-1.49,0.05,0.11,1.58,-0.26,-0.26,copyable
15,0x85c06787486a90e05ba1df96c034ef95c8cce01d,2026,3947,32556.78,6647.43,2000.22,871,2026-06-02 12:57:30+00:00,-1.00,0.11,2259.80,464.21,6647.43,209871.25,0.00,0.00,32556.78,0.00,32756.86,2000.22,0.00,0.00,0.20,0.00,5081.49,0.39,0.65,-0.10,0.20,0.19,0.03,0.01,0.83,5.72,5.72,4.27,0.59,0.59,0.60,0.83,0.83,0.83,0.34,0.23,0.20,0.30,0.03,0.39,0.30,1.00,0.10,-1.68,-1.68,0.06,0.23,1.76,-0.30,-0.30,copyable
16,0xa89518aca5a633a79ad1e9737209c9689f83faac,753,1589,51624.18,20714.19,2210.17,329,2026-06-15 14:50:00+00:00,-1.00,1.45,270.43,116.60,20714.19,183842.30,0.00,0.00,51624.18,0.00,14794.29,2210.17,0.00,0.00,0.40,0.00,4154.34,0.46,0.73,-0.02,0.47,0.11,0.10,0.05,1.76,5.99,5.99,4.60,0.41,0.41,0.79,0.60,0.60,0.88,0.01,0.05,0.40,0.11,0.15,0.53,0.11,0.87,0.02,-1.68,-1.68,0.04,0.05,1.39,-0.46,-0.46,copyable
17,0x8fb431f5057112cfdb0e7f566b4b687cb69cb9ed,1333,3257,40787.36,10528.84,2856.17,364,2026-05-07 14:10:00+00:00,-1.00,0.21,3588.27,1056.08,10528.84,218785.50,0.00,0.00,40787.36,0.00,50176.32,2856.17,0.00,0.00,0.26,0.00,9354.18,0.53,0.76,-0.16,0.28,0.26,0.07,0.02,1.35,5.84,5.84,5.00,0.56,0.53,0.69,0.81,0.80,0.87,0.34,0.37,0.26,0.27,0.06,0.31,0.27,0.95,0.16,-2.05,-2.05,0.07,0.37,1.85,-0.49,-0.49,copyable
18,0x1cd2da1d25c07776dcc6bfee2c5589da2d98c304,653,1041,13295.70,6569.68,1054.31,287,2026-07-09 02:35:00+00:00,-1.00,1.64,803.64,109.11,6569.68,88962.70,0.00,0.00,13295.70,0.00,3782.58,1054.31,0.00,0.00,0.49,0.00,565.32,0.58,0.89,-0.22,0.28,0.31,0.12,0.03,2.53,9.41,9.41,4.51,0.29,0.31,0.18,0.55,0.59,0.27,0.12,0.10,0.49,0.16,0.26,1.86,0.16,0.85,0.22,-2.70,-2.70,0.08,0.10,2.51,-0.61,-0.61,copyable
19,0xc00837a29d51e8cb51a8ce6c1062f512d9f66adf,178,532,11884.65,7408.16,1403.83,32,2026-06-30 04:25:00+00:00,-1.00,-0.27,796.02,59.54,7408.16,47474.55,0.00,0.00,11884.65,0.00,5070.77,1403.83,0.00,0.00,0.62,0.00,1269.40,0.60,0.93,-0.15,0.36,0.46,0.26,0.12,4.13,10.17,10.17,9.18,0.32,0.33,0.32,0.36,0.35,0.40,0.11,0.04,0.62,0.19,-0.05,1.11,0.19,0.68,0.15,-3.27,-3.27,0.12,0.04,2.92,-0.79,-0.79,copyable