# Wallet Strategy Selection

Unified selection stage: runs **all wallet-selection methods** and saves each
as a named `WalletSelectionStrategy` artifact in the workspace.  The backtest
stage loads these artifacts directly — no strategy logic is re-built there.

## Methods included
| id suffix | description |
|-----------|-------------|
| `skill_sweep` → `quality_core` | top-N by best skill metric (grid-searched on train-a→train-b) |
| `cohort_early_entry` | wallets that enter markets early |
| `cohort_smooth_pnl` | wallets with high PnL relative to volatility |
| `volatility` | volatility-filtered wallets (from the profitable_wallet_analysis path) |

Each method produces **three trigger variants**:
- `score_threshold`  — composite signal score ≥ calibrated threshold (Kelly sizing)
- `all_open_buys`    — every open-buy event (fixed stake baseline)
- `copy_triggers`    — every trade (open/add/close/reduce), tight slippage

In [1]:
%load_ext autoreload
%autoreload 2

import datetime
from pathlib import Path

import numpy as np
import pandas as pd
import pyarrow.dataset as ds

np.set_printoptions(precision=4, suppress=True)
pd.options.display.float_format = '{:.2f}'.format

## Configuration

In [2]:
# ── configuration ─────────────────────────────────────────────────────────────
RECENCY_DAYS     = 90

PRICE_BUCKET_BINS   = [0.0, 0.1, 0.25, 0.4, 0.6, 0.75, 0.9, 1.0]
PRICE_BUCKET_LABELS = [
    "0.00-0.10", "0.10-0.25", "0.25-0.40", "0.40-0.60",
    "0.60-0.75", "0.75-0.90", "0.90-1.00",
]

TRADES_DIR    = Path("../../data/polygon_trades_processed")
WORKSPACE_DIR = Path("../../data/trade_signals_workspace_v2")
WORKSPACE_DIR.mkdir(parents=True, exist_ok=True)

dataset = ds.dataset(TRADES_DIR, format="parquet")
DATASET_COLUMNS        = set(dataset.schema.names)
TRIGGER_TX_HASH_COLUMN = (
    "transaction_hash" if "transaction_hash" in DATASET_COLUMNS
    else ("tx_hash" if "tx_hash" in DATASET_COLUMNS else None)
)

METRICS_A_PATH          = WORKSPACE_DIR / "wallet_metrics_train_a.parquet"
METRICS_B_PATH          = WORKSPACE_DIR / "wallet_metrics_train_b.parquet"
METRICS_FULL_PATH       = WORKSPACE_DIR / "wallet_metrics_full_train.parquet"
METRICS_TEST_PATH       = WORKSPACE_DIR / "wallet_metrics_test.parquet"
CALIBRATION_SIGNALS_PATH = WORKSPACE_DIR / "signal_events_train_b.parquet"
TEST_SIGNALS_PATH       = WORKSPACE_DIR / "signal_events_test.parquet"

## Derive train/test dates from data

In [3]:
# ── derive train/test boundary from is_train flag ───────────────────────────
_sample = pd.read_parquet(sorted(TRADES_DIR.glob("*.parquet"))[0], columns=["dt", "is_train"])
_sample["dt"] = pd.to_datetime(_sample["dt"], utc=True)
END_DATE_TRAIN   = _sample.loc[_sample["is_train"], "dt"].max().date()
TRAIN_START_DATE = _sample.loc[_sample["is_train"], "dt"].min().date()
# Split train_a / train_b at the trade-count median of training rows so that
# both halves always contain roughly equal numbers of trades even when the
# data is unevenly distributed over calendar time.
_train_rows = _sample.loc[_sample["is_train"]].sort_values("dt")
TRAIN_A_END_DATE = _train_rows["dt"].quantile(0.5, interpolation="nearest").date()
del _sample, _train_rows
print(f"END_DATE_TRAIN={END_DATE_TRAIN}  TRAIN_A_END_DATE={TRAIN_A_END_DATE}")

END_DATE_TRAIN=2026-02-15  TRAIN_A_END_DATE=2026-01-26

## Compute / load wallet skill metrics

In [4]:
from polymarket_analysis.wallet_selection.metrics import compute_wallet_skill_workspace

if all(p.exists() for p in [METRICS_A_PATH, METRICS_B_PATH, METRICS_FULL_PATH, METRICS_TEST_PATH]):
    train_a_metrics    = pd.read_parquet(METRICS_A_PATH)
    train_b_metrics    = pd.read_parquet(METRICS_B_PATH)
    full_train_metrics = pd.read_parquet(METRICS_FULL_PATH)
    test_metrics       = pd.read_parquet(METRICS_TEST_PATH)
else:
    train_a_metrics, train_b_metrics, full_train_metrics, test_metrics = (
        compute_wallet_skill_workspace(
            dataset,
            end_date_train=END_DATE_TRAIN,
            train_a_end_date=TRAIN_A_END_DATE,
            recency_days=RECENCY_DAYS,
        )
    )
    train_a_metrics.to_parquet(METRICS_A_PATH, index=False)
    train_b_metrics.to_parquet(METRICS_B_PATH, index=False)
    full_train_metrics.to_parquet(METRICS_FULL_PATH, index=False)
    test_metrics.to_parquet(METRICS_TEST_PATH, index=False)

pd.Series({
    "train_a_wallets":    len(train_a_metrics),
    "train_b_wallets":    len(train_b_metrics),
    "full_train_wallets": len(full_train_metrics),
    "test_wallets":       len(test_metrics),
}).to_frame("value")

                    value
train_a_wallets     10964
train_b_wallets     10964
full_train_wallets  10964
test_wallets        10964

## Cohort selection sweep (skill path)

Grid-search over metrics × top-N using train-a → train-b persistence.

In [5]:
from polymarket_analysis.wallet_selection.selector import (
    CANDIDATE_METRICS,
    cohort_selection_sweep,
    select_wallets,
)

cohort_sweep = cohort_selection_sweep(train_a_metrics, train_b_metrics, CANDIDATE_METRICS)
cohort_sweep.sort_values(
    ["train_b_avg_copy_roi_capped", "train_b_weighted_prob_edge"], ascending=False
).head(20)

,metric,top_n,wallets_found_in_train_b,train_b_open_buy_trades,train_b_weighted_prob_edge,train_b_avg_prob_edge,train_b_avg_copy_roi_capped,train_b_total_copy_pnl_usdc,train_b_hit_rate
10,avg_copy_roi_capped,50,50,1813,0.07,0.12,1.52,103284.02,0.42
11,avg_copy_roi_capped,100,100,2695,0.07,0.10,1.12,143225.93,0.42
0,prob_edge_shrunk,50,50,4204,0.01,0.12,0.93,115130.45,0.47
22,roi_sharpe,200,200,3250,0.01,0.07,0.85,101101.91,0.70
12,avg_copy_roi_capped,200,200,5272,0.06,0.11,0.82,248959.70,0.48
1,prob_edge_shrunk,100,100,5418,0.03,0.11,0.78,201409.43,0.51
13,avg_copy_roi_capped,300,300,7046,0.06,0.07,0.76,384078.84,0.50
23,roi_sharpe,300,300,4467,0.01,0.07,0.70,117444.18,0.70
6,weighted_prob_edge_shrunk,100,100,2399,0.06,0.09,0.68,256835.63,0.47
21,roi_sharpe,100,100,2473,0.01,0.03,0.66,73063.49,0.78
5,weighted_prob_edge_shrunk,50,50,1768,0.01,0.08,0.58,50491.82,0.48
2,prob_edge_shrunk,200,200,8374,0.03,0.09,0.57,323284.86,0.53
24,roi_sharpe,500,500,6393,0.01,0.07,0.56,198368.62,0.66
14,avg_copy_roi_capped,500,500,11623,0.04,0.06,0.55,655064.68,0.52
18,edge_sharpe,300,300,6229,0.01,0.07,0.55,189776.29,0.72
7,weighted_prob_edge_shrunk,200,200,3199,0.00,0.07,0.53,14502.35,0.49
17,edge_sharpe,200,200,3974,0.01,0.07,0.43,139834.11,0.80
8,weighted_prob_edge_shrunk,300,300,4144,0.03,0.06,0.42,207341.21,0.50
3,prob_edge_shrunk,300,300,14108,0.01,0.07,0.39,358793.35,0.50
19,edge_sharpe,500,500,9959,0.01,0.06,0.39,178385.09,0.75

In [6]:
# pick best metric / top-N
best_row = cohort_sweep.sort_values(
    ["train_b_avg_copy_roi_capped", "train_b_weighted_prob_edge", "train_b_open_buy_trades"],
    ascending=[False, False, False],
).iloc[0]
BEST_SELECTION_METRIC = best_row["metric"]
BEST_TOP_N            = int(best_row["top_n"])
{"best_metric": BEST_SELECTION_METRIC, "best_top_n": BEST_TOP_N}

{'best_metric': 'avg_copy_roi_capped', 'best_top_n': 50}

## Select wallets (skill path) + build cohorts

In [7]:
selected_wallets = select_wallets(full_train_metrics, BEST_SELECTION_METRIC, BEST_TOP_N)
selected_wallets.to_parquet(WORKSPACE_DIR / "selected_wallets_v2.parquet", index=False)
selected_wallets[[
    "wallet", "open_buy_trades", "distinct_markets",
    "recent_open_buy_trades", BEST_SELECTION_METRIC, "wallet_quality"
]].head(15)

,wallet,open_buy_trades,distinct_markets,recent_open_buy_trades,avg_copy_roi_capped,wallet_quality
0,0x4d7fad0c5944fc24d4a67110f8e31abd5f559485,67,67,67,3.63,1.00
1,0xf94fe1799944b93b3b831b6f9f4f4aee1cdd78d7,27,27,27,2.73,0.98
2,0xbb0bd109b9f0c2a59b8819c466f064cf65ab3790,456,435,456,2.71,0.96
3,0x54a2c4cfc4332d831acc3f5a860d6540982c1d43,275,264,275,2.47,0.94
4,0x5ad5c4608c4661361b91c92e1091d2c5b43c37b9,464,451,464,2.41,0.92
5,0x1838cca016850ac7185a9b149fe7d0bd2d6629b4,851,221,851,2.32,0.90
6,0x82307f44c9405e73dc1cff466073dcc505535121,409,386,409,2.28,0.88
7,0x91b859901e1292380ef5da3c4f81b29738e551cf,32,31,32,2.18,0.86
8,0x456d7e1295b785ba37725a0db29436b056b11fe1,22,22,22,2.11,0.84
9,0x4266e8adab19c1c989547d7a4b4565a0336ba06d,38,34,38,2.06,0.82
10,0x71cd52a9bf9121cf8376ba13999468f5d659912d,82,79,82,1.99,0.80
11,0x9bd4f28b5af1fcea475fefe05b29634ac1ac35b5,156,148,156,1.94,0.78
12,0x81209ebf10e9cc4aa000003974cc761bb623057d,44,42,44,1.79,0.76
13,0x411edae2f0d05f932d0a976efdde5edd6b43ea8b,95,84,95,1.73,0.74
14,0x55ac83b5a4837d868fd058c9793d53ab73c19955,174,161,174,1.73,0.72

## Build wallet profiles and signal events

In [8]:
from polymarket_analysis.signal.builder import (
    build_wallet_profiles,
    build_signal_events,
)

selected_wallet_profiles = build_wallet_profiles(
    dataset, selected_wallets, period="full_train",
    end_date_train=END_DATE_TRAIN, train_a_end_date=TRAIN_A_END_DATE
)
selected_wallet_profiles.to_parquet(
    WORKSPACE_DIR / "selected_wallet_profiles_v2.parquet", index=False
)

# Force-regenerate signal caches: the schema now includes all event types
# (open_buy, add_buy, close_sell, reduce_sell) plus copy_price/copy_market_key/
# copy_token_winner columns. Delete stale parquets so they are always rebuilt.
CALIBRATION_SIGNALS_PATH.unlink(missing_ok=True)
TEST_SIGNALS_PATH.unlink(missing_ok=True)

_, train_b_signals = build_signal_events(
    dataset, selected_wallet_profiles, period="train_b",
    end_date_train=END_DATE_TRAIN, train_a_end_date=TRAIN_A_END_DATE,
    price_bucket_bins=PRICE_BUCKET_BINS, price_bucket_labels=PRICE_BUCKET_LABELS,
    tx_hash_column=TRIGGER_TX_HASH_COLUMN,
)
train_b_signals.to_parquet(CALIBRATION_SIGNALS_PATH, index=False)

_, test_signals = build_signal_events(
    dataset, selected_wallet_profiles, period="test",
    end_date_train=END_DATE_TRAIN, train_a_end_date=TRAIN_A_END_DATE,
    price_bucket_bins=PRICE_BUCKET_BINS, price_bucket_labels=PRICE_BUCKET_LABELS,
    tx_hash_column=TRIGGER_TX_HASH_COLUMN,
)
test_signals.to_parquet(TEST_SIGNALS_PATH, index=False)

print(f"train_b signals: {len(train_b_signals):,}  test signals: {len(test_signals):,}")
print(f"event types: {train_b_signals['event_type'].value_counts().to_dict()}")

train_b signals: 4,789  test signals: 3,943
event types: {'add_buy': 2032, 'reduce_sell': 1939, 'open_buy': 664, 'close_sell': 148, 'other': 6}

## Calibrate signal scoring on train-B

In [9]:
from polymarket_analysis.signal.scorer import (
    build_calibration_tables,
    apply_signal_score,
    select_signal_threshold,
)

# Calibration tables are built from open_buy events only — the scoring model
# is designed for open-buy conviction features. Non-open-buy rows get neutral
# defaults and will not be used to calibrate the scorer.
train_b_open_buys = train_b_signals[train_b_signals["event_type"] == "open_buy"].copy()

price_table, consensus_table, global_edge = build_calibration_tables(train_b_open_buys)
train_b_scored = apply_signal_score(train_b_open_buys, price_table, consensus_table)
SIGNAL_THRESHOLD = select_signal_threshold(train_b_scored)
print(f"Global edge: {global_edge:.4f}")
print(f"Selected signal threshold: {SIGNAL_THRESHOLD:.2f}")

# score distribution
score_deciles = (
    train_b_scored.assign(
        score_decile=lambda df: pd.qcut(df["signal_score"], q=10, labels=False, duplicates="drop")
    )
    .groupby("score_decile")
    .agg(
        count=("signal_score", "size"),
        avg_signal_score=("signal_score", "mean"),
        avg_copy_roi_capped=("copy_roi_capped", "mean"),
    )
    .reset_index()
)
score_deciles

Global edge: 0.2205
Selected signal threshold: 0.65

   score_decile  count  avg_signal_score  avg_copy_roi_capped
0             0     67              0.36                 1.18
1             1     68              0.46                 1.39
2             2     64              0.53                 0.69
3             3     67              0.61                 1.36
4             4     66              0.69                 2.33
5             5     66              0.74                 3.51
6             6     67              0.77                 2.32
7             7     67              0.82                 2.19
8             8     88              0.86                 0.97
9             9     44              0.90                 1.54

## Build wallet cohorts (skill path)

In [10]:
from polymarket_analysis.wallet_selection.selector import build_wallet_cohorts

wallet_cohorts = build_wallet_cohorts(
    full_train_metrics, train_b_open_buys, selected_wallets,
    top_n=BEST_TOP_N,
)
{name: len(df) for name, df in wallet_cohorts.items()}

{'quality_core': 50, 'early_entry': 13, 'smooth_pnl': 50}

## Volatility-based wallet selection (second method)

Loads the full training set, applies the volatility filter, and stores the
result as an additional `WalletSelectionStrategy`.  The volatility wallet set
is added to `wallet_cohorts` so the strategy factory handles it uniformly.

In [11]:
dft = pd.read_parquet(TRADES_DIR / "0.parquet")

In [12]:
from polymarket_analysis.wallet_selection.volatility import (
    compute_wallet_metrics,
    filter_wallets_by_volatility,
)

# Load full training trades for the volatility path
trade_files = sorted(TRADES_DIR.glob("*.parquet"))
df_train_vol = pd.concat([pd.read_parquet(f) for f in trade_files], ignore_index=True)
df_train_vol["dt"] = pd.to_datetime(df_train_vol["dt"], utc=True)

# Normalise grouped schema → canonical fill-level names
if "total_quantity" in df_train_vol.columns and "quantity" not in df_train_vol.columns:
    df_train_vol = df_train_vol.rename(columns={
        "total_quantity": "quantity",
        "avg_price": "price",
        "trade_value_usdc": "usdc_amount",
    })

df_train_vol["usdc_amount"]      = df_train_vol["usdc_amount"].astype(float)
df_train_vol["final_value_usdc"] = df_train_vol["final_value_usdc"].astype(float)
df_train_vol["quantity"]         = df_train_vol["quantity"].astype(float)

# PnL and notional per fill

df_train_vol["copyable_pnl"] = (
        df_train_vol["copyable_qty"] / df_train_vol["quantity"]
        * (df_train_vol["final_price"] - df_train_vol["price"])
        * np.where(df_train_vol["side"] == "BUY", 1, -1)
    )

df_train_vol["pnl"] = np.where(
    df_train_vol["side"] == "BUY",
    df_train_vol["final_value_usdc"] - df_train_vol["usdc_amount"],
    df_train_vol["usdc_amount"] - df_train_vol["final_value_usdc"],
)
df_train_vol["notional"] = np.where(
    df_train_vol["side"] == "BUY",
    df_train_vol["usdc_amount"],
    df_train_vol["quantity"] * (1 - df_train_vol["price"].astype(float)),
)
df_slice = df_train_vol[df_train_vol["is_train"]].copy()

wallet_vol_train, _ = compute_wallet_metrics(df_slice)
# del df_train_vol, df_slice

In [49]:
wallet_vol_train['copyable_pnl_factor'] = np.clip(wallet_vol_train['copyable_pnl'] / wallet_vol_train['total_pnl'], 0, 1.0)
wallet_vol_train['copyable_roi'] = wallet_vol_train['average_roi'] * wallet_vol_train['copyable_pnl_factor']
wallet_vol_train.sort_values('copyable_roi', ascending=False, inplace=True)
wallet_vol_train.reset_index(drop=True, inplace=True)
wallet_vol_train = wallet_vol_train[wallet_vol_train['copyable_roi'] > 0.05]
wallet_vol_train = wallet_vol_train[wallet_vol_train['top_market_pnl_pct'] < 0.3]

In [79]:
wallet_cohorts = {}

In [80]:
print(len(wallet_vol_train))
wallet_vol_train.head()

407

,wallet,pnl_volatility,num_buckets,num_markets,total_notional,total_pnl,copyable_pnl,top5_pnl_pct,top_market_pnl_pct,median_roi,average_roi,return,copyable_pnl_factor,copyable_roi
0,0x82307f44c9405e73dc1cff466073dcc505535121,9.46,488.00,386.00,40628.80,23369.47,10455.92,0.54,0.18,-1.00,4.93,0.58,0.45,2.21
1,0xede186f37ead91aa618cf8101db2bfe6b6c57dd1,5.59,49.00,33.00,9804.32,5952.92,5272.49,0.81,0.27,-1.00,1.30,0.61,0.89,1.15
2,0xfe0ad5ed4c912a46a4e41198e673bd371c384a63,24.85,138.00,40.00,96684.29,56567.43,22667.54,0.99,0.28,-1.00,2.64,0.59,0.40,1.06
3,0xde5830e0b75b31c466fc64aa2313a1e07e3f8610,2.12,13.00,11.00,473.49,791.49,417.97,0.76,0.24,1.78,1.66,1.67,0.53,0.88
4,0x8d5c3994aab4d5a04418d0f10394f3b398bab756,2.74,9.00,9.00,817.78,777.86,462.64,0.99,0.25,1.00,1.45,0.95,0.59,0.86

In [81]:
# filtered_wallets_vol = filter_wallets_by_volatility(
#     wallet_vol_train,
#     min_buckets=20,
#     max_top5_pnl_pct=.6,
#     max_top_market_pnl_pct=0.5,
# )

filtered_wallets_vol = wallet_vol_train.copy()

# filtered_wallets_vol = (
#     filtered_wallets_vol[
#         (filtered_wallets_vol['average_roi'] >= 0.04)
#         & (filtered_wallets_vol['copyable_pnl'] / filtered_wallets_vol['total_pnl'] >= 0.5)
# ].sort_values("pnl_volatility", ascending=True).head(100)
# )

print(f"Volatility-filtered wallets: {len(filtered_wallets_vol)}")

# Build wallet_quality based on total_pnl rank (higher = better)
filtered_wallets_vol = filtered_wallets_vol.copy().reset_index(drop=True)
filtered_wallets_vol["wallet_quality"] = filtered_wallets_vol["total_pnl"].rank(
    method="first", pct=True
)

# Add as additional cohort (uses only train-b signals for trigger calibration)
# We intersect with wallets that have signals to ensure coverage
vol_wallets_with_signals = set(train_b_signals["wallet"]).intersection(
    set(filtered_wallets_vol["wallet"])
)
wallet_cohorts["volatility"] = filtered_wallets_vol.copy().reset_index(drop=True)

# [
#     filtered_wallets_vol["wallet"].isin(vol_wallets_with_signals)
# ][["wallet", "wallet_quality"]].copy().reset_index(drop=True)

print(f"Volatility cohort: {len(wallet_cohorts['volatility'])}")

Volatility-filtered wallets: 407
Volatility cohort: 407

In [208]:
wallet_cohorts["top_pnl"] = wallet_vol_train.sort_values("total_pnl", ascending=False).head(100).copy().reset_index(drop=True)
wallet_cohorts["top_copyable_pnl"] = wallet_vol_train.sort_values("copyable_pnl", ascending=False).head(100).copy().reset_index(drop=True)
wallet_cohorts["top_copyable_roi"] = wallet_vol_train.sort_values("copyable_roi", ascending=False).head(100).copy().reset_index(drop=True)

wallet_cohorts['multi_filter'] = wallet_vol_train[
    (wallet_vol_train['copyable_roi'] > 0.05)
    &(wallet_vol_train['num_buckets'] >= 50)
    &(wallet_vol_train['copyable_pnl_factor'] >=0.4)
    & (wallet_vol_train['median_roi'] >= 0.05)
    & (wallet_vol_train['top_market_pnl_pct'] < 0.3)
    & (wallet_vol_train['top5_pnl_pct'] < 0.8)
    & (wallet_vol_train['total_pnl'] < 10_000)
].sort_values("copyable_roi", ascending=False).head(100).copy().reset_index(drop=True)

In [209]:
print(len(wallet_cohorts['multi_filter']))
pd.set_option('display.max_rows', 100)
wallet_cohorts["multi_filter"].sort_values("median_roi", ascending=True).head(100)

25

,wallet,pnl_volatility,num_buckets,num_markets,total_notional,total_pnl,copyable_pnl,top5_pnl_pct,top_market_pnl_pct,median_roi,average_roi,return,copyable_pnl_factor,copyable_roi
9,0x7656ed7f597a0a61cd307591db198a42b2a7194b,5.57,215.00,68.00,32651.20,6087.97,3294.83,0.72,0.26,0.08,0.31,0.19,0.54,0.17
20,0x47c6e09427e5581445323964afa8432803e82fe4,2.53,253.00,136.00,22419.75,3255.73,1701.15,0.50,0.18,0.12,0.15,0.15,0.52,0.08
16,0x480e1e120dba94077cb8571fa72f6bc58c7971e9,4.58,298.00,145.00,57729.14,3685.75,2833.11,0.71,0.15,0.13,0.12,0.06,0.77,0.09
14,0x12e64c5230a1ba133d5b6406d1dd83c35739ea33,3.09,84.00,35.00,11481.20,1639.76,1172.60,0.78,0.27,0.16,0.16,0.14,0.72,0.11
18,0x54fde20fa60e932fc480071e05695b42caa94ac3,3.68,304.00,88.00,35840.35,5758.24,3746.00,0.52,0.13,0.25,0.13,0.16,0.65,0.08
21,0x5124088a00cde78aab67b8c3e47d2b98a8fa91bb,7.27,699.00,444.00,67245.83,8028.59,4222.16,0.76,0.17,0.25,0.12,0.12,0.53,0.07
11,0xaf3c7d23f497ea9aa23c522a25fa291274b4f5ff,1.53,80.00,32.00,10738.56,2958.11,1707.76,0.34,0.11,0.28,0.26,0.28,0.58,0.15
24,0x522f77e63f087115ee51c7cfda1d34c0b46e1415,0.83,377.00,275.00,9908.09,1144.01,583.34,0.31,0.09,0.28,0.10,0.12,0.51,0.05
7,0x0269f11e5f0956d89417f9b508a35b2a16dc783b,2.99,56.00,48.00,6017.29,1184.57,764.01,0.75,0.20,0.29,0.27,0.20,0.64,0.18
23,0x8b552440eaefeef7d4818e6d74cf5c391a76d74b,1.70,486.00,284.00,22337.21,2319.07,1147.14,0.44,0.17,0.29,0.11,0.10,0.49,0.06
12,0x37bdf9681cecfebe1f5709d2aed823e0063c2a26,4.20,137.00,125.00,32549.03,7496.73,7075.49,0.49,0.17,0.35,0.15,0.23,0.94,0.15
4,0xb90f99021050dd7da7e5a9a8a63fc9b3fbd4ea7a,3.16,57.00,36.00,4620.68,1174.51,741.71,0.71,0.29,0.39,0.30,0.25,0.63,0.19
22,0x4fb060ef365ad6a76d8da1387ec6a7372d4b3182,1.87,1980.00,921.00,71835.22,5041.03,3665.51,0.39,0.11,0.43,0.08,0.07,0.73,0.06
6,0x8caeaa76f4a9eb8e19715c12f7eddedeabdab135,2.58,87.00,84.00,3609.06,741.99,530.19,0.73,0.20,0.43,0.25,0.21,0.71,0.18
0,0xa772656bf37c8a62e4e91ac83beb6a7a3229ae85,1.26,57.00,52.00,2138.19,925.05,727.86,0.41,0.10,0.47,0.43,0.43,0.79,0.34
13,0xb78ddd792ad7d1f603fcd046c662d6d9adbf835d,1.48,88.00,59.00,7599.86,2266.99,977.31,0.30,0.15,0.49,0.30,0.30,0.43,0.13
3,0x8296cb1975814e52c3386a68459e8e74b75326e7,2.10,76.00,76.00,1167.88,502.06,435.14,0.71,0.21,0.50,0.26,0.43,0.87,0.22
5,0xabde435151e5cf858071cec380303acb610fd41f,2.94,650.00,206.00,57871.75,8042.63,5830.16,0.34,0.16,0.54,0.25,0.14,0.72,0.18
15,0x162f272e66376edd22c553017122ad1f19c8585a,7.86,594.00,259.00,117426.28,6980.78,4862.35,0.78,0.14,0.61,0.13,0.06,0.70,0.09
2,0xac8ede57320225a95585bef4627cbc8fc64a64a9,4.68,95.00,18.00,6331.74,2802.71,1250.89,0.58,0.30,0.61,0.52,0.44,0.45,0.23
19,0xdc32b242c97ad4c34151f690c4abb4ebe2f400bf,0.59,468.00,316.00,5325.05,725.04,624.03,0.28,0.08,0.67,0.09,0.14,0.86,0.08
10,0x2e778415f0c0e144f83d0a2876009dfe7d210368,4.05,61.00,58.00,6938.79,1139.06,884.45,0.77,0.17,0.69,0.20,0.16,0.78,0.16
8,0x865ab91c322793309506adca4f8f245e0023901b,1.23,289.00,233.00,5880.89,815.66,794.51,0.39,0.19,0.75,0.18,0.14,0.97,0.18
17,0x902ec8d1dca94db373d212c136650929417c5f41,6.97,67.00,49.00,20450.80,4869.75,2154.33,0.78,0.25,0.87,0.19,0.24,0.44,0.08
1,0x8b0244a0ded9943470a6bdad9050dce24bb1f3d9,3.16,101.00,61.00,11751.50,6244.51,3708.88,0.36,0.19,0.92,0.53,0.53,0.59,0.32

## Build and save strategy registry

All cohorts × all trigger variants → persisted `WalletSelectionStrategy` files.
The backtest loads these directly.

In [210]:
from polymarket_analysis.wallet_selection.selector import build_strategies_from_sweep
from polymarket_analysis.strategy.registry import save_strategy

all_strategies = build_strategies_from_sweep(
    wallet_cohorts=wallet_cohorts,
    signal_threshold=SIGNAL_THRESHOLD,
    selection_metric=BEST_SELECTION_METRIC,
    top_n=BEST_TOP_N,
    sweep_df=cohort_sweep,
    extra_metadata={
        "end_date_train": str(END_DATE_TRAIN),
        "train_a_end_date": str(TRAIN_A_END_DATE),
    },
)

for strategy in all_strategies:
    parquet_path, json_path = save_strategy(strategy, WORKSPACE_DIR)
    print(f"Saved [{strategy.strategy_id}]  wallets={len(strategy.wallets):3d}  trigger={strategy.trigger.fn_ref.split('.')[-1]}")

print(f"\nTotal strategies saved: {len(all_strategies)}")

Saved [volatility__score_threshold]  wallets=407  trigger=score_threshold
Saved [volatility__all_open_buys]  wallets=407  trigger=all_open_buys
Saved [volatility__copy_triggers]  wallets=407  trigger=copy_triggers
Saved [top_pnl__score_threshold]  wallets=100  trigger=score_threshold
Saved [top_pnl__all_open_buys]  wallets=100  trigger=all_open_buys
Saved [top_pnl__copy_triggers]  wallets=100  trigger=copy_triggers
Saved [top_copyable_pnl__score_threshold]  wallets=100  trigger=score_threshold
Saved [top_copyable_pnl__all_open_buys]  wallets=100  trigger=all_open_buys
Saved [top_copyable_pnl__copy_triggers]  wallets=100  trigger=copy_triggers
Saved [top_copyable_roi__score_threshold]  wallets=100  trigger=score_threshold
Saved [top_copyable_roi__all_open_buys]  wallets=100  trigger=all_open_buys
Saved [top_copyable_roi__copy_triggers]  wallets=100  trigger=copy_triggers
Saved [multi_filter__score_threshold]  wallets= 25  trigger=score_threshold
Saved [multi_filter__all_open_buys]  wallets= 25  trigger=all_open_buys
Saved [multi_filter__copy_triggers]  wallets= 25  trigger=copy_triggers

Total strategies saved: 15

## Strategy registry summary

In [211]:
from polymarket_analysis.strategy.registry import load_all_strategies

registry = load_all_strategies(WORKSPACE_DIR)
summary_rows = []
for sid, s in registry.items():
    summary_rows.append({
        "strategy_id": s.strategy_id,
        "name": s.name,
        "selection_method": s.selection_method,
        "num_wallets": len(s.wallets),
        "trigger_fn": s.trigger.fn_ref.split(".")[-1],
        "threshold": s.trigger.params.get("threshold"),
        "dynamic_sizing": s.trigger.params.get("dynamic_sizing"),
    })

pd.DataFrame(summary_rows)

,strategy_id,name,selection_method,num_wallets,trigger_fn,threshold,dynamic_sizing
0,early_entry__all_open_buys,early_entry | all open-buys (fixed stake),cohort_early_entry,13,all_open_buys,NaN,False
1,early_entry__copy_triggers,early_entry | copy all triggers (tight slippage),cohort_early_entry,13,copy_triggers,NaN,False
2,early_entry__score_threshold,early_entry | score >= 0.65 (Kelly),cohort_early_entry,13,score_threshold,0.65,True
3,last_ten__all_open_buys,last_ten | all open-buys (fixed stake),last_ten,10,all_open_buys,NaN,False
4,last_ten__copy_triggers,last_ten | copy all triggers (tight slippage),last_ten,10,copy_triggers,NaN,False
5,last_ten__score_threshold,last_ten | score >= 0.65 (Kelly),last_ten,10,score_threshold,0.65,True
6,multi_filter__all_open_buys,multi_filter | all open-buys (fixed stake),multi_filter,25,all_open_buys,NaN,False
7,multi_filter__copy_triggers,multi_filter | copy all triggers (tight slippage),multi_filter,25,copy_triggers,NaN,False
8,multi_filter__score_threshold,multi_filter | score >= 0.65 (Kelly),multi_filter,25,score_threshold,0.65,True
9,quality_core__all_open_buys,quality_core | all open-buys (fixed stake),skill_sweep,50,all_open_buys,NaN,False
10,quality_core__copy_triggers,quality_core | copy all triggers (tight slippage),skill_sweep,50,copy_triggers,NaN,False
11,quality_core__score_threshold,quality_core | score >= 0.65 (Kelly),skill_sweep,50,score_threshold,0.65,True
12,smooth_pnl__all_open_buys,smooth_pnl | all open-buys (fixed stake),cohort_smooth_pnl,50,all_open_buys,NaN,False
13,smooth_pnl__copy_triggers,smooth_pnl | copy all triggers (tight slippage),cohort_smooth_pnl,50,copy_triggers,NaN,False
14,smooth_pnl__score_threshold,smooth_pnl | score >= 0.65 (Kelly),cohort_smooth_pnl,50,score_threshold,0.65,True
15,top_copyable_pnl__all_open_buys,top_copyable_pnl | all open-buys (fixed stake),top_copyable_pnl,100,all_open_buys,NaN,False
16,top_copyable_pnl__copy_triggers,top_copyable_pnl | copy all triggers (tight sl...,top_copyable_pnl,100,copy_triggers,NaN,False
17,top_copyable_pnl__score_threshold,top_copyable_pnl | score >= 0.65 (Kelly),top_copyable_pnl,100,score_threshold,0.65,True
18,top_copyable_roi__all_open_buys,top_copyable_roi | all open-buys (fixed stake),top_copyable_roi,100,all_open_buys,NaN,False
19,top_copyable_roi__copy_triggers,top_copyable_roi | copy all triggers (tight sl...,top_copyable_roi,100,copy_triggers,NaN,False
20,top_copyable_roi__score_threshold,top_copyable_roi | score >= 0.65 (Kelly),top_copyable_roi,100,score_threshold,0.65,True
21,top_pnl__all_open_buys,top_pnl | all open-buys (fixed stake),top_pnl,100,all_open_buys,NaN,False
22,top_pnl__copy_triggers,top_pnl | copy all triggers (tight slippage),top_pnl,100,copy_triggers,NaN,False
23,top_pnl__score_threshold,top_pnl | score >= 0.65 (Kelly),top_pnl,100,score_threshold,0.65,True
24,top_ten__all_open_buys,top_ten | all open-buys (fixed stake),top_ten,10,all_open_buys,NaN,False
25,top_ten__copy_triggers,top_ten | copy all triggers (tight slippage),top_ten,10,copy_triggers,NaN,False
26,top_ten__score_threshold,top_ten | score >= 0.65 (Kelly),top_ten,10,score_threshold,0.65,True
27,volatility__all_open_buys,volatility | all open-buys (fixed stake),volatility,407,all_open_buys,NaN,False
28,volatility__copy_triggers,volatility | copy all triggers (tight slippage),volatility,407,copy_triggers,NaN,False
29,volatility__score_threshold,volatility | score >= 0.65 (Kelly),volatility,407,score_threshold,0.65,True

## Wallet PnL over time

Three independent plots:
- **Training plot** — cohort aggregate cumulative PnL over the training period only
- **Test plot** — cohort aggregate cumulative PnL over the test period only (starts from 0)
- **Individual plot** — per-wallet cumulative PnL spanning train + test, with a train/test split
  vline and wallet address labels; test portion resets to 0 at the split boundary

Set `PLOT_WALLET_PNL = False` to skip (e.g. when running headlessly).

In [212]:
PLOT_WALLET_PNL  = True
TOP_N_INDIVIDUAL = 10   # wallets shown in panel 1 per cohort

In [213]:
_trade_files = sorted(TRADES_DIR.glob("*.parquet"))
df_fills = pd.concat([pd.read_parquet(f) for f in _trade_files], ignore_index=True)
df_fills["dt"]               = pd.to_datetime(df_fills["dt"], utc=True)

# Normalise grouped schema → canonical fill-level names
if "total_quantity" in df_fills.columns and "quantity" not in df_fills.columns:
    df_fills = df_fills.rename(columns={
        "total_quantity": "quantity",
        "avg_price": "price",
        "trade_value_usdc": "usdc_amount",
    })

df_fills["usdc_amount"]      = df_fills["usdc_amount"].astype(float)
df_fills["final_value_usdc"] = df_fills["final_value_usdc"].astype(float)
df_fills["quantity"]         = df_fills["quantity"].astype(float)

In [214]:
len(wallet_cohorts['volatility'])

407

In [215]:
wallet_cohorts['volatility']['wallet'].to_list()

['0x82307f44c9405e73dc1cff466073dcc505535121',
 '0xede186f37ead91aa618cf8101db2bfe6b6c57dd1',
 '0xfe0ad5ed4c912a46a4e41198e673bd371c384a63',
 '0xde5830e0b75b31c466fc64aa2313a1e07e3f8610',
 '0x8d5c3994aab4d5a04418d0f10394f3b398bab756',
 '0x9bc8e9f0c3ada70da1a82f3051448b6cc4783361',
 '0x071682d3d8ea0e9e7f69e370b47830109c0b5ff1',
 '0x6ef453ffe9139352188648263d1e644aede783f4',
 '0x7eb134f39c4809a15cf8a41218a2a64c8c45fdb2',
 '0x126073a6eca0937c642a6f69f0c8e98030efb85a',
 '0x4427b362e3c00a3dc41d0d0eea1ec86bd0880e7f',
 '0xb89190c659af6087669fce8a4c9dc0f2102e969b',
 '0xb22d3e8d06bed1d38f5f0336d43c0b2ab5d5b530',
 '0xbdc2b2d3eaf1cc272267127b74d841d6cfe3e7c9',
 '0xe0c589813f2bf5315171a035604f64178ca77aa9',
 '0x5f59a5196372d454d62d51ba5f1a83b2cd88152c',
 '0x4162cf0487763d777bfdfbe6a54c5fa2bccf5a99',
 '0x963e75d62f11939a96d0fcc1a67bafac29004383',
 '0xf8fc0d2cc44fcdc74e1bab5590d49bfe812704aa',
 '0x08a807c407cad0a33646243bb598889007844c60',
 '0x1190b18ddbf41ee89798077c42fce20f261f936a',
 '0x78c4334672edbb81a11866ca4f26a17241d43203',
 '0x60a5243f45012677c7dc1c81ef3034eedb292da4',
 '0x8d0429233005da1cdc45c03e1f4b597bd59862aa',
 '0x0b9dc84cf570a39546d856927cf1f131b70b787c',
 '0x1d7f4976c7759e280f1bad4a4f8e8eb191f9f6ed',
 '0xfafdadaf7ecfe1a884420eb4165cc7e806e04da0',
 '0x75e765216a57942d738d880ffcda854d9f869080',
 '0x3335de45972fd32e5d8a3b689e772147f2693656',
 '0xf5f3174dac5631c808d3e38a10aefd60b3adcb3e',
 '0x641b56cd1de69da37e9bfefeddc7b277341c5433',
 '0xaa789d2b1467cb5b1772601723cc8456edcf698b',
 '0x1dac7146c24a271f93244db373a13d69166211bf',
 '0x0c058138ee8749433656cb5c696e0fd3dc7dfabf',
 '0x50e07c12596fd2513d066698f1e8d2e624287132',
 '0xc3bff4a4a661ebac290d51edb09f003951df2a0f',
 '0xdf207b231a91122fbc181093346a73894eca1940',
 '0xeb4366fbe48e1609c568a46a46f8d6d95413187f',
 '0xc63a2c66b5d008d428872598533ffa47780b6fc0',
 '0x92a2701ef184ee45ee2a19fd08dc65e8e1422f5f',
 '0x236599e3745dbea9d285d7ac967846f476d8aaf4',
 '0x90ed5bffbffbfc344aa1195572d89719a398b5bc',
 '0x2ee9d1721dd8d38bd05374417ddfcba187a12362',
 '0xc6c9676048fea6242c818f0566f97de45bb582c1',
 '0xa772656bf37c8a62e4e91ac83beb6a7a3229ae85',
 '0xaeb6ffae1741f72a47bfe571c9a8b49a458a6d93',
 '0x46bcbaf94922970fbf7100d36e3ed3a72f702d14',
 '0x885f394114536f6fbde7d388de58499a1de808a9',
 '0xe35378b7dc1ce78fb0c99bc47408d359e4115a51',
 '0x363b7f38567babedd077953fcbfca6f7b30bfb76',
 '0xd435c6f901b642e8f7a0e8adada4ed5db7856e5e',
 '0xf2cae58953c73cb722ba70ab694d3779b6e4b467',
 '0x8b0244a0ded9943470a6bdad9050dce24bb1f3d9',
 '0x714a648585eff0ed8c5f6efa4daf61d85363e775',
 '0x18163e531ca2e5e864c5069ea80601b82599c3f9',
 '0x4e3632a4299df465b5590028e7d1c6bdbdfc1195',
 '0xa6a1071f7ae99c5f972b61382921eed379673b93',
 '0x5d8c1750824c99abfe20ca73ce1ec6894b048527',
 '0x2ac4d531a8b5e91a61124d2beec02a83194b4c7b',
 '0xc364d68932f1e737bcd7708628f2c2450f81c413',
 '0x46c2c0ba75742d38f348874ab85e7b7843c3966d',
 '0x62dfb31c90dcf1d960726218555b7ab89feff7ae',
 '0x580ce341b4c99b541c07213b56926a4b23928438',
 '0x742c04c3978a848dbe85849bd8a229eceaca5d8f',
 '0x0176ffeb5f21db79054eec8ecc90a2fc3ab7ff71',
 '0xdfe21c292286d4449ad320c01a7096ae7ccf5f33',
 '0x17d0101982318fbbac0450d49100d4463a8d8a25',
 '0x6d5d270aaa9c6f04c3c2ce256ad37ca0ecabc54f',
 '0x662db7c3b714e9e3162e45764a9b56db9055e112',
 '0x1e940a1c70152b34a2ebb5706fefaf88f84ece75',
 '0x76ca37e810b694963926bc19ee38d6580d046a3a',
 '0xb6209f5564cc178f3db6cd51fc145ba60f0399f2',
 '0xa251486af5af47b0b3a287c498b225a357018a4b',
 '0x4d16e11451096393f1326b7747a2db8799ef0c02',
 '0x6b68d331f8c8c56dd73ba27a30294f813b36913a',
 '0xbbda94aceda34f4d8cc4504b8950ce1502036e2c',
 '0xaca1f810cbe5264ac179ef5e73fb895979300492',
 '0xf13bc7526456c46b62dac7ee210a957adbe89ef9',
 '0x865dab442e6a93936e52d8033adca779af7447aa',
 '0xb162b2bad3722d9561ff7f6cd920ceedbb1240e8',
 '0xf3a0fb336a839837f9b864324121300b7b3c6c91',
 '0x5aa1f10c184cd25e46960a8b18b6fe2257b57197',
 '0x6af08750b25723c9c5209a7c0f69d6d3ba941ddd',
 '0x9aabeb00eb554e120ca1d57f17f2c9c9718b6a2d',
 '0x0855572d2d38578415878ef0f1e59cc414fedb46',
 '0xac1afee0db8879b341d3869331158de8dbcdf708',
 '0x2be08e5492d67a11527a356d8d8426867c9b1538',
 '0x31ec93874cdff3db7d9960f3d0393e0c17d4e406',
 '0x5c85faa9e70e32ee227ce318906f81fc67185cd6',
 '0x8b72cb885a6bd4ea9d1da393ca231f0fa3476dbe',
 '0x4cfa6c2c6f4b052984efe6d78d36948647e367e0',
 '0x14238ebc01567699007e82b7034387e1ee0c9f78',
 '0xf83033e71ab7769c15da51b60d3492196851c2db',
 '0xd767f745b9cf19efefd9d17bb0f24cc1f59c0a93',
 '0xac8ede57320225a95585bef4627cbc8fc64a64a9',
 '0xf93d65619ca54932b134cdfb5ea91d312bdaf36d',
 '0x98689f5983898c1da0ec7a9f0864d478f3bee82b',
 '0x7ca66e570fad33f1c63fc1039790d183a2774123',
 '0x9d5f391fc63c8a887a8cc3a10fa4b065637084bf',
 '0xd6e26297e4330f7e444f4c7e3cb5ca1a3a92c751',
 '0x8296cb1975814e52c3386a68459e8e74b75326e7',
 '0x5c4aa9a1d52cb9eddb9234609d809e811901df38',
 '0xd3c74420d547771b5ecf5506da840330bb8dc7c5',
 '0xe082c07538bba2536ef5166226a28749a7d6aa2e',
 '0x40d9ac81a425f14d2c490c41ac8969c0cbcfd472',
 '0x742f27a189791e20a5b85437f001cc9859fdb3d6',
 '0xa924ab525445bfaee728f3c648b4fa87157cb1b9',
 '0x89cb72636af04f72826672f55437668ac538e7b5',
 '0x4daf9abb4dcffd6a191317827f967fb230b63b21',
 '0x03a9f592e5eb9a34f0df6c41c3a37c1f063237ba',
 '0xe9f3dc586abdc365281e91508c2e81cb9be47d5f',
 '0xbcb253ae67a40fd4271b7b8394c0d958245c8f34',
 '0x648c4c04af676edb16881f24a8579fbf71e992e8',
 '0x03ae42814b5b4b5ff87efc4f403be5fc233ebf79',
 '0x993b364feffc42346e28f242d1ad57446c70deda',
 '0x9645778f19a0157179c8f975d37c2c3b197bbdbe',
 '0x388451e16fa4f9719b7a810771da8086c769398c',
 '0xde6dc1303cf974573082716fd38a6b892642220f',
 '0x8ddefed8a03eb5eda34a9fe2f00fd43929eef2ca',
 '0x0673e519d7bbe9f736b0a7eda1bd4bd47676406c',
 '0x520b4a0452005517964ee864985f2026d0dc100a',
 '0xe6614d3451f3ca1ec8a42572fb05c0631a77c653',
 '0xd56758b87ff41936faf8bbeaf1d5dd82df2b68d9',
 '0xc7605539b14fe99ff3a3d2a23dd833138383a21a',
 '0x35027d4493c57e34c606435935feae431fe77955',
 '0x6560abb717a8e5f3afaacd1a31e9c03eed71e164',
 '0xa09a96aca62a6cc596654781449901e43865a5b2',
 '0x1c10c20a4eb48523e91454d65dfa4760efbf1cc0',
 '0xef6e03ff137fe725eeee2254ab6eceb1e2a36cf3',
 '0xf47fded73e414b63b4535fe490cdc9e4219fe84a',
 '0x5ffe73adf88eb454d1b93a1c9866325996f92864',
 '0x3f6266563d35813d5dff71147f1e7ad8616dd90e',
 '0xb90f99021050dd7da7e5a9a8a63fc9b3fbd4ea7a',
 '0xdd1be44bd9c183480232f32925351c7127b0be7b',
 '0x0dcdc3a827f9f56cdc14dba817385d8d628fc3d4',
 '0x6fbbd19e716f7454bdf483c41e6fa276a9e139da',
 '0xfca8166ec0bdf5a3246a4e651e2a7eb344052e4d',
 '0x9e8ecc4cb3c4e48f544cba2fbbb252a6a65e8db8',
 '0x46b2f91027bfddfadeda5768b2c50bef74878f9f',
 '0xabde435151e5cf858071cec380303acb610fd41f',
 '0x571a08ab5d5f2f568eb29529cc6b7447a51eb034',
 '0x8caeaa76f4a9eb8e19715c12f7eddedeabdab135',
 '0xe193e7d42b2c411871b33b356def7bb4422ac0c4',
 '0x7600ac7e3fe8097be7909ad78224aefd0baf4478',
 '0x6257dce5bac3a8859a24600210ff03401b2fbd72',
 '0x738544c373c07e07cde001282d20dc9c55a6194c',
 '0x0269f11e5f0956d89417f9b508a35b2a16dc783b',
 '0x2b46bb71681777202368d095196f266944a1684d',
 '0x2d613c30614b68eada0a37d65bddf3778d981fa7',
 '0x865ab91c322793309506adca4f8f245e0023901b',
 '0xa7df0ed1324ec784cb646703dcfe649bc6b3e19f',
 '0x80a09d9599b82cd54cf50e82d8a243e753552bbf',
 '0xcdf22188fab4ffaf9ef3eae5deff1909840d1b2d',
 '0x5332d74a46099fc92040c850162dce15ff20545c',
 '0xc13f2a97dd2a68061c1b382568b7bd711a08c93b',
 '0xd4967e8b78cb5212b4cde2b08877c136f884c28f',
 '0x1bc0d88ca86b9049cf05d642e634836d5ddf4429',
 '0xd37dc390fd9f6a5237dda93d6e07885ebe21b897',
 '0x7656ed7f597a0a61cd307591db198a42b2a7194b',
 '0x04823600eb2464429757db04fa52efe6e83b5c56',
 '0x38dacb9c024e69cb5608ce621821240a0eac01ec',
 '0x83c8005b5af05829aa269b8d752b6d1945019541',
 '0xd5b97d08ec6098407bfbf66c2786ccc9967fe44e',
 '0x17e9a22d1733f26f18af3157864c1da0e5eafcc9',
 '0xc00fe74158802e38688cba5498f9b78c68ea0f52',
 '0x88082b0705522c899be41c5ddf2e3bec68cd75a8',
 '0xd1105b3fc943eb277af3f54654a0b4610263ed30',
 '0xe59941eb2d8ba4acae6e98c49b85f49558bd53bd',
 '0x5754becbe873d6ba9eefa4eedf214dd254ece515',
 '0x2e778415f0c0e144f83d0a2876009dfe7d210368',
 '0x5c89f96764ebe08ff7ca7174e2acfe843f788354',
 '0xda8a6ccfab19d8a1c739e499a6bcf248d48a223c',
 '0x123db09e6390127165afca0da5f0535590e70695',
 '0x94f3c2d8ce305f009302d3ac051d27fdcdbf4895',
 '0x3dac3f5fb0e4066a6a7fa9c1a4eaa2db546e5e12',
 '0xf6c378223093081de84543fdac57db12d9eb0484',
 '0xe8fbc8c4868f2da335e5f6bb2c7bee55bf340bb8',
 '0xd7951f1ff7880761dcb3d186630d86047dbf6fcd',
 '0xaf3c7d23f497ea9aa23c522a25fa291274b4f5ff',
 '0x7db081239b36cff0aa8e306bbc3509969e03f397',
 '0xe28eabb190539dc42f2d50f4a902cdbc0f61ac9f',
 '0x264bf42e23a945a38a0c9251f8197cb3be2fcf7f',
 '0x557da24111fe9cb075863cb4391df0805beb49e7',
 '0x5b9a9505250899ef1318d7b194fac54c7657887c',
 '0x9cb32ec9c4d72d6617f00b57ab0745aeacafb631',
 '0x154794795d978c5890b3f69264311f0bd966d066',
 '0x37bdf9681cecfebe1f5709d2aed823e0063c2a26',
 '0xf9a02e8345a44e31b765ff6eb5f35aa305ea0e1f',
 '0x4e25605fd905e9972efc0f4d8814530c655cd7a7',
 '0x3f2c9b3d2d7a09143f810940b4da51ac90b2f0cf',
 '0x3ddeb89322e09cb7c909ab05a5024ae5ce7e2c06',
 '0x189a227b148b9c9fedbc9567c69bf755712d84fc',
 '0x76120391ce475c15ac3cab5ce78ec47fad85f717',
 '0x6aa092e91513a2a98e4a521de10ef54d953d9d5e',
 '0x9172fec415f1a6ab5e9e509577deda9a357a93f2',
 '0x207e8edc66e2d0465053686e8bdf8b4e230d3499',
 '0x801ed774db6a5981945a825074a6b91788f6ad90',
 '0xdb838b48d59f88c74a4e327922d2426d8a150831',
 '0x2b76c1d12cd928b1d95a6d2c7f1e6f6e7f14edef',
 '0x739aed0d8149404ef7ed12d5a08c838fcb92eada',
 '0x5a39e5c7c40de63294d596b06124eec78ea29e71',
 '0xff48dc04e8f09e3f84a3e682a8a65157be453ad0',
 '0x4de408eef41e7a0fa675302c615b8d1264e4abea',
 '0xf9199a9739ff35570b7e971f2e72b241a99d128e',
 '0x65b46b62e213c6d442a94fe2cd31e08ce5e7aed7',
 '0x5a2bb79b06b64edf7cf80497f9de0d961609ae0c',
 '0xccdb7d6b741aba0873690476fa14b365f403ffa9',
 '0x78065018ffc5b3d676b20295cddc47fe564cc203',
 '0xb49c1be187c5feda9ab33c54f4b417d8ebc49c9a',
 '0xc0ae9b1a8c227b4b6452c74b4ae585cd78b19d57',
 '0xa02b34d4811c01d9b7682c8bc14769a48c6170d6',
 '0x72f03f5b574793baff3a65fa19f9625da082e616',
 '0xdaa6a2cd4ba545befb3dbdc25d2b444c46873e62',
 '0xc39def5fd10ac841f927cd2ebd261f0451a4a8c5',
 '0x66c1cc4f994ee99a2f5977a2e071cbfd65852c72',
 '0x68389646246361ec06fb26870be72fc2f7140777',
 '0xe3e89a10792c6e5cab23bf1fc56621e9e6653f7d',
 '0x3de31543ad3ac375de649af18f28a86e17987d50',
 '0x5a89a6550d044ddfd09cccd3fbf541a129da9b57',
 '0x489f44b0b019992693131b7ebb0ad9d192dcb348',
 '0xf87cfb9774b8a1b2eaa6f81f011fb732369e0305',
 '0x9ff24b286fdca278acd82a0fe449e5d4b1c23d4c',
 '0xb78ddd792ad7d1f603fcd046c662d6d9adbf835d',
 '0x84a9c4048f98979398f253d75f3b112b45e8b878',
 '0x3de2a0ef48c492f7c87491786a7f1359ed42ca41',
 '0x9fd422b784381d14f1d04455ca88b31564385c1e',
 '0x2b30ebd85ae00628814cb923f5b8aa1932eb19bd',
 '0x91667e40b80c447050904b042f3b85d22fc6b479',
 '0x75ff7aac19b4a2545d3ebab0d71dd0898e7b08d0',
 '0xb5e7455a18a5db60f622a1ad7cc65e678f91980c',
 '0x051ca51871df8adbecceaf1f57c8b2927e02f25d',
 '0xec0bc5b9d6f9cf4e88706d1e3efe333c6ee669e6',
 '0xd1ba13e6204db994b4d7953f59eb1f1ffc6253e0',
 '0x9cddb1ce9c395a690806bc5df025fbf6b1ff3974',
 '0x486a739419c57f9e83bbb309aafadb54ff31a13f',
 '0x9ee2267fd76fe3b69ae8fc42bc454a7faabd2846',
 '0xd84176e412a2813ef70ebf1a760c2f22b628b5d9',
 '0x904261291f0284fd10fd143715776a3527422125',
 '0x029662711382aa37238cd8828cdbea287e798a9b',
 '0x09086358ebe0bb003a6e41658a04c564565261f5',
 '0xac1fa693047ef6fff2b5719a094a26e13ac8c6ad',
 '0xb604df9f6c6dcb1826e68030d895f0b62cd7f113',
 '0xc2ca284fc3ad126b565f018c93e94241edcb54a2',
 '0xc98b99ed7f9748fb3eb8d13d0e4531d023286430',
 '0x12e64c5230a1ba133d5b6406d1dd83c35739ea33',
 '0x35b5eed4dfa7beb2292de214523c2fa294bc93c2',
 '0x74ae1ea55c4e4b19de9f694cc64af81c24bff4a9',
 '0x5fc04a3d6351ee84000ec50bc1fbd0ba0561a988',
 '0x20a89c60befe1e2d866042deed93ab72be6fd960',
 '0xe8f3ceb54f83f7e87b797a64c45a3bf11a434ef6',
 '0x0c2b5e02ef76614fd80581fd6c4542444998ba36',
 '0x6a88c5ecd262e2c42e78bad8e6db7ab3c4e4b859',
 '0x33ba4c67126f16fadbeb85893ec892b2b0afc4a4',
 '0xc11b16ef82df0252b60a4f1e4a9183b8c8dae7e4',
 '0xe5a35b635142e3bbfd3d5e3f70d01be53c3944ed',
 '0x78be8635ea215dee3383537f49cc1eaf0922ddc8',
 '0x28a007d9b545e127853ede7337953980464468fc',
 '0x0ebaa2e35bcf40e59348d7bbacc21364f4c40aa9',
 '0xb7e6401b4c3c303d14422416457a4ea90fbf54d5',
 '0x239ef5c5c7ebcb8385a85da06d973c47e882ef98',
 '0x6c9ae4cd62b6a584820cc26ea5f2dccab2ef2d63',
 '0xb901ed54b0fae631e836c69c1130a571c35e1477',
 '0x5c3a1a602848565bb16165fcd460b00c3d43020b',
 '0x852a61deac7872fff2c6a80ee82c059d6a8d3188',
 '0x44c58184f89a5c2f699dc8943009cb3d75a08d45',
 '0x9ad0493f2a2cb88bf05ae4288d3c9f6736ab58ef',
 '0xfb681e23db8d1cca8a6b7e2a70a29e000ddfa240',
 '0x10cd300d4a8dde929dd5b00972081001ed3b8433',
 '0x3927d879113c435ad2bb77d24d9c455863382903',
 '0x34476a91b0af7f38c09cb04082d561bbda4f7aa4',
 '0xf6de8f922f3e7cefb31eb87799059c949c0f95e8',
 '0xd0b4313113f8ac3c43e921228df7faa9a33c919c',
 '0xfef0163f472acee028b09c8b97d44278de587708',
 '0xb14dabe5c67f8ed680509a2f06733c244ca5290f',
 '0x76ed2caa9604f3a3b3770d47161190d871f1fa48',
 '0x496164f139d7f4a1f93cd355f8507ebcb77cf59f',
 '0xb55f6fb8aaa4af67a35fe7a8ba45f66a3fd852cb',
 '0x09074fef2ffd6b95c1b004af983b61322ec07315',
 '0xeae41aa9c1870020d41f207e5b43de606a56bf9e',
 '0xea00216f723c856486199535d5085ed6091723a7',
 '0xc1279f0580792e964583e486a07ffa2b06fb66e9',
 '0x162f272e66376edd22c553017122ad1f19c8585a',
 '0xda3a9b7afff7b44ad4fd75308723194e0a11381f',
 '0x480e1e120dba94077cb8571fa72f6bc58c7971e9',
 '0x444e9c57c9a85d4271ea95aa2609dac0e78a1a78',
 '0xf71061cce6d1ab8aaef8f6928a4fdb5dfe15edc9',
 '0x324d6b10e533076b7a4e6409edb3e5853237f1c8',
 '0xffd0bca48e1895768af6f6b5e77f0a3b023d4aeb',
 '0x7f458ca5617a6eefdd314402ccf63e8213c632fc',
 '0xda277509d8778d58d9c0f6da8e654d91d9045c0f',
 '0xe174475bf2abfef1364493e92f467e28ba0df74b',
 '0x66b5c7a745c318e57a7219d9f866a5f3b002b26d',
 '0xdab288c0b6e92de1c5949545f460b45995829e92',
 '0x2e00d79f8c1320d432d1bc519d2a172891a700b4',
 '0x2d51e0f79369d305e717a76f326cb7be58c29761',
 '0x2f58202ea056be5700ad0394d2b7e768026ba13d',
 '0x355e5ae20cc1a3a2164f818e4bac8d22dd72a038',
 '0x87af6dadcea1315313c618e0f31631fdf11224a4',
 '0x699896b06cd0c2205de8f8e13112aadcfc29ae95',
 '0x9f7b570328009f2a28c8e916d16b727f9d6271a9',
 '0x7960f86f8f43d8830a16de52537c35ae1b92b94f',
 '0x96d9da943660be27aed7230166eaac467c5718a0',
 '0x7f0f780b9eceeb62d5c28e5e61859394a8384f31',
 '0x3df7a56c681d7342a638118d8e7fa8f6c31e17ed',
 '0x9b008e690fb470c37e825f3da1f5334c820ba757',
 '0x902ec8d1dca94db373d212c136650929417c5f41',
 '0x53ebdde1d8a909652485cead2fd454a5426b7d54',
 '0x27ab2fd23f340f214857f1c05dc99cc221c28b78',
 '0x8a924f330c0d15d6295c4cbb89b93eef5d5c6941',
 '0xcf0aca0d7a395202aec661c3666be9cc098e320a',
 '0x12d7709147fa888dec340abfa76532b0d60041eb',
 '0xba144c299177b5d790c60d6ed697c04ddf44b792',
 '0x54fde20fa60e932fc480071e05695b42caa94ac3',
 '0x0903bd955e62cf7782015e04a6dc84883268b95e',
 '0x93abbc022ce98d6f45d4444b594791cc4b7a9723',
 '0xaa5211d8e0e6aa5b2f9bc861db6852e262d761de',
 '0xdc32b242c97ad4c34151f690c4abb4ebe2f400bf',
 '0x26ae7610923503348c1d3905c4b8e321bbc06a87',
 '0xcde1829e3672079480ccf971aa804472b430552d',
 '0x47c6e09427e5581445323964afa8432803e82fe4',
 '0x3a3ebc5179ab0fcc4c7d2b9f8ae5b5189bbd0d89',
 '0xd96ecf0c76f6c38e8fab776d1b3d423dfb961ed8',
 '0x69446f722854c6cdd68b0e014c1d24bdbfae0060',
 '0xf97a6ebe37d27583b03121aed2810b2c544707c9',
 '0xc7b8a3f1033a9efa9d912b60885c1d2c1e012c1f',
 '0xe1cfc7d1906ccf1c5d10393c2560b81b7326c995',
 '0x6d21f34a73c1f268d4eb8f13d20ca89c8887abbd',
 '0x1c144e30f405a25f991cbd8baa15d40599090869',
 '0x92d0cb81e6c891b835c8e0272e8c323095bd269e',
 '0xa69b9933a2b7cdeeffaf29a119543f743c397b0c',
 '0x6a0c91301370bad22a3649efd5b0a06247243f90',
 '0x48898de94e70ca0c06c62c57483b3a8d5890e2d8',
 '0x9ca119b8cd7bdb890aecf1ff3b0f6e3a45cc13b5',
 '0x882e3b3f40a9e6c8b597dffc72d0d87dc95be757',
 '0x2dbd020f635afced8a2a4de283014e0c4ecf4219',
 '0xb6418d1e10a83fc1f9ed843013f5ebaeb0b32208',
 '0x41583f2efc720b8e2682750fffb67f2806fece9f',
 '0x3db4c677e267cba4982c8d286c5544c72220d69b',
 '0x94a148b40aae95e8bf2bd2ed428eff4097372075',
 '0xf19ff417bf80dea2fed2704af8cd1c17869098c2',
 '0x69bc24c9de2a28bc60ade389b6d66c785c71577d',
 '0xdfda5fe95b0eca722011ad02909bf9ae2df92a81',
 '0xc757850237e266d3b08d16b8455777a88590ccfc',
 '0x6b61b495ee20b5a161b7f75649e3b8888b217a33',
 '0xb0f6dfdd6cbda54d27cec465310af422b9bfa31c',
 '0x10cb0bbd847cc9de1986401e36a42de14fc709d6',
 '0xa918dde348ebe3c2078a3d03ebfa95f19fed8d4b',
 '0xec54bcb41d23fe724cf6a5569cadebd1180ac7b2',
 '0x6d8c80da967b83d87b3b369d0dcd20566d6ba079',
 '0xc949b287f5f6b616034ffeafa286d17aa936fa93',
 '0xde1203e002b6e2ed309b121812336f2f978f63ef',
 '0x80f0860d9afa090b2837cad73f24bea71d5e1ebe',
 '0xc3cd1d612bbf9fbf80da5a9bff0b0470cb46816c',
 '0xc5b5bbd42624a8f0c8dfa90221913007d8c77e80',
 '0x2976a8a1e130415c9a7f47ff29f288b82373704e',
 '0x1f4fed5158189c40ce7b44ea0c3d0eee16086ddd',
 '0x0dedae6a02ea2ff8018ba5f277632919ed1c9025',
 '0xa354c4d6bc6dbcdd804cdbac820949e7defeb85f',
 '0xb4c6c0238491389f999179d5a31f4e8e31b775ad',
 '0x5124088a00cde78aab67b8c3e47d2b98a8fa91bb',
 '0xb889590a2fab0c810584a660518c4c020325a430',
 '0xee206fbbde03bdcd8fb790a27f6cbe0bf6905b37',
 '0xc7fac0efc53d5b1394a36014207d58a1064295ca',
 '0xf20f029625df25df291a4a76c55ed5d0ca21df8f',
 '0x3532fc27e44816c2dfd9e6f53a425ee67b0e3711',
 '0x5a4825cc3d4a07bcb4688693ec2043c59e7f822a',
 '0x9841e43425dba85d4eeb3d484cbe685b55f861c8',
 '0x4da864aae118c9f6abdf36aca26bd734b1fa6511',
 '0x43fb740ac6e1ebfa43505a15e359e3e10cef52a4',
 '0xd51e71f285df4a2f2ad2b8231f5097bd0e061ce6',
 '0xd1e0c0db26fb636fb557704f05f7cd8ae4148913',
 '0x0cb10c40b0776e9ee8cef970af85724654dda76c',
 '0xf2c29fa94f5a18b1c68c00baee66155b89254de7',
 '0xa01ea43d416a4582a022fb75319ade76645699d8',
 '0x66b684bff04208d6f6a43499297cc1f09ebc159d',
 '0x4fb060ef365ad6a76d8da1387ec6a7372d4b3182',
 '0x0ede52753e3795f412b5df47f09794c0d4a117cb',
 '0x7e5246abed17a5cff43a17b55b30f982f45200f5',
 '0x481f12d29ec2579fed980366a3152d4c5917f4f2',
 '0x9aeb534c42b58b21673d5e03e9da14fbd15b2729',
 '0xebaa323f118e7113ee52c4b6e90f2e786bb177c3',
 '0xac748d88e04c1e9a67e68b13facbef9a79985673',
 '0x8b552440eaefeef7d4818e6d74cf5c391a76d74b',
 '0x9597bdbe6beffbd6542be8d807e991b269804758',
 '0xab85b40a0d684026153d45a71039de4eeed081e6',
 '0xb6b126b130d0746dfb9fd9631b28728c61fe94c8',
 '0x03ac67436f169bb5348653f991d498bcb4944f55',
 '0x52d339fe95a130f68e06a4e5add92f55c6ca11e1',
 '0xa3ecf3a4b852420b69c037442cc73aa6c3ea279f',
 '0xc2d18723e3a0fb181fc0bbb5fd435150a18a84a2',
 '0x205477e523cda7b9f6f67aca4f016890180119b4',
 '0x9c82c60829df081d593055ee5fa288870c051f13',
 '0xa4fdaa4b8ad301fec79ae46238a7ad2952210095',
 '0xf3ed9663099f62eed671ff40611446f1487bf56d',
 '0x2f6dc3bd78711699eb8cb606566dcff58ea14ad5',
 '0x26cf4a41eb49f0c560d32a2d2e4f45715e47c612',
 '0x0d1ef0baad62e10e91e2ddfd3b366bf63327effe',
 '0x9b2fcb79bdb8a6a6174da327e9335f7889c6d8f8',
 '0x94b76c6f14bb215d9b20d4af9608e9549457eae7',
 '0xb29ed9230822c94b06ad5faca94f46b007927a17',
 '0xf658449199d0bcf544de0ff928a3b66685f3dcfe',
 '0x522f77e63f087115ee51c7cfda1d34c0b46e1415',
 '0x9ded3908e1ea9c00f341d22cb22cdee14cef0d50',
 '0x61952bcaf26f0fb12c79525cdbe515ef2752b9e3',
 '0xb5f7d8addbb88193bba6cc32945bde159cce42a9',
 '0xfc8ae9908aa994999ce9256e92b5462c89c64ba5',
 '0x13414a77a4be48988851c73dfd824d0168e70853']

In [216]:
vol_fills = df_fills[
    (df_fills["wallet"].isin(wallet_cohorts["volatility"]["wallet"]))
    & (df_fills["is_train"] == False)
].sort_values("dt")
len(vol_fills)

110298

In [217]:
# last_ten = ['0x6fbbd19e716f7454bdf483c41e6fa276a9e139da',
#  '0x47c6e09427e5581445323964afa8432803e82fe4',
#  '0x3f2c9b3d2d7a09143f810940b4da51ac90b2f0cf',
#  '0x8b0244a0ded9943470a6bdad9050dce24bb1f3d9',
#  '0x0c4f5b1295f39cf505679209a22adbafe61c0f33',
#  '0xaf3c7d23f497ea9aa23c522a25fa291274b4f5ff',
#  '0xbff9efe3a976c115e3e639b4c6b9c7168479009d',
#  '0x236599e3745dbea9d285d7ac967846f476d8aaf4',
#  '0xd6f44883f664d7dc963d8b89c5a0689fdd330566',
#  '0xf201a19b43471261a3c1ba9247335d55270e527e']
# top_ten =['0xabde435151e5cf858071cec380303acb610fd41f',
#  '0xec593b3c1a9a0ed15e597dc4ea09cafbffe3bb35',
#  '0x37bdf9681cecfebe1f5709d2aed823e0063c2a26',
#  '0x702226b14b65b1c8d05ff51759e095f09932f64e',
#  '0xcf0aca0d7a395202aec661c3666be9cc098e320a',
#  '0xdaa6a2cd4ba545befb3dbdc25d2b444c46873e62',
#  '0x4a4b5d59f1979fdf45fa15c17e2ba414f2ebbbca',
#  '0x2687cb380661a0041bf4c4cf3945a034b79e1363',
#  '0xc5b5bbd42624a8f0c8dfa90221913007d8c77e80',
#  '0x3335de45972fd32e5d8a3b689e772147f2693656']
# vol = wallet_cohorts['volatility']
# last_ten_vol = vol[vol['wallet'].isin(last_ten)].copy().reset_index(drop=True)
# top_ten_vol = vol[vol['wallet'].isin(top_ten)].copy().reset_index(drop=True)
# wallet_cohorts['last_ten'] = last_ten_vol
# wallet_cohorts['top_ten'] = top_ten_vol

In [218]:
from polymarket_analysis.visualization.wallet_plots import (
    plot_wallet_selection_pnl,
    plot_wallet_individual_pnl,
)

if PLOT_WALLET_PNL:
    _trade_files = sorted(TRADES_DIR.glob("*.parquet"))
    df_fills = pd.concat([pd.read_parquet(f) for f in _trade_files], ignore_index=True)
    df_fills["dt"]               = pd.to_datetime(df_fills["dt"], utc=True)

    # Normalise grouped schema → canonical fill-level names
    if "total_quantity" in df_fills.columns and "quantity" not in df_fills.columns:
        df_fills = df_fills.rename(columns={
            "total_quantity": "quantity",
            "avg_price": "price",
            "trade_value_usdc": "usdc_amount",
        })

    df_fills["usdc_amount"]      = df_fills["usdc_amount"].astype(float)
    df_fills["final_value_usdc"] = df_fills["final_value_usdc"].astype(float)
    df_fills["quantity"]         = df_fills["quantity"].astype(float)

    split_dt = pd.Timestamp(END_DATE_TRAIN, tz="UTC") + pd.Timedelta(days=1)

    # Cohort aggregate PnL — training period
    fig_train = plot_wallet_selection_pnl(
        df_fills,
        wallet_cohorts,
        split_date=split_dt,
        period="train",
        title="Wallet selection cohorts — cohort cumulative PnL (training period)",
    )
    fig_train.show(renderer="browser")

    # Cohort aggregate PnL — test period (starts from 0)
    fig_test = plot_wallet_selection_pnl(
        df_fills,
        wallet_cohorts,
        split_date=split_dt,
        period="test",
        title="Wallet selection cohorts — cohort cumulative PnL (test period)",
    )
    fig_test.show(renderer="browser")

    # # Individual wallet lines (train + test) with split vline and labels
    # fig_ind = plot_wallet_individual_pnl(
    #     df_fills,
    #     wallet_cohorts,
    #     split_date=split_dt,
    #     top_n_individual=TOP_N_INDIVIDUAL,
    #     title="Individual wallet cumulative PnL (train + test, resets at split)",
    # )
    # fig_ind.show(renderer="browser")

    del df_fills
else:
    print("PLOT_WALLET_PNL=False — skipping plots")